// Public API of the `health-record` entity (bloom B-N6-03). Import only from here (CLAUDE.md §3.3).

export {
  BLOOD_TYPES,
  CHRONIC_ILLNESSES,
  GYN_CONDITIONS,
  MANUAL_OUTCOMES,
  MAX_ALLERGIES,
  MAX_ALLERGY_LENGTH,
  MAX_BABY_COUNT,
  type Allergies,
  type Basics,
  type BasicsInput,
  type BloodType,
  type Conditions,
  type ConditionsInput,
  type CycleSummary,
  type HealthRecord,
  type ManualOutcome,
  type Medications,
  type PregnancyEntry,
  type PregnancyInput,
  type PregnancyOutcome,
  type Pregnancies,
  type RecordCheckup,
  type RecordLab,
  type RecordMedication,
  type RecordPerson,
  type Section,
  type ValueSummary,
  type VitalsSummary,
} from './model/types';
export { addAllergy, removeAllergy, toggleCode } from './model/edit';
export { healthRecordKeys } from './api/keys';
export { healthRecordSchema, pregnancyEntrySchema } from './api/schema';
export {
  emergencyCardSchema,
  lockEmergencyCardSchema,
  useEmergencyCard,
  useLockEmergencyCard,
  type EmergencyCard,
  type OwnerEmergencyCard,
} from './api/emergency';
export { EmergencyCardView } from './ui/EmergencyCardView';
export {
  fetchHealthRecord,
  useDeleteRecordPregnancy,
  useHealthRecord,
  useSaveRecordBasics,
  useSaveRecordConditions,
  useSaveRecordPregnancy,
} from './api/queries';
export {
  MAX_REPORT_QUESTION,
  REPORT_RANGES,
  REPORT_SECTIONS,
  fetchSharedReport,
  healthReportSchema,
  sharedReportSchema,
  shareLinksSchema,
  useCreateShareLink,
  useHealthReport,
  useRevokeShareLink,
  useSharedReport,
  useShareLinks,
  type CreatedShareLink,
  type HealthReport,
  type ReportRange,
  type ReportSection,
  type ReportSelection,
  type ReportWindow,
  type SharedReport,
  type ShareLink,
  type ShareLinks,
  type ShareLinkStatus,
} from './api/report';
// CB-MENO-11: the `menopause` provider section of the doctor report (GET /health-record/report, GET /menopause/report).
export { REPORT_PROVIDER_SECTIONS, type ReportProviderSection } from './api/report';
export { menopauseSectionSchema, type MenopauseSection } from './api/menopause-section';
// Canvas-build CB-REC-04: record documents, categories, extras, timeline (CB-REC-01/02 + CB-CORE-05 files).
export {
  CATEGORY_KEYS,
  DOCUMENT_KINDS,
  EXTRACT_FIELDS,
  IMAGING_STUDIES,
  ITEM_FIELDS,
  MAX_DOCUMENT_FILES,
  MAX_DOCUMENT_NOTE,
  MAX_DOCUMENT_TEXT,
  MAX_EXTRAS_ENTRIES,
  MAX_EXTRAS_TEXT,
  MAX_UPLOAD_BYTES,
  RELATIVES,
  TIMELINE_KINDS,
  type CategoryKey,
  type DatingOffer,
  type DocumentFile,
  type DocumentKind,
  type Extraction,
  type FamilyHistoryEntry,
  type ItemField,
  type LinkState,
  type LinkType,
  type ReadValue,
  type RecordCategories,
  type RecordDocument,
  type RecordDocumentInput,
  type RecordExtras,
  type Relative,
  type ReviewState,
  type StoredFile,
  type Surgery,
  type TimelineItem,
  type TimelineItemKind,
  type TimelineKind,
  type TimelineMonth,
  type TimelinePage,
  type WhereUsed,
} from './model/documents';
export {
  LOW_CONFIDENCE,
  claimBadge,
  isDateField,
  isImageMime,
  isNumberField,
  reviewDraftOf,
  reviewFieldsBody,
  reviewItemsBody,
  reviewItemsOf,
  safeFileUrl,
  stayDays,
  type ReviewDraft,
  type ReviewItemDraft,
} from './model/documents-lib';
export {
  datingOfferSchema,
  recordCategoriesSchema,
  recordDocumentSchema,
  recordExtrasSchema,
  timelinePageSchema,
  type DocConsent,
} from './api/documents-schema';
export {
  deleteRecordFile,
  downloadSignedFile,
  fetchSignedFile,
  recordDocKeys,
  useAnswerRecordDating,
  useCreateRecordDocument,
  useDeleteRecordDocument,
  useDocAiConsent,
  useExtractRecordDocument,
  useRecordCategories,
  useRecordDating,
  useRecordDocument,
  useRecordExtras,
  useRecordTimeline,
  useReviewRecordDocument,
  useSaveRecordExtras,
  useSetDocAiConsent,
  useUpdateRecordDocument,
  useUploadRecordFile,
} from './api/documents';
export { CATEGORY_LOOK, KIND_LOOK } from './ui/document-look';
export { RecordDateField } from './ui/RecordDateField';
