// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CatalogCodeExists(ctx context.Context, arg CatalogCodeExistsParams) (bool, error)
	CountAdminCatalogItems(ctx context.Context, arg CountAdminCatalogItemsParams) (int64, error)
	CreateCatalogItem(ctx context.Context, arg CreateCatalogItemParams) (sql.Result, error)
	DeleteCatalogItem(ctx context.Context, arg DeleteCatalogItemParams) (sql.Result, error)
	// An item by id, only inside the group named by the URL (an id of another group is a 404).
	GetCatalogItem(ctx context.Context, arg GetCatalogItemParams) (CatalogItem, error)
	// Content catalog (CB-CORE-03, docs/canvas-build/catalog.md): /api/v1/catalog/{group} and the admin CRUD under
	// /api/admin/v1/catalog. Shared, admin-owned content — no user data lives in this table.
	// One group's active items in display order (the public read, cached per group).
	ListActiveCatalogItems(ctx context.Context, group string) ([]ListActiveCatalogItemsRow, error)
	ListAdminCatalogItems(ctx context.Context, arg ListAdminCatalogItemsParams) ([]CatalogItem, error)
	// Every group with its item counts (admin group picker).
	ListCatalogGroups(ctx context.Context) ([]ListCatalogGroupsRow, error)
	NextCatalogSortOrder(ctx context.Context, group string) (int64, error)
	// Reorder (POST /catalog/{group}/reorder): only sort_order changes, so a concurrent edit of the other columns survives.
	SetCatalogSortOrder(ctx context.Context, arg SetCatalogSortOrderParams) error
	UpdateCatalogItem(ctx context.Context, arg UpdateCatalogItemParams) error
}

var _ Querier = (*Queries)(nil)
