// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"database/sql"
)

const listOwnerAuditPage = `-- name: ListOwnerAuditPage :many
SELECT id, owner_id, actor_id, companion_id, section, action, created_at FROM ` + "`" + `companion_audit_logs` + "`" + `
WHERE owner_id = ?
  AND (? = 0 OR id < ?)
  AND (? = '' OR action = ?)
ORDER BY id DESC
LIMIT ?
`

type ListOwnerAuditPageParams struct {
	OwnerID  uint64
	BeforeID uint64
	Action   string
	Limit    int32
}

// One page of the owner's audit trail, newest first: rows older than before_id (0 = from the newest), optionally
// of one action (empty = every action).
func (q *Queries) ListOwnerAuditPage(ctx context.Context, arg ListOwnerAuditPageParams) ([]CompanionAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerAuditPage,
		arg.OwnerID,
		arg.BeforeID,
		arg.BeforeID,
		arg.Action,
		arg.Action,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanionAuditLog{}
	for rows.Next() {
		var i CompanionAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ActorID,
			&i.CompanionID,
			&i.Section,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentReadAudit = `-- name: RecentReadAudit :one
SELECT id FROM ` + "`" + `companion_audit_logs` + "`" + `
WHERE owner_id = ? AND actor_id = ? AND companion_id = ?
  AND section = ? AND action = 'read' AND created_at >= ?
ORDER BY id DESC
LIMIT 1
`

type RecentReadAuditParams struct {
	OwnerID     uint64
	ActorID     sql.NullInt64
	CompanionID sql.NullInt64
	Section     sql.NullString
	Since       sql.NullTime
}

// The newest `read` row of this actor on this section of the owner's data through this link since `since`: a
// companion read within the coalescing window is not written again (a reload must not flood the owner's trail;
// B-N4-08b, CMP-L1).
func (q *Queries) RecentReadAudit(ctx context.Context, arg RecentReadAuditParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, recentReadAudit,
		arg.OwnerID,
		arg.ActorID,
		arg.CompanionID,
		arg.Section,
		arg.Since,
	)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
