// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"

	"github.com/ritme/backend-go/db"
)

const getUserGender = `-- name: GetUserGender :one

SELECT gender FROM ` + "`" + `user_life_profiles` + "`" + ` WHERE user_id = ? LIMIT 1
`

// Companion account and panel home (bloom B-N4-03). Read-only.
// user_life_profiles.gender of one account (onboarding v2 Gender step; no row / NULL = never asked → a woman's
// account, the legacy default). male = a companion account.
func (q *Queries) GetUserGender(ctx context.Context, userID uint64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserGender, userID)
	var gender sql.NullString
	err := row.Scan(&gender)
	return gender, err
}

const listCompanionArticles = `-- name: ListCompanionArticles :many
SELECT id, slug, title, excerpt, category, read_time_minutes, image_url, image_path
FROM ` + "`" + `articles` + "`" + `
WHERE is_published = 1
  AND (category = 'companion'
    OR (CAST(? AS SIGNED) = 1 AND cycle_phases IS NOT NULL AND JSON_OVERLAPS(cycle_phases, ?)))
ORDER BY (category = 'companion') DESC, sort_order, id
LIMIT 4
`

type ListCompanionArticlesParams struct {
	HasPhases int64
	Phases    string
}

type ListCompanionArticlesRow struct {
	ID              uint64
	Slug            string
	Title           json.RawMessage
	Excerpt         db.NullRawJSON
	Category        sql.NullString
	ReadTimeMinutes sql.NullInt16
	ImageUrl        sql.NullString
	ImagePath       sql.NullString
}

// «برای خواندن» on the companion home: published articles of category `companion`, then articles tagged with the
// partner's phase (has_phases = 0 skips them); untagged general articles are not companion reading.
func (q *Queries) ListCompanionArticles(ctx context.Context, arg ListCompanionArticlesParams) ([]ListCompanionArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanionArticles, arg.HasPhases, arg.Phases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanionArticlesRow{}
	for rows.Next() {
		var i ListCompanionArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Category,
			&i.ReadTimeMinutes,
			&i.ImageUrl,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanionTipContents = `-- name: ListCompanionTipContents :many
SELECT item_key, locale, payload FROM ` + "`" + `message_contents` + "`" + `
WHERE ` + "`" + `group` + "`" + ` = 'companion_tip' AND is_active = 1 AND is_approved = 1 AND locale IN (/*SLICE:locales*/?)
`

type ListCompanionTipContentsRow struct {
	ItemKey string
	Locale  string
	Payload json.RawMessage
}

// The live admin copy of the «امروز چه کار کنی؟» tips (message_contents group companion_tip) in the given locales
// (request locale + default language). Not user data.
func (q *Queries) ListCompanionTipContents(ctx context.Context, locales []string) ([]ListCompanionTipContentsRow, error) {
	query := listCompanionTipContents
	var queryParams []interface{}
	if len(locales) > 0 {
		for _, v := range locales {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:locales*/?", strings.Repeat(",?", len(locales))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:locales*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanionTipContentsRow{}
	for rows.Next() {
		var i ListCompanionTipContentsRow
		if err := rows.Scan(&i.ItemKey, &i.Locale, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
