// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sample.sql

package store

import (
	"context"
)

const sampleHomeTaskTemplate = `-- name: SampleHomeTaskTemplate :one

SELECT id, ` + "`" + `key` + "`" + `, title, description, category, icon, cycle_phase, is_active, sort_order, created_at, updated_at FROM ` + "`" + `task_templates` + "`" + ` WHERE id = ? LIMIT 1
`

// Placeholder so the `home` sqlc package exists and compiles before its domain task lands (T-M2-03).
// Delete this file when the first real query is added to db/queries/home/.
func (q *Queries) SampleHomeTaskTemplate(ctx context.Context, id uint64) (TaskTemplate, error) {
	row := q.db.QueryRowContext(ctx, sampleHomeTaskTemplate, id)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Icon,
		&i.CyclePhase,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
