// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bbt.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const listBBTReadings = `-- name: ListBBTReadings :many

SELECT log_date, basal_body_temperature
FROM ` + "`" + `daily_health_logs` + "`" + `
WHERE user_id = ?
  AND log_date >= ?
  AND log_date <= ?
  AND basal_body_temperature IS NOT NULL
ORDER BY log_date
`

type ListBBTReadingsParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

type ListBBTReadingsRow struct {
	LogDate              civildate.Date
	BasalBodyTemperature sql.NullString
}

// BBT chart (T-M5-02, docs/fertility-ttc/README.md). Every query is scoped by user_id.
// The user's basal-temperature readings from `from` to `to` (inclusive), oldest first.
// The value is decimal(4,2) text ("36.55").
func (q *Queries) ListBBTReadings(ctx context.Context, arg ListBBTReadingsParams) ([]ListBBTReadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBBTReadings, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBBTReadingsRow{}
	for rows.Next() {
		var i ListBBTReadingsRow
		if err := rows.Scan(&i.LogDate, &i.BasalBodyTemperature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
