// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fertility.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const deleteFertilityLog = `-- name: DeleteFertilityLog :exec
DELETE FROM ` + "`" + `fertility_logs` + "`" + ` WHERE user_id = ? AND log_date = ?
`

type DeleteFertilityLogParams struct {
	UserID  uint64
	LogDate civildate.Date
}

func (q *Queries) DeleteFertilityLog(ctx context.Context, arg DeleteFertilityLogParams) error {
	_, err := q.db.ExecContext(ctx, deleteFertilityLog, arg.UserID, arg.LogDate)
	return err
}

const getFertilityLog = `-- name: GetFertilityLog :one
SELECT id, user_id, log_date, lh_test, cervical_mucus, bbt_time, created_at, updated_at FROM ` + "`" + `fertility_logs` + "`" + ` WHERE user_id = ? AND log_date = ?
`

type GetFertilityLogParams struct {
	UserID  uint64
	LogDate civildate.Date
}

func (q *Queries) GetFertilityLog(ctx context.Context, arg GetFertilityLogParams) (FertilityLog, error) {
	row := q.db.QueryRowContext(ctx, getFertilityLog, arg.UserID, arg.LogDate)
	var i FertilityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.LhTest,
		&i.CervicalMucus,
		&i.BbtTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMergedDay = `-- name: GetMergedDay :one

SELECT
  d.basal_body_temperature,
  d.intercourse_type,
  d.ovarian_pain_intensity,
  d.bloating_intensity,
  d.breast_sensitivity_intensity,
  d.spotting,
  d.notes,
  f.lh_test,
  f.cervical_mucus,
  f.bbt_time,
  el.value_code AS entry_lh_test,
  em.value_code AS entry_mucus
FROM (SELECT 1 AS one) AS day
LEFT JOIN ` + "`" + `daily_health_logs` + "`" + ` d ON d.user_id = ? AND d.log_date = ?
LEFT JOIN ` + "`" + `fertility_logs` + "`" + ` f ON f.user_id = ? AND f.log_date = ?
LEFT JOIN ` + "`" + `health_log_entries` + "`" + ` el ON el.user_id = ? AND el.log_date = ?
  AND el.category = 'measurements' AND el.param = 'lh_test' AND el.item = ''
LEFT JOIN ` + "`" + `health_log_entries` + "`" + ` em ON em.user_id = ? AND em.log_date = ?
  AND em.category = 'discharge' AND em.param = 'consistency' AND em.item = ''
`

type GetMergedDayParams struct {
	UserID  uint64
	LogDate civildate.Date
}

type GetMergedDayRow struct {
	BasalBodyTemperature       sql.NullString
	IntercourseType            sql.NullString
	OvarianPainIntensity       sql.NullString
	BloatingIntensity          sql.NullString
	BreastSensitivityIntensity sql.NullString
	Spotting                   sql.NullBool
	Notes                      sql.NullString
	LhTest                     sql.NullString
	CervicalMucus              sql.NullString
	BbtTime                    sql.NullString
	EntryLhTest                sql.NullString
	EntryMucus                 sql.NullString
}

// Fertility day log (T-M5-01, docs/fertility-ttc/README.md). Every query is scoped by user_id.
// The merged day in one statement: the day's daily_health_logs columns the fertility screens use,
// its fertility_logs row and the log sheet's (taxonomy v2) LH test and mucus consistency, any of
// them missing (all NULL). B-N3-14b: the v2 values are not synced into fertility_logs, so the day
// merges both like the TTC analysis does (QUESTIONS #80).
func (q *Queries) GetMergedDay(ctx context.Context, arg GetMergedDayParams) (GetMergedDayRow, error) {
	row := q.db.QueryRowContext(ctx, getMergedDay,
		arg.UserID,
		arg.LogDate,
		arg.UserID,
		arg.LogDate,
		arg.UserID,
		arg.LogDate,
		arg.UserID,
		arg.LogDate,
	)
	var i GetMergedDayRow
	err := row.Scan(
		&i.BasalBodyTemperature,
		&i.IntercourseType,
		&i.OvarianPainIntensity,
		&i.BloatingIntensity,
		&i.BreastSensitivityIntensity,
		&i.Spotting,
		&i.Notes,
		&i.LhTest,
		&i.CervicalMucus,
		&i.BbtTime,
		&i.EntryLhTest,
		&i.EntryMucus,
	)
	return i, err
}

const upsertFertilityLog = `-- name: UpsertFertilityLog :exec
INSERT INTO ` + "`" + `fertility_logs` + "`" + ` (user_id, log_date, lh_test, cervical_mucus, bbt_time, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  lh_test = VALUES(lh_test),
  cervical_mucus = VALUES(cervical_mucus),
  bbt_time = VALUES(bbt_time),
  updated_at = VALUES(updated_at)
`

type UpsertFertilityLogParams struct {
	UserID        uint64
	LogDate       civildate.Date
	LhTest        sql.NullString
	CervicalMucus sql.NullString
	BbtTime       sql.NullString
	Now           sql.NullTime
}

// One row per (user_id, log_date); created_at is kept on update.
func (q *Queries) UpsertFertilityLog(ctx context.Context, arg UpsertFertilityLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertFertilityLog,
		arg.UserID,
		arg.LogDate,
		arg.LhTest,
		arg.CervicalMucus,
		arg.BbtTime,
		arg.Now,
		arg.Now,
	)
	return err
}
