// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const listLHTests = `-- name: ListLHTests :many

SELECT log_date, lh_test
FROM ` + "`" + `fertility_logs` + "`" + `
WHERE user_id = ?
  AND log_date >= ?
  AND log_date <= ?
  AND lh_test IS NOT NULL
ORDER BY log_date
`

type ListLHTestsParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

type ListLHTestsRow struct {
	LogDate civildate.Date
	LhTest  sql.NullString
}

// Fertility insights (T-M5-03, docs/fertility-ttc/README.md). Every query is scoped by user_id.
// The user's LH test results from `from` to `to` (inclusive), oldest first.
func (q *Queries) ListLHTests(ctx context.Context, arg ListLHTestsParams) ([]ListLHTestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLHTests, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLHTestsRow{}
	for rows.Next() {
		var i ListLHTestsRow
		if err := rows.Scan(&i.LogDate, &i.LhTest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
