// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	// AI usage + cost log (B-N6-05, goose 00032): one row per provider call. No content, no PII.
	InsertUsage(ctx context.Context, arg InsertUsageParams) error
	// The global daily cap: the estimated cost of every call since `since` (start of the Tehran day).
	SumCostSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	// Admin aggregates: per Tehran day in [from, to).
	UsageByDay(ctx context.Context, arg UsageByDayParams) ([]UsageByDayRow, error)
	UsageByFeature(ctx context.Context, arg UsageByFeatureParams) ([]UsageByFeatureRow, error)
}

var _ Querier = (*Queries)(nil)
