// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: side_effects.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const getCycleHistoryAfter = `-- name: GetCycleHistoryAfter :one
SELECT id, user_id, period_start_date, period_end_date, cycle_length, bleeding_length, is_confirmed, is_estimated, source, data_quality_flags, created_at, updated_at FROM ` + "`" + `cycle_histories` + "`" + ` WHERE user_id = ? AND period_start_date > ?
ORDER BY period_start_date ASC LIMIT 1
`

type GetCycleHistoryAfterParams struct {
	UserID    uint64
	AfterDate civildate.Date
}

// B-N3-14b (D-55): the first period that starts after a bleeding day (it may start a day or two later).
func (q *Queries) GetCycleHistoryAfter(ctx context.Context, arg GetCycleHistoryAfterParams) (CycleHistory, error) {
	row := q.db.QueryRowContext(ctx, getCycleHistoryAfter, arg.UserID, arg.AfterDate)
	var i CycleHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CycleLength,
		&i.BleedingLength,
		&i.IsConfirmed,
		&i.IsEstimated,
		&i.Source,
		&i.DataQualityFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleHistoryByStart = `-- name: GetCycleHistoryByStart :one
SELECT id, user_id, period_start_date, period_end_date, cycle_length, bleeding_length, is_confirmed, is_estimated, source, data_quality_flags, created_at, updated_at FROM ` + "`" + `cycle_histories` + "`" + ` WHERE user_id = ? AND period_start_date = ? LIMIT 1
`

type GetCycleHistoryByStartParams struct {
	UserID          uint64
	PeriodStartDate civildate.Date
}

func (q *Queries) GetCycleHistoryByStart(ctx context.Context, arg GetCycleHistoryByStartParams) (CycleHistory, error) {
	row := q.db.QueryRowContext(ctx, getCycleHistoryByStart, arg.UserID, arg.PeriodStartDate)
	var i CycleHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CycleLength,
		&i.BleedingLength,
		&i.IsConfirmed,
		&i.IsEstimated,
		&i.Source,
		&i.DataQualityFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleHistoryOnOrBefore = `-- name: GetCycleHistoryOnOrBefore :one
SELECT id, user_id, period_start_date, period_end_date, cycle_length, bleeding_length, is_confirmed, is_estimated, source, data_quality_flags, created_at, updated_at FROM ` + "`" + `cycle_histories` + "`" + ` WHERE user_id = ? AND period_start_date <= ?
ORDER BY period_start_date DESC LIMIT 1
`

type GetCycleHistoryOnOrBeforeParams struct {
	UserID uint64
	OnDate civildate.Date
}

// B-N3-14b (D-55): the period that starts on or before a back-dated bleeding day (it may contain the day).
func (q *Queries) GetCycleHistoryOnOrBefore(ctx context.Context, arg GetCycleHistoryOnOrBeforeParams) (CycleHistory, error) {
	row := q.db.QueryRowContext(ctx, getCycleHistoryOnOrBefore, arg.UserID, arg.OnDate)
	var i CycleHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CycleLength,
		&i.BleedingLength,
		&i.IsConfirmed,
		&i.IsEstimated,
		&i.Source,
		&i.DataQualityFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCycleHistory = `-- name: GetLatestCycleHistory :one
SELECT id, user_id, period_start_date, period_end_date, cycle_length, bleeding_length, is_confirmed, is_estimated, source, data_quality_flags, created_at, updated_at FROM ` + "`" + `cycle_histories` + "`" + ` WHERE user_id = ? ORDER BY period_start_date DESC LIMIT 1
`

// CycleHistory::where('user_id', $u)->orderBy('period_start_date', 'desc')->first().
func (q *Queries) GetLatestCycleHistory(ctx context.Context, userID uint64) (CycleHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestCycleHistory, userID)
	var i CycleHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodStartDate,
		&i.PeriodEndDate,
		&i.CycleLength,
		&i.BleedingLength,
		&i.IsConfirmed,
		&i.IsEstimated,
		&i.Source,
		&i.DataQualityFlags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one

SELECT id, user_id, birthday, weight, height, period_duration, cycle_duration, last_period_start, user_goal, pregnancy_intention, chronic_conditions, subscription_type, calculation_status, calculation_started_at, calculation_completed_at, calculation_version, created_at, updated_at FROM ` + "`" + `user_profiles` + "`" + ` WHERE user_id = ? ORDER BY id LIMIT 1
`

// Side effects of POST /health-logs on user_profiles and cycle_histories
// (CycleHistoryService, UserProfile::markRecalculated).
// $user->profile (hasOne without ordering: the lowest id on MariaDB).
func (q *Queries) GetUserProfile(ctx context.Context, userID uint64) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Birthday,
		&i.Weight,
		&i.Height,
		&i.PeriodDuration,
		&i.CycleDuration,
		&i.LastPeriodStart,
		&i.UserGoal,
		&i.PregnancyIntention,
		&i.ChronicConditions,
		&i.SubscriptionType,
		&i.CalculationStatus,
		&i.CalculationStartedAt,
		&i.CalculationCompletedAt,
		&i.CalculationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCycleHistory = `-- name: InsertCycleHistory :execlastid
INSERT INTO ` + "`" + `cycle_histories` + "`" + ` (user_id, period_start_date, cycle_length, is_confirmed, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?)
`

type InsertCycleHistoryParams struct {
	UserID          uint64
	PeriodStartDate civildate.Date
	CycleLength     sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

// CycleHistory::create([user_id, period_start_date, cycle_length, is_confirmed => false]);
// is_estimated / source / data_quality_flags keep their column defaults.
func (q *Queries) InsertCycleHistory(ctx context.Context, arg InsertCycleHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCycleHistory,
		arg.UserID,
		arg.PeriodStartDate,
		arg.CycleLength,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const markProfileRecalculated = `-- name: MarkProfileRecalculated :exec
UPDATE ` + "`" + `user_profiles` + "`" + `
SET calculation_version = calculation_version + 1,
    calculation_status = 'completed',
    calculation_started_at = ?,
    calculation_completed_at = ?,
    updated_at = ?
WHERE id = ?
`

type MarkProfileRecalculatedParams struct {
	Now sql.NullTime
	ID  uint64
}

// UserProfile::markRecalculated(): increment('calculation_version', 1, [status, started, completed])
// (Eloquent's increment also touches updated_at).
func (q *Queries) MarkProfileRecalculated(ctx context.Context, arg MarkProfileRecalculatedParams) error {
	_, err := q.db.ExecContext(ctx, markProfileRecalculated,
		arg.Now,
		arg.Now,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateCycleHistoryEnd = `-- name: UpdateCycleHistoryEnd :exec
UPDATE ` + "`" + `cycle_histories` + "`" + ` SET period_end_date = ?, bleeding_length = ?, updated_at = ? WHERE id = ?
`

type UpdateCycleHistoryEndParams struct {
	PeriodEndDate  civildate.NullDate
	BleedingLength sql.NullInt32
	UpdatedAt      sql.NullTime
	ID             uint64
}

func (q *Queries) UpdateCycleHistoryEnd(ctx context.Context, arg UpdateCycleHistoryEndParams) error {
	_, err := q.db.ExecContext(ctx, updateCycleHistoryEnd,
		arg.PeriodEndDate,
		arg.BleedingLength,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCycleHistoryStart = `-- name: UpdateCycleHistoryStart :exec
UPDATE ` + "`" + `cycle_histories` + "`" + ` SET period_start_date = ?, bleeding_length = ?, updated_at = ? WHERE id = ?
`

type UpdateCycleHistoryStartParams struct {
	PeriodStartDate civildate.Date
	BleedingLength  sql.NullInt32
	UpdatedAt       sql.NullTime
	ID              uint64
}

// B-N3-14b (D-55): a bleeding day logged right before a period moves its start back.
func (q *Queries) UpdateCycleHistoryStart(ctx context.Context, arg UpdateCycleHistoryStartParams) error {
	_, err := q.db.ExecContext(ctx, updateCycleHistoryStart,
		arg.PeriodStartDate,
		arg.BleedingLength,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProfileLastPeriodStart = `-- name: UpdateProfileLastPeriodStart :exec
UPDATE ` + "`" + `user_profiles` + "`" + ` SET last_period_start = ?, updated_at = ? WHERE id = ?
`

type UpdateProfileLastPeriodStartParams struct {
	LastPeriodStart civildate.NullDate
	UpdatedAt       sql.NullTime
	ID              uint64
}

// CycleHistoryService::updateProfileLMP ($profile->update(['last_period_start' => …]) when dirty).
func (q *Queries) UpdateProfileLastPeriodStart(ctx context.Context, arg UpdateProfileLastPeriodStartParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileLastPeriodStart, arg.LastPeriodStart, arg.UpdatedAt, arg.ID)
	return err
}
