// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const addKick = `-- name: AddKick :execrows
UPDATE ` + "`" + `pregnancy_kick_sessions` + "`" + `
SET tenth_kick_at = IF(tenth_kick_at IS NULL AND kicks + 1 >= ?, ?, tenth_kick_at),
    kicks = kicks + 1, last_kick_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND active_lock = 1 AND kicks < ?
`

type AddKickParams struct {
	Target   uint16
	At       sql.NullTime
	Now      sql.NullTime
	ID       uint64
	UserID   uint64
	MaxKicks uint16
}

// One kick on a running session, atomically. tenth_kick_at is assigned before kicks (MariaDB evaluates SET left to
// right on the updated row), so it sees the count before this kick.
func (q *Queries) AddKick(ctx context.Context, arg AddKickParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addKick,
		arg.Target,
		arg.At,
		arg.At,
		arg.Now,
		arg.ID,
		arg.UserID,
		arg.MaxKicks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteContractionSession = `-- name: DeleteContractionSession :execrows
DELETE FROM ` + "`" + `pregnancy_contraction_sessions` + "`" + ` WHERE id = ? AND user_id = ?
`

type DeleteContractionSessionParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeleteContractionSession(ctx context.Context, arg DeleteContractionSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContractionSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteKickSession = `-- name: DeleteKickSession :execrows
DELETE FROM ` + "`" + `pregnancy_kick_sessions` + "`" + ` WHERE id = ? AND user_id = ?
`

type DeleteKickSessionParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeleteKickSession(ctx context.Context, arg DeleteKickSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKickSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishContractionSession = `-- name: FinishContractionSession :execrows
UPDATE ` + "`" + `pregnancy_contraction_sessions` + "`" + `
SET ended_at = ?, active_lock = NULL, updated_at = ?
WHERE id = ? AND user_id = ? AND active_lock = 1
`

type FinishContractionSessionParams struct {
	EndedAt sql.NullTime
	Now     sql.NullTime
	ID      uint64
	UserID  uint64
}

func (q *Queries) FinishContractionSession(ctx context.Context, arg FinishContractionSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishContractionSession,
		arg.EndedAt,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveContractionSession = `-- name: GetActiveContractionSession :one
SELECT id, user_id, started_at, ended_at, alert_at, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_contraction_sessions` + "`" + ` WHERE user_id = ? AND active_lock = 1 LIMIT 1
`

func (q *Queries) GetActiveContractionSession(ctx context.Context, userID uint64) (PregnancyContractionSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveContractionSession, userID)
	var i PregnancyContractionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.AlertAt,
		&i.ActiveLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveKickSession = `-- name: GetActiveKickSession :one
SELECT id, user_id, started_at, ended_at, kicks, tenth_kick_at, last_kick_at, pregnancy_week, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_kick_sessions` + "`" + ` WHERE user_id = ? AND active_lock = 1 LIMIT 1
`

func (q *Queries) GetActiveKickSession(ctx context.Context, userID uint64) (PregnancyKickSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveKickSession, userID)
	var i PregnancyKickSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Kicks,
		&i.TenthKickAt,
		&i.LastKickAt,
		&i.PregnancyWeek,
		&i.ActiveLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractionSession = `-- name: GetContractionSession :one
SELECT id, user_id, started_at, ended_at, alert_at, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_contraction_sessions` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetContractionSessionParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) GetContractionSession(ctx context.Context, arg GetContractionSessionParams) (PregnancyContractionSession, error) {
	row := q.db.QueryRowContext(ctx, getContractionSession, arg.ID, arg.UserID)
	var i PregnancyContractionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.AlertAt,
		&i.ActiveLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKickSession = `-- name: GetKickSession :one
SELECT id, user_id, started_at, ended_at, kicks, tenth_kick_at, last_kick_at, pregnancy_week, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_kick_sessions` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetKickSessionParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) GetKickSession(ctx context.Context, arg GetKickSessionParams) (PregnancyKickSession, error) {
	row := q.db.QueryRowContext(ctx, getKickSession, arg.ID, arg.UserID)
	var i PregnancyKickSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Kicks,
		&i.TenthKickAt,
		&i.LastKickAt,
		&i.PregnancyWeek,
		&i.ActiveLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContraction = `-- name: InsertContraction :execlastid
INSERT INTO ` + "`" + `pregnancy_contractions` + "`" + ` (session_id, user_id, started_at, active_lock, created_at, updated_at)
VALUES (?, ?, ?, 1, ?, ?)
`

type InsertContractionParams struct {
	SessionID uint64
	UserID    uint64
	StartedAt time.Time
	Now       sql.NullTime
}

func (q *Queries) InsertContraction(ctx context.Context, arg InsertContractionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertContraction,
		arg.SessionID,
		arg.UserID,
		arg.StartedAt,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertContractionSession = `-- name: InsertContractionSession :execlastid
INSERT INTO ` + "`" + `pregnancy_contraction_sessions` + "`" + ` (user_id, started_at, active_lock, created_at, updated_at)
VALUES (?, ?, 1, ?, ?)
`

type InsertContractionSessionParams struct {
	UserID    uint64
	StartedAt time.Time
	Now       sql.NullTime
}

func (q *Queries) InsertContractionSession(ctx context.Context, arg InsertContractionSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertContractionSession,
		arg.UserID,
		arg.StartedAt,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertKickSession = `-- name: InsertKickSession :execlastid

INSERT INTO ` + "`" + `pregnancy_kick_sessions` + "`" + ` (user_id, started_at, kicks, pregnancy_week, active_lock, created_at, updated_at)
VALUES (?, ?, 0, ?, 1, ?, ?)
`

type InsertKickSessionParams struct {
	UserID        uint64
	StartedAt     time.Time
	PregnancyWeek sql.NullInt16
	Now           sql.NullTime
}

// Pregnancy tools (bloom B-N5-03; internal/pregnancy/tools): kick-count sessions and contraction sessions. Every
// query is scoped by user_id. active_lock = 1 marks the running session / contraction; NULL once it ended.
func (q *Queries) InsertKickSession(ctx context.Context, arg InsertKickSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertKickSession,
		arg.UserID,
		arg.StartedAt,
		arg.PregnancyWeek,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listActiveSessionContractions = `-- name: ListActiveSessionContractions :many
SELECT c.id, c.session_id, c.user_id, c.started_at, c.ended_at, c.active_lock, c.created_at, c.updated_at FROM ` + "`" + `pregnancy_contractions` + "`" + ` c
JOIN ` + "`" + `pregnancy_contraction_sessions` + "`" + ` s ON s.id = c.session_id
WHERE c.user_id = ? AND s.user_id = ? AND s.active_lock = 1
ORDER BY c.started_at, c.id
`

type ListActiveSessionContractionsParams struct {
	UserID uint64
}

// The contractions of the user's running session (the alert engine's 5-1-1 facts).
func (q *Queries) ListActiveSessionContractions(ctx context.Context, arg ListActiveSessionContractionsParams) ([]PregnancyContraction, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessionContractions, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyContraction{}
	for rows.Next() {
		var i PregnancyContraction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractionSessions = `-- name: ListContractionSessions :many
SELECT id, user_id, started_at, ended_at, alert_at, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_contraction_sessions` + "`" + `
WHERE user_id = ? AND ended_at IS NOT NULL
ORDER BY started_at DESC, id DESC LIMIT ?
`

type ListContractionSessionsParams struct {
	UserID uint64
	Limit  int32
}

// The user's ended contraction sessions, newest first.
func (q *Queries) ListContractionSessions(ctx context.Context, arg ListContractionSessionsParams) ([]PregnancyContractionSession, error) {
	rows, err := q.db.QueryContext(ctx, listContractionSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyContractionSession{}
	for rows.Next() {
		var i PregnancyContractionSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.AlertAt,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractionsSince = `-- name: ListContractionsSince :many
SELECT id, session_id, user_id, started_at, ended_at, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_contractions` + "`" + `
WHERE user_id = ? AND started_at >= ?
ORDER BY started_at, id
`

type ListContractionsSinceParams struct {
	UserID uint64
	Since  time.Time
}

// The user's contractions started on or after since (grouped by session for the history list).
func (q *Queries) ListContractionsSince(ctx context.Context, arg ListContractionsSinceParams) ([]PregnancyContraction, error) {
	rows, err := q.db.QueryContext(ctx, listContractionsSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyContraction{}
	for rows.Next() {
		var i PregnancyContraction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKickSessions = `-- name: ListKickSessions :many
SELECT id, user_id, started_at, ended_at, kicks, tenth_kick_at, last_kick_at, pregnancy_week, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_kick_sessions` + "`" + `
WHERE user_id = ? AND ended_at IS NOT NULL
ORDER BY started_at DESC, id DESC LIMIT ?
`

type ListKickSessionsParams struct {
	UserID uint64
	Limit  int32
}

// The user's ended kick sessions, newest first.
func (q *Queries) ListKickSessions(ctx context.Context, arg ListKickSessionsParams) ([]PregnancyKickSession, error) {
	rows, err := q.db.QueryContext(ctx, listKickSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyKickSession{}
	for rows.Next() {
		var i PregnancyKickSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Kicks,
			&i.TenthKickAt,
			&i.LastKickAt,
			&i.PregnancyWeek,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKickSessionsBetween = `-- name: ListKickSessionsBetween :many
SELECT id, user_id, started_at, ended_at, kicks, tenth_kick_at, last_kick_at, pregnancy_week, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_kick_sessions` + "`" + `
WHERE user_id = ? AND ended_at IS NOT NULL
  AND started_at >= ? AND started_at < ?
ORDER BY started_at, id
`

type ListKickSessionsBetweenParams struct {
	UserID   uint64
	DateFrom time.Time
	DateTo   time.Time
}

// Ended sessions started in [date_from, date_to) (the day's kick total written to pregnancy_fetal_movements).
func (q *Queries) ListKickSessionsBetween(ctx context.Context, arg ListKickSessionsBetweenParams) ([]PregnancyKickSession, error) {
	rows, err := q.db.QueryContext(ctx, listKickSessionsBetween, arg.UserID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyKickSession{}
	for rows.Next() {
		var i PregnancyKickSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Kicks,
			&i.TenthKickAt,
			&i.LastKickAt,
			&i.PregnancyWeek,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionContractions = `-- name: ListSessionContractions :many
SELECT id, session_id, user_id, started_at, ended_at, active_lock, created_at, updated_at FROM ` + "`" + `pregnancy_contractions` + "`" + `
WHERE session_id = ? AND user_id = ?
ORDER BY started_at, id
`

type ListSessionContractionsParams struct {
	SessionID uint64
	UserID    uint64
}

func (q *Queries) ListSessionContractions(ctx context.Context, arg ListSessionContractionsParams) ([]PregnancyContraction, error) {
	rows, err := q.db.QueryContext(ctx, listSessionContractions, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyContraction{}
	for rows.Next() {
		var i PregnancyContraction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.ActiveLock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFetalMovementFelt = `-- name: MarkFetalMovementFelt :exec
UPDATE ` + "`" + `pregnancy_profiles` + "`" + `
SET fetal_movement_felt = 1, first_fetal_movement_date = COALESCE(first_fetal_movement_date, ?),
    updated_at = ?
WHERE user_id = ? AND pregnancy_mode = 1 AND fetal_movement_felt = 0
`

type MarkFetalMovementFeltParams struct {
	Day    civildate.NullDate
	Now    sql.NullTime
	UserID uint64
}

// The first counted kick marks the profile's first felt movement (like POST /pregnancy/fetal-movement with felt).
func (q *Queries) MarkFetalMovementFelt(ctx context.Context, arg MarkFetalMovementFeltParams) error {
	_, err := q.db.ExecContext(ctx, markFetalMovementFelt, arg.Day, arg.Now, arg.UserID)
	return err
}

const setContractionAlertAt = `-- name: SetContractionAlertAt :exec
UPDATE ` + "`" + `pregnancy_contraction_sessions` + "`" + `
SET alert_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND alert_at IS NULL
`

type SetContractionAlertAtParams struct {
	AlertAt sql.NullTime
	Now     sql.NullTime
	ID      uint64
	UserID  uint64
}

func (q *Queries) SetContractionAlertAt(ctx context.Context, arg SetContractionAlertAtParams) error {
	_, err := q.db.ExecContext(ctx, setContractionAlertAt,
		arg.AlertAt,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const stopContraction = `-- name: StopContraction :execrows
UPDATE ` + "`" + `pregnancy_contractions` + "`" + `
SET ended_at = ?, active_lock = NULL, updated_at = ?
WHERE session_id = ? AND user_id = ? AND active_lock = 1
`

type StopContractionParams struct {
	EndedAt   sql.NullTime
	Now       sql.NullTime
	SessionID uint64
	UserID    uint64
}

func (q *Queries) StopContraction(ctx context.Context, arg StopContractionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopContraction,
		arg.EndedAt,
		arg.Now,
		arg.SessionID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stopKickSession = `-- name: StopKickSession :execrows
UPDATE ` + "`" + `pregnancy_kick_sessions` + "`" + `
SET ended_at = ?, active_lock = NULL, updated_at = ?
WHERE id = ? AND user_id = ? AND active_lock = 1
`

type StopKickSessionParams struct {
	EndedAt sql.NullTime
	Now     sql.NullTime
	ID      uint64
	UserID  uint64
}

func (q *Queries) StopKickSession(ctx context.Context, arg StopKickSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopKickSession,
		arg.EndedAt,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const undoKick = `-- name: UndoKick :execrows
UPDATE ` + "`" + `pregnancy_kick_sessions` + "`" + `
SET tenth_kick_at = IF(kicks - 1 < ?, NULL, tenth_kick_at), kicks = kicks - 1, updated_at = ?
WHERE id = ? AND user_id = ? AND active_lock = 1 AND kicks > 0
`

type UndoKickParams struct {
	Target uint16
	Now    sql.NullTime
	ID     uint64
	UserID uint64
}

// Takes the last kick back (the time to the target is cleared when the count drops under it).
func (q *Queries) UndoKick(ctx context.Context, arg UndoKickParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, undoKick,
		arg.Target,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
