// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v2_alerts.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const ackV2Alert = `-- name: AckV2Alert :exec
UPDATE ` + "`" + `pregnancy_alerts` + "`" + `
SET is_read = 1, read_at = COALESCE(read_at, ?), is_dismissed = 1,
    dismissed_at = COALESCE(dismissed_at, ?), updated_at = ?
WHERE user_id = ? AND id = ?
`

type AckV2AlertParams struct {
	Now    sql.NullTime
	UserID uint64
	ID     uint64
}

// Action ack («دیدم، ممنون»): read + dismissed (hidden from the v1 active list too).
func (q *Queries) AckV2Alert(ctx context.Context, arg AckV2AlertParams) error {
	_, err := q.db.ExecContext(ctx, ackV2Alert,
		arg.Now,
		arg.Now,
		arg.Now,
		arg.UserID,
		arg.ID,
	)
	return err
}

const countV2AlertDedupe = `-- name: CountV2AlertDedupe :one
SELECT COUNT(*) FROM ` + "`" + `pregnancy_alerts` + "`" + `
WHERE user_id = ? AND alert_type = ? AND created_at >= ?
  AND JSON_UNQUOTE(JSON_EXTRACT(trigger_symptoms, '$.dedupe')) = CAST(? AS CHAR)
`

type CountV2AlertDedupeParams struct {
	UserID    uint64
	AlertType string
	Since     sql.NullTime
	Dedupe    interface{}
}

// Dedupe: how many alerts of one rule with the same dedupe key exist since `since`.
func (q *Queries) CountV2AlertDedupe(ctx context.Context, arg CountV2AlertDedupeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countV2AlertDedupe,
		arg.UserID,
		arg.AlertType,
		arg.Since,
		arg.Dedupe,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getV2Alert = `-- name: GetV2Alert :one
SELECT id, user_id, alert_level, alert_type, title, message, pregnancy_week, trigger_symptoms, medical_history_flags, is_read, is_dismissed, read_at, dismissed_at, recommended_actions, created_at, updated_at FROM ` + "`" + `pregnancy_alerts` + "`" + `
WHERE user_id = ? AND id = ? AND alert_type LIKE 'v2:%' LIMIT 1
`

type GetV2AlertParams struct {
	UserID uint64
	ID     uint64
}

func (q *Queries) GetV2Alert(ctx context.Context, arg GetV2AlertParams) (PregnancyAlert, error) {
	row := q.db.QueryRowContext(ctx, getV2Alert, arg.UserID, arg.ID)
	var i PregnancyAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AlertLevel,
		&i.AlertType,
		&i.Title,
		&i.Message,
		&i.PregnancyWeek,
		&i.TriggerSymptoms,
		&i.MedicalHistoryFlags,
		&i.IsRead,
		&i.IsDismissed,
		&i.ReadAt,
		&i.DismissedAt,
		&i.RecommendedActions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveMessageGroup = `-- name: ListLiveMessageGroup :many

SELECT item_key, locale, payload FROM ` + "`" + `message_contents` + "`" + `
WHERE ` + "`" + `group` + "`" + ` = ? AND is_active = 1 AND is_approved = 1
ORDER BY item_key, locale
`

type ListLiveMessageGroupRow struct {
	ItemKey string
	Locale  string
	Payload json.RawMessage
}

// Pregnancy v2 alert rules (T-M7-04, internal/messages/pregnancyalerts). v2 rows live in pregnancy_alerts
// with alert_type = 'v2:<rule_key>' and their v2 metadata (level4, dedupe key, placeholder values) in
// trigger_symptoms. Every user-scoped query filters by user_id.
// Every live (active + approved) row of one message_contents group, all locales (rules + legend).
func (q *Queries) ListLiveMessageGroup(ctx context.Context, messageGroup string) ([]ListLiveMessageGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveMessageGroup, messageGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveMessageGroupRow{}
	for rows.Next() {
		var i ListLiveMessageGroupRow
		if err := rows.Scan(&i.ItemKey, &i.Locale, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listV2AlertsSince = `-- name: ListV2AlertsSince :many
SELECT id, user_id, alert_level, alert_type, title, message, pregnancy_week, trigger_symptoms, medical_history_flags, is_read, is_dismissed, read_at, dismissed_at, recommended_actions, created_at, updated_at FROM ` + "`" + `pregnancy_alerts` + "`" + `
WHERE user_id = ? AND alert_type LIKE 'v2:%' AND created_at >= ?
ORDER BY created_at DESC, id DESC
`

type ListV2AlertsSinceParams struct {
	UserID uint64
	Since  sql.NullTime
}

// The user's v2 alerts created at or after `since`, newest first (dismissed = acked ones included).
func (q *Queries) ListV2AlertsSince(ctx context.Context, arg ListV2AlertsSinceParams) ([]PregnancyAlert, error) {
	rows, err := q.db.QueryContext(ctx, listV2AlertsSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyAlert{}
	for rows.Next() {
		var i PregnancyAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AlertLevel,
			&i.AlertType,
			&i.Title,
			&i.Message,
			&i.PregnancyWeek,
			&i.TriggerSymptoms,
			&i.MedicalHistoryFlags,
			&i.IsRead,
			&i.IsDismissed,
			&i.ReadAt,
			&i.DismissedAt,
			&i.RecommendedActions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listV2WeeklyLogsSince = `-- name: ListV2WeeklyLogsSince :many
SELECT id, user_id, log_date, pregnancy_week, weight, swelling_locations, has_swelling, has_shortness_of_breath, has_blood_pressure_device, systolic_pressure, diastolic_pressure, fasting_blood_sugar, post_meal_blood_sugar, overall_mood, has_anxiety, anxiety_severity, has_mood_swings, mood_swings_severity, has_depression_feelings, depression_severity, notes, created_at, updated_at FROM ` + "`" + `pregnancy_weekly_logs` + "`" + `
WHERE user_id = ? AND log_date >= ?
ORDER BY log_date, pregnancy_week
`

type ListV2WeeklyLogsSinceParams struct {
	UserID   uint64
	DateFrom civildate.Date
}

// Weekly logs (weight / BP / sugar) logged on or after `date_from`.
func (q *Queries) ListV2WeeklyLogsSince(ctx context.Context, arg ListV2WeeklyLogsSinceParams) ([]PregnancyWeeklyLog, error) {
	rows, err := q.db.QueryContext(ctx, listV2WeeklyLogsSince, arg.UserID, arg.DateFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyWeeklyLog{}
	for rows.Next() {
		var i PregnancyWeeklyLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.PregnancyWeek,
			&i.Weight,
			&i.SwellingLocations,
			&i.HasSwelling,
			&i.HasShortnessOfBreath,
			&i.HasBloodPressureDevice,
			&i.SystolicPressure,
			&i.DiastolicPressure,
			&i.FastingBloodSugar,
			&i.PostMealBloodSugar,
			&i.OverallMood,
			&i.HasAnxiety,
			&i.AnxietySeverity,
			&i.HasMoodSwings,
			&i.MoodSwingsSeverity,
			&i.HasDepressionFeelings,
			&i.DepressionSeverity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markV2AlertRead = `-- name: MarkV2AlertRead :exec
UPDATE ` + "`" + `pregnancy_alerts` + "`" + ` SET is_read = 1, read_at = COALESCE(read_at, ?), updated_at = ?
WHERE user_id = ? AND id = ?
`

type MarkV2AlertReadParams struct {
	Now    sql.NullTime
	UserID uint64
	ID     uint64
}

func (q *Queries) MarkV2AlertRead(ctx context.Context, arg MarkV2AlertReadParams) error {
	_, err := q.db.ExecContext(ctx, markV2AlertRead,
		arg.Now,
		arg.Now,
		arg.UserID,
		arg.ID,
	)
	return err
}
