// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v2_daily_extras.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const deleteDailyExtras = `-- name: DeleteDailyExtras :exec
DELETE FROM ` + "`" + `pregnancy_daily_extras` + "`" + ` WHERE user_id = ? AND log_date = ?
`

type DeleteDailyExtrasParams struct {
	UserID  uint64
	LogDate civildate.Date
}

func (q *Queries) DeleteDailyExtras(ctx context.Context, arg DeleteDailyExtrasParams) error {
	_, err := q.db.ExecContext(ctx, deleteDailyExtras, arg.UserID, arg.LogDate)
	return err
}

const getDailyExtras = `-- name: GetDailyExtras :one

SELECT id, user_id, log_date, mood, water_glasses, heartburn_severity, constipation_severity, visit_note, created_at, updated_at FROM ` + "`" + `pregnancy_daily_extras` + "`" + ` WHERE user_id = ? AND log_date = ? LIMIT 1
`

type GetDailyExtrasParams struct {
	UserID  uint64
	LogDate civildate.Date
}

// Pregnancy v2 per-day extras (table pregnancy_daily_extras, T-M7-01): the day-log fields
// pregnancy_symptom_logs lacks (mood, water, heartburn, constipation, visit note). Every query is
// scoped by user_id. Unique (user_id, log_date).
func (q *Queries) GetDailyExtras(ctx context.Context, arg GetDailyExtrasParams) (PregnancyDailyExtra, error) {
	row := q.db.QueryRowContext(ctx, getDailyExtras, arg.UserID, arg.LogDate)
	var i PregnancyDailyExtra
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.Mood,
		&i.WaterGlasses,
		&i.HeartburnSeverity,
		&i.ConstipationSeverity,
		&i.VisitNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyExtrasRange = `-- name: ListDailyExtrasRange :many
SELECT id, user_id, log_date, mood, water_glasses, heartburn_severity, constipation_severity, visit_note, created_at, updated_at FROM ` + "`" + `pregnancy_daily_extras` + "`" + `
WHERE user_id = ? AND log_date >= ? AND log_date <= ?
ORDER BY log_date
`

type ListDailyExtrasRangeParams struct {
	UserID   uint64
	DateFrom civildate.Date
	DateTo   civildate.Date
}

// from..to inclusive (doctor report, alert windows).
func (q *Queries) ListDailyExtrasRange(ctx context.Context, arg ListDailyExtrasRangeParams) ([]PregnancyDailyExtra, error) {
	rows, err := q.db.QueryContext(ctx, listDailyExtrasRange, arg.UserID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyDailyExtra{}
	for rows.Next() {
		var i PregnancyDailyExtra
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.Mood,
			&i.WaterGlasses,
			&i.HeartburnSeverity,
			&i.ConstipationSeverity,
			&i.VisitNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDailyVisitNote = `-- name: SetDailyVisitNote :exec
INSERT INTO ` + "`" + `pregnancy_daily_extras` + "`" + ` (user_id, log_date, visit_note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE visit_note = VALUES(visit_note), updated_at = VALUES(updated_at)
`

type SetDailyVisitNoteParams struct {
	UserID    uint64
	LogDate   civildate.Date
	VisitNote sql.NullString
	Now       sql.NullTime
}

// Alert action add_to_visit_note (T-M7-04): creates the day's row when missing, keeps the other fields.
func (q *Queries) SetDailyVisitNote(ctx context.Context, arg SetDailyVisitNoteParams) error {
	_, err := q.db.ExecContext(ctx, setDailyVisitNote,
		arg.UserID,
		arg.LogDate,
		arg.VisitNote,
		arg.Now,
		arg.Now,
	)
	return err
}

const upsertDailyExtras = `-- name: UpsertDailyExtras :exec
INSERT INTO ` + "`" + `pregnancy_daily_extras` + "`" + ` (
  user_id, log_date, mood, water_glasses, heartburn_severity, constipation_severity, visit_note, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?,
  ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
  mood = VALUES(mood),
  water_glasses = VALUES(water_glasses),
  heartburn_severity = VALUES(heartburn_severity),
  constipation_severity = VALUES(constipation_severity),
  visit_note = VALUES(visit_note),
  updated_at = VALUES(updated_at)
`

type UpsertDailyExtrasParams struct {
	UserID               uint64
	LogDate              civildate.Date
	Mood                 sql.NullInt16
	WaterGlasses         sql.NullInt16
	HeartburnSeverity    sql.NullString
	ConstipationSeverity sql.NullString
	VisitNote            sql.NullString
	Now                  sql.NullTime
}

// One row per (user_id, log_date); created_at is kept on update. Idempotent (offline outbox resends).
func (q *Queries) UpsertDailyExtras(ctx context.Context, arg UpsertDailyExtrasParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyExtras,
		arg.UserID,
		arg.LogDate,
		arg.Mood,
		arg.WaterGlasses,
		arg.HeartburnSeverity,
		arg.ConstipationSeverity,
		arg.VisitNote,
		arg.Now,
		arg.Now,
	)
	return err
}
