// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v2_read.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"

	"github.com/ritme/backend-go/db"
)

const getV2TodayExtras = `-- name: GetV2TodayExtras :one

SELECT
  (SELECT COUNT(*) FROM ` + "`" + `pregnancy_alerts` + "`" + ` pa
    WHERE pa.user_id = ? AND pa.is_dismissed = 0 AND pa.is_read = 0
      AND pa.alert_type LIKE 'v2:%' AND pa.created_at >= ?) AS unread_alerts,
  a.id AS appointment_id,
  a.title AS appointment_title,
  a.scheduled_at AS appointment_at,
  a.meta AS appointment_meta,
  ci.` + "`" + `key` + "`" + ` AS care_item_key,
  ci.title AS care_item_title,
  ci.week_from AS care_item_week_from,
  ci.week_to AS care_item_week_to
FROM ` + "`" + `users` + "`" + ` u
LEFT JOIN ` + "`" + `reminders` + "`" + ` a ON a.id = (
  SELECT r.id FROM ` + "`" + `reminders` + "`" + ` r
  WHERE r.user_id = ? AND r.` + "`" + `type` + "`" + ` = 'appointment'
    AND r.scheduled_at >= ?
    AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(r.meta, '$.status')), 'scheduled') <> 'cancelled'
  ORDER BY r.scheduled_at, r.id
  LIMIT 1
)
LEFT JOIN ` + "`" + `pregnancy_care_items` + "`" + ` ci ON ci.id = (
  SELECT c.id FROM ` + "`" + `pregnancy_care_items` + "`" + ` c
  WHERE c.is_active = 1 AND c.week_to >= ?
  ORDER BY c.week_from, c.sort_order, c.id
  LIMIT 1
)
WHERE u.id = ?
`

type GetV2TodayExtrasParams struct {
	UserID      uint64
	AlertsSince sql.NullTime
	Now         sql.NullTime
	CurrentWeek uint8
}

type GetV2TodayExtrasRow struct {
	UnreadAlerts     int64
	AppointmentID    sql.NullInt64
	AppointmentTitle sql.NullString
	AppointmentAt    sql.NullTime
	AppointmentMeta  db.NullRawJSON
	CareItemKey      sql.NullString
	CareItemTitle    db.NullRawJSON
	CareItemWeekFrom sql.NullInt16
	CareItemWeekTo   sql.NullInt16
}

// Pregnancy v2 read model (T-M7-02, internal/pregnancy/v2): the Today screen's extras and the message
// rows it reads. Every user-scoped query filters by user_id.
// One row for the Today screen: the unread (not dismissed) alert count, the next upcoming non-cancelled
// M3 appointment at or after `now`, and the first active care-plan item whose week window has not ended
// (the next-visit fallback). The users row only anchors the single result row.
// The count covers exactly what GET /pregnancy/v2/alerts lists (ListV2AlertsSince): v2 rows created at
// or after `alerts_since`. Legacy v1 rows (e.g. `symptom_based`) are never shown there, so they must
// not inflate the badge either (QA 2026-09-29-c L1).
func (q *Queries) GetV2TodayExtras(ctx context.Context, arg GetV2TodayExtrasParams) (GetV2TodayExtrasRow, error) {
	row := q.db.QueryRowContext(ctx, getV2TodayExtras,
		arg.UserID,
		arg.AlertsSince,
		arg.UserID,
		arg.Now,
		arg.CurrentWeek,
		arg.UserID,
	)
	var i GetV2TodayExtrasRow
	err := row.Scan(
		&i.UnreadAlerts,
		&i.AppointmentID,
		&i.AppointmentTitle,
		&i.AppointmentAt,
		&i.AppointmentMeta,
		&i.CareItemKey,
		&i.CareItemTitle,
		&i.CareItemWeekFrom,
		&i.CareItemWeekTo,
	)
	return i, err
}

const listV2MessageGroupPayloads = `-- name: ListV2MessageGroupPayloads :many
SELECT item_key, locale, payload FROM ` + "`" + `message_contents` + "`" + `
WHERE ` + "`" + `group` + "`" + ` = ?
  AND is_active = 1 AND is_approved = 1 AND locale IN (/*SLICE:locales*/?)
`

type ListV2MessageGroupPayloadsParams struct {
	MessageGroup string
	Locales      []string
}

type ListV2MessageGroupPayloadsRow struct {
	ItemKey string
	Locale  string
	Payload json.RawMessage
}

// Every live message_contents row of one group in the given locales (request locale + default language)
// — the Setup screen's copy (GET /pregnancy/v2/setup-copy, T-M7-20).
func (q *Queries) ListV2MessageGroupPayloads(ctx context.Context, arg ListV2MessageGroupPayloadsParams) ([]ListV2MessageGroupPayloadsRow, error) {
	query := listV2MessageGroupPayloads
	var queryParams []interface{}
	queryParams = append(queryParams, arg.MessageGroup)
	if len(arg.Locales) > 0 {
		for _, v := range arg.Locales {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:locales*/?", strings.Repeat(",?", len(arg.Locales))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:locales*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListV2MessageGroupPayloadsRow{}
	for rows.Next() {
		var i ListV2MessageGroupPayloadsRow
		if err := rows.Scan(&i.ItemKey, &i.Locale, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listV2MessagePayloads = `-- name: ListV2MessagePayloads :many
SELECT locale, payload FROM ` + "`" + `message_contents` + "`" + `
WHERE ` + "`" + `group` + "`" + ` = ? AND item_key = ?
  AND is_active = 1 AND is_approved = 1 AND locale IN (/*SLICE:locales*/?)
`

type ListV2MessagePayloadsParams struct {
	MessageGroup string
	ItemKey      string
	Locales      []string
}

type ListV2MessagePayloadsRow struct {
	Locale  string
	Payload json.RawMessage
}

// The live message_contents rows of one group/item in the given locales (request locale + default
// language, for the fallback) — the week tip and the setup templates.
func (q *Queries) ListV2MessagePayloads(ctx context.Context, arg ListV2MessagePayloadsParams) ([]ListV2MessagePayloadsRow, error) {
	query := listV2MessagePayloads
	var queryParams []interface{}
	queryParams = append(queryParams, arg.MessageGroup)
	queryParams = append(queryParams, arg.ItemKey)
	if len(arg.Locales) > 0 {
		for _, v := range arg.Locales {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:locales*/?", strings.Repeat(",?", len(arg.Locales))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:locales*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListV2MessagePayloadsRow{}
	for rows.Next() {
		var i ListV2MessagePayloadsRow
		if err := rows.Scan(&i.Locale, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
