// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly_logs.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const getWeeklyLog = `-- name: GetWeeklyLog :one
SELECT id, user_id, log_date, pregnancy_week, weight, swelling_locations, has_swelling, has_shortness_of_breath, has_blood_pressure_device, systolic_pressure, diastolic_pressure, fasting_blood_sugar, post_meal_blood_sugar, overall_mood, has_anxiety, anxiety_severity, has_mood_swings, mood_swings_severity, has_depression_feelings, depression_severity, notes, created_at, updated_at FROM ` + "`" + `pregnancy_weekly_logs` + "`" + ` WHERE user_id = ? AND pregnancy_week = ? LIMIT 1
`

type GetWeeklyLogParams struct {
	UserID        uint64
	PregnancyWeek int32
}

func (q *Queries) GetWeeklyLog(ctx context.Context, arg GetWeeklyLogParams) (PregnancyWeeklyLog, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyLog, arg.UserID, arg.PregnancyWeek)
	var i PregnancyWeeklyLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.PregnancyWeek,
		&i.Weight,
		&i.SwellingLocations,
		&i.HasSwelling,
		&i.HasShortnessOfBreath,
		&i.HasBloodPressureDevice,
		&i.SystolicPressure,
		&i.DiastolicPressure,
		&i.FastingBloodSugar,
		&i.PostMealBloodSugar,
		&i.OverallMood,
		&i.HasAnxiety,
		&i.AnxietySeverity,
		&i.HasMoodSwings,
		&i.MoodSwingsSeverity,
		&i.HasDepressionFeelings,
		&i.DepressionSeverity,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWeeklyLog = `-- name: InsertWeeklyLog :execlastid
INSERT INTO ` + "`" + `pregnancy_weekly_logs` + "`" + ` (
  user_id, log_date, pregnancy_week, weight, swelling_locations, has_swelling, has_shortness_of_breath,
  has_blood_pressure_device, systolic_pressure, diastolic_pressure, fasting_blood_sugar, post_meal_blood_sugar,
  overall_mood, has_anxiety, anxiety_severity, has_mood_swings, mood_swings_severity,
  has_depression_feelings, depression_severity, notes, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWeeklyLogParams struct {
	UserID                 uint64
	LogDate                civildate.Date
	PregnancyWeek          int32
	Weight                 sql.NullString
	SwellingLocations      db.NullRawJSON
	HasSwelling            sql.NullBool
	HasShortnessOfBreath   sql.NullBool
	HasBloodPressureDevice bool
	SystolicPressure       sql.NullInt32
	DiastolicPressure      sql.NullInt32
	FastingBloodSugar      sql.NullString
	PostMealBloodSugar     sql.NullString
	OverallMood            sql.NullString
	HasAnxiety             sql.NullBool
	AnxietySeverity        sql.NullString
	HasMoodSwings          sql.NullBool
	MoodSwingsSeverity     sql.NullString
	HasDepressionFeelings  sql.NullBool
	DepressionSeverity     sql.NullString
	Notes                  sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

func (q *Queries) InsertWeeklyLog(ctx context.Context, arg InsertWeeklyLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertWeeklyLog,
		arg.UserID,
		arg.LogDate,
		arg.PregnancyWeek,
		arg.Weight,
		arg.SwellingLocations,
		arg.HasSwelling,
		arg.HasShortnessOfBreath,
		arg.HasBloodPressureDevice,
		arg.SystolicPressure,
		arg.DiastolicPressure,
		arg.FastingBloodSugar,
		arg.PostMealBloodSugar,
		arg.OverallMood,
		arg.HasAnxiety,
		arg.AnxietySeverity,
		arg.HasMoodSwings,
		arg.MoodSwingsSeverity,
		arg.HasDepressionFeelings,
		arg.DepressionSeverity,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listWeeklyLogs = `-- name: ListWeeklyLogs :many

SELECT id, user_id, log_date, pregnancy_week, weight, swelling_locations, has_swelling, has_shortness_of_breath, has_blood_pressure_device, systolic_pressure, diastolic_pressure, fasting_blood_sugar, post_meal_blood_sugar, overall_mood, has_anxiety, anxiety_severity, has_mood_swings, mood_swings_severity, has_depression_feelings, depression_severity, notes, created_at, updated_at FROM ` + "`" + `pregnancy_weekly_logs` + "`" + ` WHERE user_id = ? ORDER BY pregnancy_week DESC
`

// PregnancyWeeklyLog (App\Models\PregnancyWeeklyLog). Unique (user_id, pregnancy_week).
func (q *Queries) ListWeeklyLogs(ctx context.Context, userID uint64) ([]PregnancyWeeklyLog, error) {
	rows, err := q.db.QueryContext(ctx, listWeeklyLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PregnancyWeeklyLog{}
	for rows.Next() {
		var i PregnancyWeeklyLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.PregnancyWeek,
			&i.Weight,
			&i.SwellingLocations,
			&i.HasSwelling,
			&i.HasShortnessOfBreath,
			&i.HasBloodPressureDevice,
			&i.SystolicPressure,
			&i.DiastolicPressure,
			&i.FastingBloodSugar,
			&i.PostMealBloodSugar,
			&i.OverallMood,
			&i.HasAnxiety,
			&i.AnxietySeverity,
			&i.HasMoodSwings,
			&i.MoodSwingsSeverity,
			&i.HasDepressionFeelings,
			&i.DepressionSeverity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeeklyLog = `-- name: UpdateWeeklyLog :exec
UPDATE ` + "`" + `pregnancy_weekly_logs` + "`" + ` SET
  log_date = ?, weight = ?, swelling_locations = ?, has_swelling = ?, has_shortness_of_breath = ?,
  has_blood_pressure_device = ?, systolic_pressure = ?, diastolic_pressure = ?, fasting_blood_sugar = ?,
  post_meal_blood_sugar = ?, overall_mood = ?, has_anxiety = ?, anxiety_severity = ?, has_mood_swings = ?,
  mood_swings_severity = ?, has_depression_feelings = ?, depression_severity = ?, notes = ?, updated_at = ?
WHERE id = ?
`

type UpdateWeeklyLogParams struct {
	LogDate                civildate.Date
	Weight                 sql.NullString
	SwellingLocations      db.NullRawJSON
	HasSwelling            sql.NullBool
	HasShortnessOfBreath   sql.NullBool
	HasBloodPressureDevice bool
	SystolicPressure       sql.NullInt32
	DiastolicPressure      sql.NullInt32
	FastingBloodSugar      sql.NullString
	PostMealBloodSugar     sql.NullString
	OverallMood            sql.NullString
	HasAnxiety             sql.NullBool
	AnxietySeverity        sql.NullString
	HasMoodSwings          sql.NullBool
	MoodSwingsSeverity     sql.NullString
	HasDepressionFeelings  sql.NullBool
	DepressionSeverity     sql.NullString
	Notes                  sql.NullString
	UpdatedAt              sql.NullTime
	ID                     uint64
}

func (q *Queries) UpdateWeeklyLog(ctx context.Context, arg UpdateWeeklyLogParams) error {
	_, err := q.db.ExecContext(ctx, updateWeeklyLog,
		arg.LogDate,
		arg.Weight,
		arg.SwellingLocations,
		arg.HasSwelling,
		arg.HasShortnessOfBreath,
		arg.HasBloodPressureDevice,
		arg.SystolicPressure,
		arg.DiastolicPressure,
		arg.FastingBloodSugar,
		arg.PostMealBloodSugar,
		arg.OverallMood,
		arg.HasAnxiety,
		arg.AnxietySeverity,
		arg.HasMoodSwings,
		arg.MoodSwingsSeverity,
		arg.HasDepressionFeelings,
		arg.DepressionSeverity,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
