// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menopause.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const createHotFlash = `-- name: CreateHotFlash :execlastid

INSERT INTO ` + "`" + `hot_flashes` + "`" + ` (user_id, started_at, duration_s, severity, night, sweat, triggers, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?, ?, ?)
`

type CreateHotFlashParams struct {
	UserID    uint64
	StartedAt time.Time
	DurationS sql.NullInt32
	Severity  sql.NullInt16
	Night     bool
	Sweat     bool
	Triggers  db.NullRawJSON
	Now       sql.NullTime
}

// Menopause (CB-MENO-01, goose 00022): the base reads/writes of the menopause tables for the API tasks
// (CB-MENO-02 hot flashes + score, CB-MENO-03 treatment). Health data: every statement is scoped by user_id in the
// statement itself. Profile = user_life_profiles.menopause_* (B-N2-01); daily symptoms = health_log_entries (B-N3-01).
func (q *Queries) CreateHotFlash(ctx context.Context, arg CreateHotFlashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createHotFlash,
		arg.UserID,
		arg.StartedAt,
		arg.DurationS,
		arg.Severity,
		arg.Night,
		arg.Sweat,
		arg.Triggers,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getRunningHotFlash = `-- name: GetRunningHotFlash :one
SELECT id, user_id, started_at, duration_s, severity, night, sweat, triggers, created_at, updated_at FROM ` + "`" + `hot_flashes` + "`" + `
WHERE user_id = ? AND duration_s IS NULL
ORDER BY started_at DESC, id DESC
LIMIT 1
`

// The timer still running (duration_s NULL), newest first.
func (q *Queries) GetRunningHotFlash(ctx context.Context, userID uint64) (HotFlash, error) {
	row := q.db.QueryRowContext(ctx, getRunningHotFlash, userID)
	var i HotFlash
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.DurationS,
		&i.Severity,
		&i.Night,
		&i.Sweat,
		&i.Triggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHotFlashesInRange = `-- name: ListHotFlashesInRange :many
SELECT id, user_id, started_at, duration_s, severity, night, sweat, triggers, created_at, updated_at FROM ` + "`" + `hot_flashes` + "`" + `
WHERE user_id = ? AND started_at >= ? AND started_at < ?
ORDER BY started_at DESC, id DESC
`

type ListHotFlashesInRangeParams struct {
	UserID uint64
	FromAt time.Time
	ToAt   time.Time
}

// started_at in [from, to).
func (q *Queries) ListHotFlashesInRange(ctx context.Context, arg ListHotFlashesInRangeParams) ([]HotFlash, error) {
	rows, err := q.db.QueryContext(ctx, listHotFlashesInRange, arg.UserID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotFlash{}
	for rows.Next() {
		var i HotFlash
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.DurationS,
			&i.Severity,
			&i.Night,
			&i.Sweat,
			&i.Triggers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenopauseScoresSince = `-- name: ListMenopauseScoresSince :many
SELECT id, user_id, month, answers, total, somatic, psychological, urogenital, created_at, updated_at FROM ` + "`" + `menopause_scores` + "`" + `
WHERE user_id = ? AND month >= ?
ORDER BY month DESC
`

type ListMenopauseScoresSinceParams struct {
	UserID    uint64
	FromMonth civildate.Date
}

func (q *Queries) ListMenopauseScoresSince(ctx context.Context, arg ListMenopauseScoresSinceParams) ([]MenopauseScore, error) {
	rows, err := q.db.QueryContext(ctx, listMenopauseScoresSince, arg.UserID, arg.FromMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenopauseScore{}
	for rows.Next() {
		var i MenopauseScore
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Answers,
			&i.Total,
			&i.Somatic,
			&i.Psychological,
			&i.Urogenital,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSideEffectLogsInRange = `-- name: ListSideEffectLogsInRange :many
SELECT id, user_id, treatment_item_id, log_date, code, created_at, updated_at FROM ` + "`" + `side_effect_logs` + "`" + `
WHERE user_id = ? AND log_date >= ? AND log_date <= ?
ORDER BY log_date, code
`

type ListSideEffectLogsInRangeParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

// log_date in [from, to].
func (q *Queries) ListSideEffectLogsInRange(ctx context.Context, arg ListSideEffectLogsInRangeParams) ([]SideEffectLog, error) {
	rows, err := q.db.QueryContext(ctx, listSideEffectLogsInRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SideEffectLog{}
	for rows.Next() {
		var i SideEffectLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TreatmentItemID,
			&i.LogDate,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreatmentIntakesInRange = `-- name: ListTreatmentIntakesInRange :many
SELECT id, user_id, treatment_item_id, intake_date, amount, taken_at, created_at, updated_at FROM ` + "`" + `treatment_intakes` + "`" + `
WHERE user_id = ? AND intake_date >= ? AND intake_date <= ?
ORDER BY intake_date, treatment_item_id
`

type ListTreatmentIntakesInRangeParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

// intake_date in [from, to].
func (q *Queries) ListTreatmentIntakesInRange(ctx context.Context, arg ListTreatmentIntakesInRangeParams) ([]TreatmentIntake, error) {
	rows, err := q.db.QueryContext(ctx, listTreatmentIntakesInRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreatmentIntake{}
	for rows.Next() {
		var i TreatmentIntake
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TreatmentItemID,
			&i.IntakeDate,
			&i.Amount,
			&i.TakenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreatmentItems = `-- name: ListTreatmentItems :many
SELECT id, user_id, kind, name, dose, schedule, started_on, review_on, weekly_goal, goal_unit, stopped_on, reminder_id, sort_order, created_at, updated_at FROM ` + "`" + `treatment_items` + "`" + `
WHERE user_id = ?
ORDER BY kind, sort_order, id
`

func (q *Queries) ListTreatmentItems(ctx context.Context, userID uint64) ([]TreatmentItem, error) {
	rows, err := q.db.QueryContext(ctx, listTreatmentItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TreatmentItem{}
	for rows.Next() {
		var i TreatmentItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.Dose,
			&i.Schedule,
			&i.StartedOn,
			&i.ReviewOn,
			&i.WeeklyGoal,
			&i.GoalUnit,
			&i.StoppedOn,
			&i.ReminderID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMenopauseScore = `-- name: UpsertMenopauseScore :exec
INSERT INTO ` + "`" + `menopause_scores` + "`" + `
  (user_id, month, answers, total, somatic, psychological, urogenital, created_at, updated_at)
VALUES
  (?, ?, ?, ?, ?,
   ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  answers = VALUES(answers),
  total = VALUES(total),
  somatic = VALUES(somatic),
  psychological = VALUES(psychological),
  urogenital = VALUES(urogenital),
  updated_at = VALUES(updated_at)
`

type UpsertMenopauseScoreParams struct {
	UserID        uint64
	Month         civildate.Date
	Answers       json.RawMessage
	Total         uint8
	Somatic       uint8
	Psychological uint8
	Urogenital    uint8
	Now           sql.NullTime
}

// One questionnaire per (user, month); filling it again replaces the answers.
func (q *Queries) UpsertMenopauseScore(ctx context.Context, arg UpsertMenopauseScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertMenopauseScore,
		arg.UserID,
		arg.Month,
		arg.Answers,
		arg.Total,
		arg.Somatic,
		arg.Psychological,
		arg.Urogenital,
		arg.Now,
		arg.Now,
	)
	return err
}
