// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package store

import (
	"context"
)

const listActiveLanguages = `-- name: ListActiveLanguages :many

SELECT code, name, english_name, direction, is_default
FROM languages
WHERE is_active = 1
ORDER BY sort_order, id
`

type ListActiveLanguagesRow struct {
	Code        string
	Name        string
	EnglishName string
	Direction   string
	IsDefault   bool
}

// LanguageRegistry::load(): Language::query()->active()->ordered()->get().
func (q *Queries) ListActiveLanguages(ctx context.Context) ([]ListActiveLanguagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveLanguagesRow{}
	for rows.Next() {
		var i ListActiveLanguagesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.EnglishName,
			&i.Direction,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
