// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// LanguageRegistry::load(): Language::query()->active()->ordered()->get().
	ListActiveLanguages(ctx context.Context) ([]ListActiveLanguagesRow, error)
}

var _ Querier = (*Queries)(nil)
