// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sample.sql

package store

import (
	"context"
)

const sampleI18nLanguage = `-- name: SampleI18nLanguage :one

SELECT id, code, name, english_name, direction, is_active, is_default, sort_order, created_at, updated_at FROM ` + "`" + `languages` + "`" + ` WHERE id = ? LIMIT 1
`

// Placeholder so the `i18n` sqlc package exists and compiles before its domain task lands (T-M2-03).
// Delete this file when the first real query is added to db/queries/i18n/.
func (q *Queries) SampleI18nLanguage(ctx context.Context, id uint64) (Language, error) {
	row := q.db.QueryRowContext(ctx, sampleI18nLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.EnglishName,
		&i.Direction,
		&i.IsActive,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
