// Code generated by enumgen from backend/app/Enums/BmiCategory.php. DO NOT EDIT.

package enums

import "slices"

// BmiCategory mirrors the PHP enum BmiCategory (backend/app/Enums/BmiCategory.php).
type BmiCategory string

// BmiCategory cases, in PHP case order.
const (
	BmiCategoryUnderweight BmiCategory = "underweight" // PHP UNDERWEIGHT
	BmiCategoryNormal      BmiCategory = "normal"      // PHP NORMAL
	BmiCategoryOverweight  BmiCategory = "overweight"  // PHP OVERWEIGHT
	BmiCategoryObese       BmiCategory = "obese"       // PHP OBESE
)

var bmiCategoryCases = []BmiCategory{
	BmiCategoryUnderweight,
	BmiCategoryNormal,
	BmiCategoryOverweight,
	BmiCategoryObese,
}

// BmiCategoryCases returns every case in PHP case order (PHP BmiCategory::cases()).
func BmiCategoryCases() []BmiCategory { return slices.Clone(bmiCategoryCases) }

// BmiCategoryValues returns the backed values in PHP case order (PHP BmiCategory::values()).
func BmiCategoryValues() []string { return valuesOf(bmiCategoryCases) }

// IsValid reports whether e is one of the declared cases.
func (e BmiCategory) IsValid() bool {
	switch e {
	case BmiCategoryUnderweight, BmiCategoryNormal, BmiCategoryOverweight, BmiCategoryObese:
		return true
	}
	return false
}

// BmiCategoryFrom returns the case backed by v and whether it exists (PHP BmiCategory::tryFrom).
func BmiCategoryFrom(v string) (BmiCategory, bool) {
	e := BmiCategory(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e BmiCategory) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case BmiCategoryUnderweight:
			return "کم\u200cوزن"
		case BmiCategoryNormal:
			return "طبیعی"
		case BmiCategoryOverweight:
			return "اضافه\u200cوزن"
		case BmiCategoryObese:
			return "چاق"
		}
		return ""
	}
	switch e {
	case BmiCategoryUnderweight:
		return "Underweight"
	case BmiCategoryNormal:
		return "Normal"
	case BmiCategoryOverweight:
		return "Overweight"
	case BmiCategoryObese:
		return "Obese"
	}
	return ""
}

// BmiCategoryOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func BmiCategoryOptions(locale string) []Option { return optionsOf(bmiCategoryCases, locale) }
