// Code generated by enumgen from backend/app/Enums/Smell.php. DO NOT EDIT.

package enums

import "slices"

// Smell mirrors the PHP enum Smell (backend/app/Enums/Smell.php).
type Smell string

// Smell cases, in PHP case order.
const (
	SmellNormal           Smell = "normal"            // PHP NORMAL
	SmellSlightlyUnusual  Smell = "slightly_unusual"  // PHP SLIGHTLY_UNUSUAL
	SmellStrongUnpleasant Smell = "strong_unpleasant" // PHP STRONG_UNPLEASANT
)

var smellCases = []Smell{
	SmellNormal,
	SmellSlightlyUnusual,
	SmellStrongUnpleasant,
}

// SmellCases returns every case in PHP case order (PHP Smell::cases()).
func SmellCases() []Smell { return slices.Clone(smellCases) }

// SmellValues returns the backed values in PHP case order (PHP Smell::values()).
func SmellValues() []string { return valuesOf(smellCases) }

// IsValid reports whether e is one of the declared cases.
func (e Smell) IsValid() bool {
	switch e {
	case SmellNormal, SmellSlightlyUnusual, SmellStrongUnpleasant:
		return true
	}
	return false
}

// SmellFrom returns the case backed by v and whether it exists (PHP Smell::tryFrom).
func SmellFrom(v string) (Smell, bool) {
	e := Smell(v)
	return e, e.IsValid()
}

// Label returns the human label. The PHP label() has one table for every locale, so locale is ignored.
func (e Smell) Label(_ string) string {
	switch e {
	case SmellNormal:
		return "طبیعی"
	case SmellSlightlyUnusual:
		return "کمی غیرطبیعی"
	case SmellStrongUnpleasant:
		return "تند"
	}
	return ""
}

// SmellOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func SmellOptions(locale string) []Option { return optionsOf(smellCases, locale) }
