// Code generated by enumgen from backend/app/Enums/Amount.php. DO NOT EDIT.

package enums

import "slices"

// Amount mirrors the PHP enum Amount (backend/app/Enums/Amount.php).
type Amount string

// Amount cases, in PHP case order.
const (
	AmountLow    Amount = "low"    // PHP LOW
	AmountMedium Amount = "medium" // PHP MEDIUM
	AmountHigh   Amount = "high"   // PHP HIGH
)

var amountCases = []Amount{
	AmountLow,
	AmountMedium,
	AmountHigh,
}

// AmountCases returns every case in PHP case order (PHP Amount::cases()).
func AmountCases() []Amount { return slices.Clone(amountCases) }

// AmountValues returns the backed values in PHP case order (PHP Amount::values()).
func AmountValues() []string { return valuesOf(amountCases) }

// IsValid reports whether e is one of the declared cases.
func (e Amount) IsValid() bool {
	switch e {
	case AmountLow, AmountMedium, AmountHigh:
		return true
	}
	return false
}

// AmountFrom returns the case backed by v and whether it exists (PHP Amount::tryFrom).
func AmountFrom(v string) (Amount, bool) {
	e := Amount(v)
	return e, e.IsValid()
}

// Label returns the human label. The PHP label() has one table for every locale, so locale is ignored.
func (e Amount) Label(_ string) string {
	switch e {
	case AmountLow:
		return "کم"
	case AmountMedium:
		return "متوسط"
	case AmountHigh:
		return "زیاد"
	}
	return ""
}

// AmountOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func AmountOptions(locale string) []Option { return optionsOf(amountCases, locale) }
