// Code generated by enumgen from backend/app/Enums/ReminderType.php. DO NOT EDIT.

package enums

import "slices"

// ReminderType mirrors the PHP enum ReminderType (backend/app/Enums/ReminderType.php).
type ReminderType string

// ReminderType cases, in PHP case order.
const (
	ReminderTypeDoctor      ReminderType = "doctor"      // PHP DOCTOR
	ReminderTypeMedication  ReminderType = "medication"  // PHP MEDICATION
	ReminderTypeAppointment ReminderType = "appointment" // PHP APPOINTMENT
	ReminderTypeCustom      ReminderType = "custom"      // PHP CUSTOM
)

var reminderTypeCases = []ReminderType{
	ReminderTypeDoctor,
	ReminderTypeMedication,
	ReminderTypeAppointment,
	ReminderTypeCustom,
}

// ReminderTypeCases returns every case in PHP case order (PHP ReminderType::cases()).
func ReminderTypeCases() []ReminderType { return slices.Clone(reminderTypeCases) }

// ReminderTypeValues returns the backed values in PHP case order (PHP ReminderType::values()).
func ReminderTypeValues() []string { return valuesOf(reminderTypeCases) }

// IsValid reports whether e is one of the declared cases.
func (e ReminderType) IsValid() bool {
	switch e {
	case ReminderTypeDoctor, ReminderTypeMedication, ReminderTypeAppointment, ReminderTypeCustom:
		return true
	}
	return false
}

// ReminderTypeFrom returns the case backed by v and whether it exists (PHP ReminderType::tryFrom).
func ReminderTypeFrom(v string) (ReminderType, bool) {
	e := ReminderType(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e ReminderType) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case ReminderTypeDoctor:
			return "یادآور دکتر"
		case ReminderTypeMedication:
			return "یادآور دارو"
		case ReminderTypeAppointment:
			return "یادآور نوبت"
		case ReminderTypeCustom:
			return "یادآور"
		}
		return ""
	}
	switch e {
	case ReminderTypeDoctor:
		return "Doctor reminder"
	case ReminderTypeMedication:
		return "Medication reminder"
	case ReminderTypeAppointment:
		return "Appointment reminder"
	case ReminderTypeCustom:
		return "Reminder"
	}
	return ""
}

// Icon returns the icon key the clients map to an asset (PHP icon()).
func (e ReminderType) Icon() string {
	switch e {
	case ReminderTypeDoctor:
		return "stethoscope"
	case ReminderTypeMedication:
		return "pill"
	case ReminderTypeAppointment:
		return "calendar-clock"
	case ReminderTypeCustom:
		return "bell"
	}
	return ""
}

// ReminderTypeOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func ReminderTypeOptions(locale string) []Option { return optionsOf(reminderTypeCases, locale) }
