// Code generated by enumgen from backend/app/Services/MessageSystem/Enums/MessageMode.php. DO NOT EDIT.

package enums

import "slices"

// MessageMode mirrors the PHP enum MessageMode (backend/app/Services/MessageSystem/Enums/MessageMode.php).
type MessageMode string

// MessageMode cases, in PHP case order.
const (
	MessageModeCycle      MessageMode = "cycle"      // PHP CYCLE
	MessageModePregnancy  MessageMode = "pregnancy"  // PHP PREGNANCY
	MessageModePostpartum MessageMode = "postpartum" // PHP POSTPARTUM
)

var messageModeCases = []MessageMode{
	MessageModeCycle,
	MessageModePregnancy,
	MessageModePostpartum,
}

// MessageModeCases returns every case in PHP case order (PHP MessageMode::cases()).
func MessageModeCases() []MessageMode { return slices.Clone(messageModeCases) }

// MessageModeValues returns the backed values in PHP case order (PHP MessageMode::values()).
func MessageModeValues() []string { return valuesOf(messageModeCases) }

// IsValid reports whether e is one of the declared cases.
func (e MessageMode) IsValid() bool {
	switch e {
	case MessageModeCycle, MessageModePregnancy, MessageModePostpartum:
		return true
	}
	return false
}

// MessageModeFrom returns the case backed by v and whether it exists (PHP MessageMode::tryFrom).
func MessageModeFrom(v string) (MessageMode, bool) {
	e := MessageMode(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e MessageMode) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case MessageModeCycle:
			return "سیکل قاعدگی"
		case MessageModePregnancy:
			return "بارداری"
		case MessageModePostpartum:
			return "پس از زایمان"
		}
		return ""
	}
	switch e {
	case MessageModeCycle:
		return "Menstrual Cycle"
	case MessageModePregnancy:
		return "Pregnancy"
	case MessageModePostpartum:
		return "Postpartum"
	}
	return ""
}

// MessageModeOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func MessageModeOptions(locale string) []Option { return optionsOf(messageModeCases, locale) }
