// Code generated by enumgen from backend/app/Enums/BannerLinkType.php. DO NOT EDIT.

package enums

import "slices"

// BannerLinkType mirrors the PHP enum BannerLinkType (backend/app/Enums/BannerLinkType.php).
type BannerLinkType string

// BannerLinkType cases, in PHP case order.
const (
	BannerLinkTypeInternal BannerLinkType = "internal" // PHP INTERNAL
	BannerLinkTypeExternal BannerLinkType = "external" // PHP EXTERNAL
)

var bannerLinkTypeCases = []BannerLinkType{
	BannerLinkTypeInternal,
	BannerLinkTypeExternal,
}

// BannerLinkTypeCases returns every case in PHP case order (PHP BannerLinkType::cases()).
func BannerLinkTypeCases() []BannerLinkType { return slices.Clone(bannerLinkTypeCases) }

// BannerLinkTypeValues returns the backed values in PHP case order (PHP BannerLinkType::values()).
func BannerLinkTypeValues() []string { return valuesOf(bannerLinkTypeCases) }

// IsValid reports whether e is one of the declared cases.
func (e BannerLinkType) IsValid() bool {
	switch e {
	case BannerLinkTypeInternal, BannerLinkTypeExternal:
		return true
	}
	return false
}

// BannerLinkTypeFrom returns the case backed by v and whether it exists (PHP BannerLinkType::tryFrom).
func BannerLinkTypeFrom(v string) (BannerLinkType, bool) {
	e := BannerLinkType(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e BannerLinkType) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case BannerLinkTypeInternal:
			return "داخلی (درون برنامه)"
		case BannerLinkTypeExternal:
			return "خارجی (تب جدید)"
		}
		return ""
	}
	switch e {
	case BannerLinkTypeInternal:
		return "Internal (in-app)"
	case BannerLinkTypeExternal:
		return "External (new tab)"
	}
	return ""
}

// BannerLinkTypeOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func BannerLinkTypeOptions(locale string) []Option { return optionsOf(bannerLinkTypeCases, locale) }
