// Code generated by enumgen from backend/app/Enums/PregnancyIntention.php. DO NOT EDIT.

package enums

import "slices"

// PregnancyIntention mirrors the PHP enum PregnancyIntention (backend/app/Enums/PregnancyIntention.php).
type PregnancyIntention string

// PregnancyIntention cases, in PHP case order.
const (
	PregnancyIntentionAvoiding PregnancyIntention = "avoiding" // PHP AVOIDING
	PregnancyIntentionPregnant PregnancyIntention = "pregnant" // PHP PREGNANT
	PregnancyIntentionTrying   PregnancyIntention = "trying"   // PHP TRYING
	PregnancyIntentionUnsure   PregnancyIntention = "unsure"   // PHP UNSURE
)

var pregnancyIntentionCases = []PregnancyIntention{
	PregnancyIntentionAvoiding,
	PregnancyIntentionPregnant,
	PregnancyIntentionTrying,
	PregnancyIntentionUnsure,
}

// PregnancyIntentionCases returns every case in PHP case order (PHP PregnancyIntention::cases()).
func PregnancyIntentionCases() []PregnancyIntention { return slices.Clone(pregnancyIntentionCases) }

// PregnancyIntentionValues returns the backed values in PHP case order (PHP PregnancyIntention::values()).
func PregnancyIntentionValues() []string { return valuesOf(pregnancyIntentionCases) }

// IsValid reports whether e is one of the declared cases.
func (e PregnancyIntention) IsValid() bool {
	switch e {
	case PregnancyIntentionAvoiding, PregnancyIntentionPregnant, PregnancyIntentionTrying, PregnancyIntentionUnsure:
		return true
	}
	return false
}

// PregnancyIntentionFrom returns the case backed by v and whether it exists (PHP PregnancyIntention::tryFrom).
func PregnancyIntentionFrom(v string) (PregnancyIntention, bool) {
	e := PregnancyIntention(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e PregnancyIntention) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case PregnancyIntentionAvoiding:
			return "فعلاً قصد بارداری ندارم"
		case PregnancyIntentionPregnant:
			return "باردار هستم"
		case PregnancyIntentionTrying:
			return "در حال تلاش برای بارداری هستم"
		case PregnancyIntentionUnsure:
			return "مطمئن نیستم / هنوز تصمیم نگرفته\u200cام"
		}
		return ""
	}
	switch e {
	case PregnancyIntentionAvoiding:
		return "Not planning a pregnancy right now"
	case PregnancyIntentionPregnant:
		return "I am pregnant"
	case PregnancyIntentionTrying:
		return "Trying to conceive"
	case PregnancyIntentionUnsure:
		return "Not sure yet"
	}
	return ""
}

// PregnancyIntentionOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func PregnancyIntentionOptions(locale string) []Option {
	return optionsOf(pregnancyIntentionCases, locale)
}
