// Code generated by enumgen from backend/app/Enums/ResolutionSource.php. DO NOT EDIT.

package enums

import "slices"

// ResolutionSource mirrors the PHP enum ResolutionSource (backend/app/Enums/ResolutionSource.php).
type ResolutionSource string

// ResolutionSource cases, in PHP case order.
const (
	ResolutionSourceUserLogged               ResolutionSource = "user_logged"                  // PHP USER_LOGGED
	ResolutionSourceUserLoggedWithAssumedEnd ResolutionSource = "user_logged_with_assumed_end" // PHP USER_LOGGED_WITH_ASSUMED_END
	ResolutionSourcePrediction               ResolutionSource = "prediction"                   // PHP PREDICTION
	ResolutionSourceOnboardingBased          ResolutionSource = "onboarding_based"             // PHP ONBOARDING_BASED
	ResolutionSourceDefaultBased             ResolutionSource = "default_based"                // PHP DEFAULT_BASED
	ResolutionSourceUnknown                  ResolutionSource = "unknown"                      // PHP UNKNOWN
)

var resolutionSourceCases = []ResolutionSource{
	ResolutionSourceUserLogged,
	ResolutionSourceUserLoggedWithAssumedEnd,
	ResolutionSourcePrediction,
	ResolutionSourceOnboardingBased,
	ResolutionSourceDefaultBased,
	ResolutionSourceUnknown,
}

// ResolutionSourceCases returns every case in PHP case order (PHP ResolutionSource::cases()).
func ResolutionSourceCases() []ResolutionSource { return slices.Clone(resolutionSourceCases) }

// ResolutionSourceValues returns the backed values in PHP case order (PHP ResolutionSource::values()).
func ResolutionSourceValues() []string { return valuesOf(resolutionSourceCases) }

// IsValid reports whether e is one of the declared cases.
func (e ResolutionSource) IsValid() bool {
	switch e {
	case ResolutionSourceUserLogged, ResolutionSourceUserLoggedWithAssumedEnd, ResolutionSourcePrediction, ResolutionSourceOnboardingBased, ResolutionSourceDefaultBased, ResolutionSourceUnknown:
		return true
	}
	return false
}

// ResolutionSourceFrom returns the case backed by v and whether it exists (PHP ResolutionSource::tryFrom).
func ResolutionSourceFrom(v string) (ResolutionSource, bool) {
	e := ResolutionSource(v)
	return e, e.IsValid()
}
