// Code generated by enumgen from backend/app/Enums/CycleVariability.php. DO NOT EDIT.

package enums

import "slices"

// CycleVariability mirrors the PHP enum CycleVariability (backend/app/Enums/CycleVariability.php).
type CycleVariability string

// CycleVariability cases, in PHP case order.
const (
	CycleVariabilityRegular       CycleVariability = "regular"        // PHP REGULAR
	CycleVariabilitySemiIrregular CycleVariability = "semi_irregular" // PHP SEMI_IRREGULAR
	CycleVariabilityIrregular     CycleVariability = "irregular"      // PHP IRREGULAR
)

var cycleVariabilityCases = []CycleVariability{
	CycleVariabilityRegular,
	CycleVariabilitySemiIrregular,
	CycleVariabilityIrregular,
}

// CycleVariabilityCases returns every case in PHP case order (PHP CycleVariability::cases()).
func CycleVariabilityCases() []CycleVariability { return slices.Clone(cycleVariabilityCases) }

// CycleVariabilityValues returns the backed values in PHP case order (PHP CycleVariability::values()).
func CycleVariabilityValues() []string { return valuesOf(cycleVariabilityCases) }

// IsValid reports whether e is one of the declared cases.
func (e CycleVariability) IsValid() bool {
	switch e {
	case CycleVariabilityRegular, CycleVariabilitySemiIrregular, CycleVariabilityIrregular:
		return true
	}
	return false
}

// CycleVariabilityFrom returns the case backed by v and whether it exists (PHP CycleVariability::tryFrom).
func CycleVariabilityFrom(v string) (CycleVariability, bool) {
	e := CycleVariability(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e CycleVariability) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case CycleVariabilityRegular:
			return "منظم"
		case CycleVariabilitySemiIrregular:
			return "نیمه\u200cمنظم"
		case CycleVariabilityIrregular:
			return "نامنظم"
		}
		return ""
	}
	switch e {
	case CycleVariabilityRegular:
		return "Regular"
	case CycleVariabilitySemiIrregular:
		return "Semi-Irregular"
	case CycleVariabilityIrregular:
		return "Irregular"
	}
	return ""
}

// CycleVariabilityOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func CycleVariabilityOptions(locale string) []Option { return optionsOf(cycleVariabilityCases, locale) }
