// Code generated by enumgen from backend/app/Enums/NotificationType.php. DO NOT EDIT.

package enums

import "slices"

// NotificationType mirrors the PHP enum NotificationType (backend/app/Enums/NotificationType.php).
type NotificationType string

// NotificationType cases, in PHP case order.
const (
	NotificationTypeReminder    NotificationType = "reminder"    // PHP REMINDER
	NotificationTypeAlert       NotificationType = "alert"       // PHP ALERT
	NotificationTypeTip         NotificationType = "tip"         // PHP TIP
	NotificationTypeAchievement NotificationType = "achievement" // PHP ACHIEVEMENT
	NotificationTypeSystem      NotificationType = "system"      // PHP SYSTEM
)

var notificationTypeCases = []NotificationType{
	NotificationTypeReminder,
	NotificationTypeAlert,
	NotificationTypeTip,
	NotificationTypeAchievement,
	NotificationTypeSystem,
}

// NotificationTypeCases returns every case in PHP case order (PHP NotificationType::cases()).
func NotificationTypeCases() []NotificationType { return slices.Clone(notificationTypeCases) }

// NotificationTypeValues returns the backed values in PHP case order (PHP NotificationType::values()).
func NotificationTypeValues() []string { return valuesOf(notificationTypeCases) }

// IsValid reports whether e is one of the declared cases.
func (e NotificationType) IsValid() bool {
	switch e {
	case NotificationTypeReminder, NotificationTypeAlert, NotificationTypeTip, NotificationTypeAchievement, NotificationTypeSystem:
		return true
	}
	return false
}

// NotificationTypeFrom returns the case backed by v and whether it exists (PHP NotificationType::tryFrom).
func NotificationTypeFrom(v string) (NotificationType, bool) {
	e := NotificationType(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e NotificationType) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case NotificationTypeReminder:
			return "یادآوری"
		case NotificationTypeAlert:
			return "هشدار"
		case NotificationTypeTip:
			return "نکته"
		case NotificationTypeAchievement:
			return "دستاورد"
		case NotificationTypeSystem:
			return "سیستمی"
		}
		return ""
	}
	switch e {
	case NotificationTypeReminder:
		return "Reminder"
	case NotificationTypeAlert:
		return "Alert"
	case NotificationTypeTip:
		return "Tip"
	case NotificationTypeAchievement:
		return "Achievement"
	case NotificationTypeSystem:
		return "System"
	}
	return ""
}

// NotificationTypeOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func NotificationTypeOptions(locale string) []Option { return optionsOf(notificationTypeCases, locale) }
