// Code generated by enumgen from backend/app/Enums/EnergyLevel.php. DO NOT EDIT.

package enums

import "slices"

// EnergyLevel mirrors the PHP enum EnergyLevel (backend/app/Enums/EnergyLevel.php).
type EnergyLevel string

// EnergyLevel cases, in PHP case order.
const (
	EnergyLevelVeryLow  EnergyLevel = "very_low"  // PHP VERY_LOW
	EnergyLevelLow      EnergyLevel = "low"       // PHP LOW
	EnergyLevelMedium   EnergyLevel = "medium"    // PHP MEDIUM
	EnergyLevelHigh     EnergyLevel = "high"      // PHP HIGH
	EnergyLevelVeryHigh EnergyLevel = "very_high" // PHP VERY_HIGH
)

var energyLevelCases = []EnergyLevel{
	EnergyLevelVeryLow,
	EnergyLevelLow,
	EnergyLevelMedium,
	EnergyLevelHigh,
	EnergyLevelVeryHigh,
}

// EnergyLevelCases returns every case in PHP case order (PHP EnergyLevel::cases()).
func EnergyLevelCases() []EnergyLevel { return slices.Clone(energyLevelCases) }

// EnergyLevelValues returns the backed values in PHP case order (PHP EnergyLevel::values()).
func EnergyLevelValues() []string { return valuesOf(energyLevelCases) }

// IsValid reports whether e is one of the declared cases.
func (e EnergyLevel) IsValid() bool {
	switch e {
	case EnergyLevelVeryLow, EnergyLevelLow, EnergyLevelMedium, EnergyLevelHigh, EnergyLevelVeryHigh:
		return true
	}
	return false
}

// EnergyLevelFrom returns the case backed by v and whether it exists (PHP EnergyLevel::tryFrom).
func EnergyLevelFrom(v string) (EnergyLevel, bool) {
	e := EnergyLevel(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e EnergyLevel) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case EnergyLevelVeryLow:
			return "خیلی کم"
		case EnergyLevelLow:
			return "کم"
		case EnergyLevelMedium:
			return "متوسط"
		case EnergyLevelHigh:
			return "زیاد"
		case EnergyLevelVeryHigh:
			return "خیلی زیاد"
		}
		return ""
	}
	switch e {
	case EnergyLevelVeryLow:
		return "Very low"
	case EnergyLevelLow:
		return "Low"
	case EnergyLevelMedium:
		return "Medium"
	case EnergyLevelHigh:
		return "High"
	case EnergyLevelVeryHigh:
		return "Very high"
	}
	return ""
}

// EnergyLevelOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func EnergyLevelOptions(locale string) []Option { return optionsOf(energyLevelCases, locale) }
