// Code generated by enumgen from backend/app/Enums/RecommendationTrigger.php. DO NOT EDIT.

package enums

import "slices"

// RecommendationTrigger mirrors the PHP enum RecommendationTrigger (backend/app/Enums/RecommendationTrigger.php).
type RecommendationTrigger string

// RecommendationTrigger cases, in PHP case order.
const (
	RecommendationTriggerHeadache  RecommendationTrigger = "headache"   // PHP HEADACHE
	RecommendationTriggerCramps    RecommendationTrigger = "cramps"     // PHP CRAMPS
	RecommendationTriggerPoorSleep RecommendationTrigger = "poor_sleep" // PHP POOR_SLEEP
	RecommendationTriggerLowMood   RecommendationTrigger = "low_mood"   // PHP LOW_MOOD
	RecommendationTriggerBloating  RecommendationTrigger = "bloating"   // PHP BLOATING
	RecommendationTriggerFatigue   RecommendationTrigger = "fatigue"    // PHP FATIGUE
)

var recommendationTriggerCases = []RecommendationTrigger{
	RecommendationTriggerHeadache,
	RecommendationTriggerCramps,
	RecommendationTriggerPoorSleep,
	RecommendationTriggerLowMood,
	RecommendationTriggerBloating,
	RecommendationTriggerFatigue,
}

// RecommendationTriggerCases returns every case in PHP case order (PHP RecommendationTrigger::cases()).
func RecommendationTriggerCases() []RecommendationTrigger {
	return slices.Clone(recommendationTriggerCases)
}

// RecommendationTriggerValues returns the backed values in PHP case order (PHP RecommendationTrigger::values()).
func RecommendationTriggerValues() []string { return valuesOf(recommendationTriggerCases) }

// IsValid reports whether e is one of the declared cases.
func (e RecommendationTrigger) IsValid() bool {
	switch e {
	case RecommendationTriggerHeadache, RecommendationTriggerCramps, RecommendationTriggerPoorSleep, RecommendationTriggerLowMood, RecommendationTriggerBloating, RecommendationTriggerFatigue:
		return true
	}
	return false
}

// RecommendationTriggerFrom returns the case backed by v and whether it exists (PHP RecommendationTrigger::tryFrom).
func RecommendationTriggerFrom(v string) (RecommendationTrigger, bool) {
	e := RecommendationTrigger(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e RecommendationTrigger) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case RecommendationTriggerHeadache:
			return "سردرد"
		case RecommendationTriggerCramps:
			return "درد و کرامپ"
		case RecommendationTriggerPoorSleep:
			return "کیفیت خواب بد"
		case RecommendationTriggerLowMood:
			return "اضطراب یا غم"
		case RecommendationTriggerBloating:
			return "نفخ"
		case RecommendationTriggerFatigue:
			return "خستگی"
		}
		return ""
	}
	switch e {
	case RecommendationTriggerHeadache:
		return "Headache"
	case RecommendationTriggerCramps:
		return "Cramps"
	case RecommendationTriggerPoorSleep:
		return "Poor sleep"
	case RecommendationTriggerLowMood:
		return "Anxious or sad mood"
	case RecommendationTriggerBloating:
		return "Bloating"
	case RecommendationTriggerFatigue:
		return "Fatigue"
	}
	return ""
}

// RecommendationTriggerOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func RecommendationTriggerOptions(locale string) []Option {
	return optionsOf(recommendationTriggerCases, locale)
}
