// Code generated by enumgen from backend/app/Enums/PainIntensity.php. DO NOT EDIT.

package enums

import "slices"

// PainIntensity mirrors the PHP enum PainIntensity (backend/app/Enums/PainIntensity.php).
type PainIntensity string

// PainIntensity cases, in PHP case order.
const (
	PainIntensityLow    PainIntensity = "low"    // PHP LOW
	PainIntensityMedium PainIntensity = "medium" // PHP MEDIUM
	PainIntensityHigh   PainIntensity = "high"   // PHP HIGH
)

var painIntensityCases = []PainIntensity{
	PainIntensityLow,
	PainIntensityMedium,
	PainIntensityHigh,
}

// PainIntensityCases returns every case in PHP case order (PHP PainIntensity::cases()).
func PainIntensityCases() []PainIntensity { return slices.Clone(painIntensityCases) }

// PainIntensityValues returns the backed values in PHP case order (PHP PainIntensity::values()).
func PainIntensityValues() []string { return valuesOf(painIntensityCases) }

// IsValid reports whether e is one of the declared cases.
func (e PainIntensity) IsValid() bool {
	switch e {
	case PainIntensityLow, PainIntensityMedium, PainIntensityHigh:
		return true
	}
	return false
}

// PainIntensityFrom returns the case backed by v and whether it exists (PHP PainIntensity::tryFrom).
func PainIntensityFrom(v string) (PainIntensity, bool) {
	e := PainIntensity(v)
	return e, e.IsValid()
}

// Label returns the human label. The PHP label() has one table for every locale, so locale is ignored.
func (e PainIntensity) Label(_ string) string {
	switch e {
	case PainIntensityLow:
		return "کم"
	case PainIntensityMedium:
		return "متوسط"
	case PainIntensityHigh:
		return "زیاد"
	}
	return ""
}

// PainIntensityOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func PainIntensityOptions(locale string) []Option { return optionsOf(painIntensityCases, locale) }
