// Code generated by enumgen from backend/app/Enums/SexualActivity.php. DO NOT EDIT.

package enums

import "slices"

// SexualActivity mirrors the PHP enum SexualActivity (backend/app/Enums/SexualActivity.php).
type SexualActivity string

// SexualActivity cases, in PHP case order.
const (
	SexualActivityHighDesire               SexualActivity = "high_desire"                // PHP HIGH_DESIRE
	SexualActivityProtectedIntercourse     SexualActivity = "protected_intercourse"      // PHP PROTECTED_INTERCOURSE
	SexualActivityUnprotectedIntercourse   SexualActivity = "unprotected_intercourse"    // PHP UNPROTECTED_INTERCOURSE
	SexualActivityNoDesire                 SexualActivity = "no_desire"                  // PHP NO_DESIRE
	SexualActivityDryness                  SexualActivity = "dryness"                    // PHP DRYNESS
	SexualActivityBurning                  SexualActivity = "burning"                    // PHP BURNING
	SexualActivityPainDuringIntercourse    SexualActivity = "pain_during_intercourse"    // PHP PAIN_DURING_INTERCOURSE
	SexualActivityBleedingAfterIntercourse SexualActivity = "bleeding_after_intercourse" // PHP BLEEDING_AFTER_INTERCOURSE
	SexualActivityLubricantUse             SexualActivity = "lubricant_use"              // PHP LUBRICANT_USE
)

var sexualActivityCases = []SexualActivity{
	SexualActivityHighDesire,
	SexualActivityProtectedIntercourse,
	SexualActivityUnprotectedIntercourse,
	SexualActivityNoDesire,
	SexualActivityDryness,
	SexualActivityBurning,
	SexualActivityPainDuringIntercourse,
	SexualActivityBleedingAfterIntercourse,
	SexualActivityLubricantUse,
}

// SexualActivityCases returns every case in PHP case order (PHP SexualActivity::cases()).
func SexualActivityCases() []SexualActivity { return slices.Clone(sexualActivityCases) }

// SexualActivityValues returns the backed values in PHP case order (PHP SexualActivity::values()).
func SexualActivityValues() []string { return valuesOf(sexualActivityCases) }

// IsValid reports whether e is one of the declared cases.
func (e SexualActivity) IsValid() bool {
	switch e {
	case SexualActivityHighDesire, SexualActivityProtectedIntercourse, SexualActivityUnprotectedIntercourse, SexualActivityNoDesire, SexualActivityDryness, SexualActivityBurning, SexualActivityPainDuringIntercourse, SexualActivityBleedingAfterIntercourse, SexualActivityLubricantUse:
		return true
	}
	return false
}

// SexualActivityFrom returns the case backed by v and whether it exists (PHP SexualActivity::tryFrom).
func SexualActivityFrom(v string) (SexualActivity, bool) {
	e := SexualActivity(v)
	return e, e.IsValid()
}

// Label returns the human label. The PHP label() has one table for every locale, so locale is ignored.
func (e SexualActivity) Label(_ string) string {
	switch e {
	case SexualActivityHighDesire:
		return "High sexual desire"
	case SexualActivityProtectedIntercourse:
		return "Protected intercourse"
	case SexualActivityUnprotectedIntercourse:
		return "Unprotected intercourse"
	case SexualActivityNoDesire:
		return "No sexual desire"
	case SexualActivityDryness:
		return "Dryness"
	case SexualActivityBurning:
		return "Burning"
	case SexualActivityPainDuringIntercourse:
		return "Pain during intercourse"
	case SexualActivityBleedingAfterIntercourse:
		return "Bleeding after intercourse"
	case SexualActivityLubricantUse:
		return "Lubricant use"
	}
	return ""
}

// SexualActivityOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func SexualActivityOptions(locale string) []Option { return optionsOf(sexualActivityCases, locale) }
