// Code generated by enumgen from backend/app/Enums/RhFactor.php. DO NOT EDIT.

package enums

import "slices"

// RhFactor mirrors the PHP enum RhFactor (backend/app/Enums/RhFactor.php).
type RhFactor string

// RhFactor cases, in PHP case order.
const (
	RhFactorPositive RhFactor = "positive" // PHP POSITIVE
	RhFactorNegative RhFactor = "negative" // PHP NEGATIVE
)

var rhFactorCases = []RhFactor{
	RhFactorPositive,
	RhFactorNegative,
}

// RhFactorCases returns every case in PHP case order (PHP RhFactor::cases()).
func RhFactorCases() []RhFactor { return slices.Clone(rhFactorCases) }

// RhFactorValues returns the backed values in PHP case order (PHP RhFactor::values()).
func RhFactorValues() []string { return valuesOf(rhFactorCases) }

// IsValid reports whether e is one of the declared cases.
func (e RhFactor) IsValid() bool {
	switch e {
	case RhFactorPositive, RhFactorNegative:
		return true
	}
	return false
}

// RhFactorFrom returns the case backed by v and whether it exists (PHP RhFactor::tryFrom).
func RhFactorFrom(v string) (RhFactor, bool) {
	e := RhFactor(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e RhFactor) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case RhFactorPositive:
			return "مثبت"
		case RhFactorNegative:
			return "منفی"
		}
		return ""
	}
	switch e {
	case RhFactorPositive:
		return "Positive"
	case RhFactorNegative:
		return "Negative"
	}
	return ""
}

// RhFactorOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func RhFactorOptions(locale string) []Option { return optionsOf(rhFactorCases, locale) }
