// Code generated by enumgen from backend/app/Enums/Intensity.php. DO NOT EDIT.

package enums

import "slices"

// Intensity mirrors the PHP enum Intensity (backend/app/Enums/Intensity.php).
type Intensity string

// Intensity cases, in PHP case order.
const (
	IntensityLow      Intensity = "low"       // PHP LOW
	IntensityMedium   Intensity = "medium"    // PHP MEDIUM
	IntensityHigh     Intensity = "high"      // PHP HIGH
	IntensityVeryHigh Intensity = "very_high" // PHP VERY_HIGH
)

var intensityCases = []Intensity{
	IntensityLow,
	IntensityMedium,
	IntensityHigh,
	IntensityVeryHigh,
}

// IntensityCases returns every case in PHP case order (PHP Intensity::cases()).
func IntensityCases() []Intensity { return slices.Clone(intensityCases) }

// IntensityValues returns the backed values in PHP case order (PHP Intensity::values()).
func IntensityValues() []string { return valuesOf(intensityCases) }

// IsValid reports whether e is one of the declared cases.
func (e Intensity) IsValid() bool {
	switch e {
	case IntensityLow, IntensityMedium, IntensityHigh, IntensityVeryHigh:
		return true
	}
	return false
}

// IntensityFrom returns the case backed by v and whether it exists (PHP Intensity::tryFrom).
func IntensityFrom(v string) (Intensity, bool) {
	e := Intensity(v)
	return e, e.IsValid()
}

// Label returns the human label. The PHP label() has one table for every locale, so locale is ignored.
func (e Intensity) Label(_ string) string {
	switch e {
	case IntensityLow:
		return "کم"
	case IntensityMedium:
		return "متوسط"
	case IntensityHigh:
		return "زیاد"
	case IntensityVeryHigh:
		return "خیلی زیاد"
	}
	return ""
}

// IntensityOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func IntensityOptions(locale string) []Option { return optionsOf(intensityCases, locale) }
