// Code generated by enumgen from backend/app/Enums/AlertLevel.php. DO NOT EDIT.

package enums

import "slices"

// AlertLevel mirrors the PHP enum AlertLevel (backend/app/Enums/AlertLevel.php).
type AlertLevel string

// AlertLevel cases, in PHP case order.
const (
	AlertLevelInfo      AlertLevel = "info"      // PHP INFO
	AlertLevelWarning   AlertLevel = "warning"   // PHP WARNING
	AlertLevelEmergency AlertLevel = "emergency" // PHP EMERGENCY
)

var alertLevelCases = []AlertLevel{
	AlertLevelInfo,
	AlertLevelWarning,
	AlertLevelEmergency,
}

// AlertLevelCases returns every case in PHP case order (PHP AlertLevel::cases()).
func AlertLevelCases() []AlertLevel { return slices.Clone(alertLevelCases) }

// AlertLevelValues returns the backed values in PHP case order (PHP AlertLevel::values()).
func AlertLevelValues() []string { return valuesOf(alertLevelCases) }

// IsValid reports whether e is one of the declared cases.
func (e AlertLevel) IsValid() bool {
	switch e {
	case AlertLevelInfo, AlertLevelWarning, AlertLevelEmergency:
		return true
	}
	return false
}

// AlertLevelFrom returns the case backed by v and whether it exists (PHP AlertLevel::tryFrom).
func AlertLevelFrom(v string) (AlertLevel, bool) {
	e := AlertLevel(v)
	return e, e.IsValid()
}

// Label returns the human label for locale (PHP label($locale)): "fa"; any other locale gets the default table.
func (e AlertLevel) Label(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case AlertLevelInfo:
			return "اطلاع\u200cرسانی"
		case AlertLevelWarning:
			return "هشدار"
		case AlertLevelEmergency:
			return "اورژانسی"
		}
		return ""
	}
	switch e {
	case AlertLevelInfo:
		return "Information"
	case AlertLevelWarning:
		return "Warning"
	case AlertLevelEmergency:
		return "Emergency"
	}
	return ""
}

// Description returns the longer description for locale (PHP description($locale)): "fa"; any other locale gets the default table.
func (e AlertLevel) Description(locale string) string {
	switch locale {
	case "fa":
		switch e {
		case AlertLevelInfo:
			return "اطلاعات عمومی و راهنمایی"
		case AlertLevelWarning:
			return "نیاز به توجه و احتیاط"
		case AlertLevelEmergency:
			return "مراجعه فوری به پزشک"
		}
		return ""
	}
	switch e {
	case AlertLevelInfo:
		return "General information and guidance"
	case AlertLevelWarning:
		return "Requires attention and caution"
	case AlertLevelEmergency:
		return "Immediate medical attention required"
	}
	return ""
}

// AlertLevelOptions returns {value, label} pairs for every case in PHP case order (the shape of PHP options($locale)).
func AlertLevelOptions(locale string) []Option { return optionsOf(alertLevelCases, locale) }
