// Code generated by enumgen. DO NOT EDIT.

package enums

var generatedEnums = map[string]enumAccessor{
	"AlertLevel": {
		values:      AlertLevelValues,
		label:       func(v, locale string) string { return AlertLevel(v).Label(locale) },
		description: func(v, locale string) string { return AlertLevel(v).Description(locale) },
		options:     AlertLevelOptions,
	},
	"Amount": {
		values:  AmountValues,
		label:   func(v, locale string) string { return Amount(v).Label(locale) },
		options: AmountOptions,
	},
	"BannerLinkType": {
		values:  BannerLinkTypeValues,
		label:   func(v, locale string) string { return BannerLinkType(v).Label(locale) },
		options: BannerLinkTypeOptions,
	},
	"BannerPosition": {
		values:  BannerPositionValues,
		label:   func(v, locale string) string { return BannerPosition(v).Label(locale) },
		options: BannerPositionOptions,
	},
	"BloodColor": {
		values:  BloodColorValues,
		label:   func(v, locale string) string { return BloodColor(v).Label(locale) },
		options: BloodColorOptions,
	},
	"BloodType": {
		values:  BloodTypeValues,
		label:   func(v, locale string) string { return BloodType(v).Label(locale) },
		options: BloodTypeOptions,
	},
	"BmiCategory": {
		values:  BmiCategoryValues,
		label:   func(v, locale string) string { return BmiCategory(v).Label(locale) },
		options: BmiCategoryOptions,
	},
	"CalculationStatus": {
		values:  CalculationStatusValues,
		label:   func(v, locale string) string { return CalculationStatus(v).Label(locale) },
		options: CalculationStatusOptions,
	},
	"ChronicCondition": {
		values:  ChronicConditionValues,
		label:   func(v, locale string) string { return ChronicCondition(v).Label(locale) },
		options: ChronicConditionOptions,
	},
	"ClotsAmount": {
		values:  ClotsAmountValues,
		label:   func(v, locale string) string { return ClotsAmount(v).Label(locale) },
		options: ClotsAmountOptions,
	},
	"ConfidenceLevel": {
		values:      ConfidenceLevelValues,
		label:       func(v, locale string) string { return ConfidenceLevel(v).Label(locale) },
		description: func(v, locale string) string { return ConfidenceLevel(v).Description(locale) },
		options:     ConfidenceLevelOptions,
	},
	"CyclePhase": {
		values:      CyclePhaseValues,
		label:       func(v, locale string) string { return CyclePhase(v).Label(locale) },
		description: func(v, locale string) string { return CyclePhase(v).Description(locale) },
		options:     CyclePhaseOptions,
	},
	"CycleSubphase": {
		values: CycleSubphaseValues,
		label:  func(v, locale string) string { return CycleSubphase(v).Label(locale) },
	},
	"CycleVariability": {
		values:  CycleVariabilityValues,
		label:   func(v, locale string) string { return CycleVariability(v).Label(locale) },
		options: CycleVariabilityOptions,
	},
	"CycleWarning": {
		values: CycleWarningValues,
	},
	"DataQualityFlag": {
		values:  DataQualityFlagValues,
		label:   func(v, locale string) string { return DataQualityFlag(v).Label(locale) },
		options: DataQualityFlagOptions,
	},
	"DataQualityLevel": {
		values: DataQualityLevelValues,
	},
	"DataSource": {
		values:  DataSourceValues,
		label:   func(v, locale string) string { return DataSource(v).Label(locale) },
		options: DataSourceOptions,
	},
	"DataStatus": {
		values:  DataStatusValues,
		label:   func(v, locale string) string { return DataStatus(v).Label(locale) },
		options: DataStatusOptions,
	},
	"DischargeColor": {
		values:  DischargeColorValues,
		label:   func(v, locale string) string { return DischargeColor(v).Label(locale) },
		options: DischargeColorOptions,
	},
	"DischargeTexture": {
		values:  DischargeTextureValues,
		label:   func(v, locale string) string { return DischargeTexture(v).Label(locale) },
		options: DischargeTextureOptions,
	},
	"EffectiveSource": {
		values:  EffectiveSourceValues,
		label:   func(v, locale string) string { return EffectiveSource(v).Label(locale) },
		options: EffectiveSourceOptions,
	},
	"EnergyLevel": {
		values:  EnergyLevelValues,
		label:   func(v, locale string) string { return EnergyLevel(v).Label(locale) },
		options: EnergyLevelOptions,
	},
	"ExerciseIntensity": {
		values:  ExerciseIntensityValues,
		label:   func(v, locale string) string { return ExerciseIntensity(v).Label(locale) },
		options: ExerciseIntensityOptions,
	},
	"ExerciseType": {
		values:  ExerciseTypeValues,
		label:   func(v, locale string) string { return ExerciseType(v).Label(locale) },
		options: ExerciseTypeOptions,
	},
	"FertilityLevel": {
		values:  FertilityLevelValues,
		label:   func(v, locale string) string { return FertilityLevel(v).Label(locale) },
		options: FertilityLevelOptions,
	},
	"FetalMovementStatus": {
		values:  FetalMovementStatusValues,
		label:   func(v, locale string) string { return FetalMovementStatus(v).Label(locale) },
		options: FetalMovementStatusOptions,
	},
	"Intensity": {
		values:  IntensityValues,
		label:   func(v, locale string) string { return Intensity(v).Label(locale) },
		options: IntensityOptions,
	},
	"IntercourseType": {
		values:  IntercourseTypeValues,
		label:   func(v, locale string) string { return IntercourseType(v).Label(locale) },
		options: IntercourseTypeOptions,
	},
	"MainPhase": {
		values:  MainPhaseValues,
		label:   func(v, locale string) string { return MainPhase(v).Label(locale) },
		options: MainPhaseOptions,
	},
	"MentalHealthStatus": {
		values:  MentalHealthStatusValues,
		label:   func(v, locale string) string { return MentalHealthStatus(v).Label(locale) },
		options: MentalHealthStatusOptions,
	},
	"Mood": {
		values:  MoodValues,
		label:   func(v, locale string) string { return Mood(v).Label(locale) },
		options: MoodOptions,
	},
	"NotificationType": {
		values:  NotificationTypeValues,
		label:   func(v, locale string) string { return NotificationType(v).Label(locale) },
		options: NotificationTypeOptions,
	},
	"OverrideType": {
		values:  OverrideTypeValues,
		label:   func(v, locale string) string { return OverrideType(v).Label(locale) },
		options: OverrideTypeOptions,
	},
	"PainIntensity": {
		values:  PainIntensityValues,
		label:   func(v, locale string) string { return PainIntensity(v).Label(locale) },
		options: PainIntensityOptions,
	},
	"PeriodEndSource": {
		values: PeriodEndSourceValues,
	},
	"PeriodStartSource": {
		values: PeriodStartSourceValues,
	},
	"PreExistingCondition": {
		values:  PreExistingConditionValues,
		label:   func(v, locale string) string { return PreExistingCondition(v).Label(locale) },
		options: PreExistingConditionOptions,
	},
	"PregnancyAgeSource": {
		values:      PregnancyAgeSourceValues,
		label:       func(v, locale string) string { return PregnancyAgeSource(v).Label(locale) },
		description: func(v, locale string) string { return PregnancyAgeSource(v).Description(locale) },
		options:     PregnancyAgeSourceOptions,
	},
	"PregnancyIntention": {
		values:  PregnancyIntentionValues,
		label:   func(v, locale string) string { return PregnancyIntention(v).Label(locale) },
		options: PregnancyIntentionOptions,
	},
	"RecommendationTrigger": {
		values:  RecommendationTriggerValues,
		label:   func(v, locale string) string { return RecommendationTrigger(v).Label(locale) },
		options: RecommendationTriggerOptions,
	},
	"RecommendationType": {
		values:  RecommendationTypeValues,
		label:   func(v, locale string) string { return RecommendationType(v).Label(locale) },
		icon:    func(v string) string { return RecommendationType(v).Icon() },
		options: RecommendationTypeOptions,
	},
	"RegularityStatus": {
		values:  RegularityStatusValues,
		label:   func(v, locale string) string { return RegularityStatus(v).Label(locale) },
		options: RegularityStatusOptions,
	},
	"ReminderType": {
		values:  ReminderTypeValues,
		label:   func(v, locale string) string { return ReminderType(v).Label(locale) },
		icon:    func(v string) string { return ReminderType(v).Icon() },
		options: ReminderTypeOptions,
	},
	"ResolutionSource": {
		values: ResolutionSourceValues,
	},
	"RhFactor": {
		values:  RhFactorValues,
		label:   func(v, locale string) string { return RhFactor(v).Label(locale) },
		options: RhFactorOptions,
	},
	"SexualActivity": {
		values:  SexualActivityValues,
		label:   func(v, locale string) string { return SexualActivity(v).Label(locale) },
		options: SexualActivityOptions,
	},
	"SexualDesire": {
		values:  SexualDesireValues,
		label:   func(v, locale string) string { return SexualDesire(v).Label(locale) },
		options: SexualDesireOptions,
	},
	"SleepDuration": {
		values:  SleepDurationValues,
		label:   func(v, locale string) string { return SleepDuration(v).Label(locale) },
		options: SleepDurationOptions,
	},
	"SleepQuality": {
		values:  SleepQualityValues,
		label:   func(v, locale string) string { return SleepQuality(v).Label(locale) },
		options: SleepQualityOptions,
	},
	"Smell": {
		values:  SmellValues,
		label:   func(v, locale string) string { return Smell(v).Label(locale) },
		options: SmellOptions,
	},
	"SubscriptionType": {
		values:  SubscriptionTypeValues,
		label:   func(v, locale string) string { return SubscriptionType(v).Label(locale) },
		options: SubscriptionTypeOptions,
	},
	"SwellingLocation": {
		values:  SwellingLocationValues,
		label:   func(v, locale string) string { return SwellingLocation(v).Label(locale) },
		options: SwellingLocationOptions,
	},
	"SymptomSeverity": {
		values:  SymptomSeverityValues,
		label:   func(v, locale string) string { return SymptomSeverity(v).Label(locale) },
		options: SymptomSeverityOptions,
	},
	"TaskCategory": {
		values:  TaskCategoryValues,
		label:   func(v, locale string) string { return TaskCategory(v).Label(locale) },
		icon:    func(v string) string { return TaskCategory(v).Icon() },
		options: TaskCategoryOptions,
	},
	"TextDirection": {
		values:  TextDirectionValues,
		label:   func(v, locale string) string { return TextDirection(v).Label(locale) },
		options: TextDirectionOptions,
	},
	"UserGoal": {
		values:  UserGoalValues,
		label:   func(v, locale string) string { return UserGoal(v).Label(locale) },
		options: UserGoalOptions,
	},
	"MessageMode": {
		values:  MessageModeValues,
		label:   func(v, locale string) string { return MessageMode(v).Label(locale) },
		options: MessageModeOptions,
	},
}
