// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engine.sql

package store

import (
	"context"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const anyRecommendationExists = `-- name: AnyRecommendationExists :one
SELECT EXISTS (SELECT 1 FROM ` + "`" + `recommendations` + "`" + `) AS present
`

// RecommendationRepository::hasContent(): Recommendation::query()->exists() (inactive rows count).
func (q *Queries) AnyRecommendationExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, anyRecommendationExists)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const getEngineProfileByUserID = `-- name: GetEngineProfileByUserID :one
SELECT p.id, p.user_id, p.birthday, p.weight, p.height, p.period_duration, p.cycle_duration, p.last_period_start, p.user_goal, p.pregnancy_intention, p.chronic_conditions, p.subscription_type, p.calculation_status, p.calculation_started_at, p.calculation_completed_at, p.calculation_version, p.created_at, p.updated_at, COALESCE(cp.lengths_auto, 1) AS lengths_auto
FROM ` + "`" + `user_profiles` + "`" + ` p
LEFT JOIN ` + "`" + `cycle_preferences` + "`" + ` cp ON cp.user_id = p.user_id
WHERE p.user_id = ?
ORDER BY p.id
LIMIT 1
`

type GetEngineProfileByUserIDRow struct {
	UserProfile UserProfile
	LengthsAuto bool
}

// GetProfileByUserID plus B-N1-09 «خودکار از داده‌ها» (goose 00013) in the same round trip: no
// cycle_preferences row = automatic (1); 0 = the engine prefers the profile lengths.
func (q *Queries) GetEngineProfileByUserID(ctx context.Context, userID uint64) (GetEngineProfileByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEngineProfileByUserID, userID)
	var i GetEngineProfileByUserIDRow
	err := row.Scan(
		&i.UserProfile.ID,
		&i.UserProfile.UserID,
		&i.UserProfile.Birthday,
		&i.UserProfile.Weight,
		&i.UserProfile.Height,
		&i.UserProfile.PeriodDuration,
		&i.UserProfile.CycleDuration,
		&i.UserProfile.LastPeriodStart,
		&i.UserProfile.UserGoal,
		&i.UserProfile.PregnancyIntention,
		&i.UserProfile.ChronicConditions,
		&i.UserProfile.SubscriptionType,
		&i.UserProfile.CalculationStatus,
		&i.UserProfile.CalculationStartedAt,
		&i.UserProfile.CalculationCompletedAt,
		&i.UserProfile.CalculationVersion,
		&i.UserProfile.CreatedAt,
		&i.UserProfile.UpdatedAt,
		&i.LengthsAuto,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one

SELECT id, user_id, birthday, weight, height, period_duration, cycle_duration, last_period_start, user_goal, pregnancy_intention, chronic_conditions, subscription_type, calculation_status, calculation_started_at, calculation_completed_at, calculation_version, created_at, updated_at FROM ` + "`" + `user_profiles` + "`" + ` WHERE user_id = ? ORDER BY id LIMIT 1
`

// Inputs of the cycle engines (CycleCalculationController, HealthDataEngine, CycleEngineCache,
// RecommendationRepository). One query per input per request.
// $user->profile (hasOne without ordering: the lowest id on MariaDB).
func (q *Queries) GetProfileByUserID(ctx context.Context, userID uint64) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Birthday,
		&i.Weight,
		&i.Height,
		&i.PeriodDuration,
		&i.CycleDuration,
		&i.LastPeriodStart,
		&i.UserGoal,
		&i.PregnancyIntention,
		&i.ChronicConditions,
		&i.SubscriptionType,
		&i.CalculationStatus,
		&i.CalculationStartedAt,
		&i.CalculationCompletedAt,
		&i.CalculationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRecommendations = `-- name: ListActiveRecommendations :many
SELECT id, ` + "`" + `key` + "`" + `, type, title, text, cycle_phase, cycle_subphases, symptom_trigger, is_active, sort_order, created_at, updated_at FROM ` + "`" + `recommendations` + "`" + ` WHERE is_active = 1 ORDER BY sort_order, id
`

// RecommendationRepository::rows(): Recommendation::active()->orderBy('sort_order')->orderBy('id').
func (q *Queries) ListActiveRecommendations(ctx context.Context) ([]Recommendation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRecommendations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recommendation{}
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Type,
			&i.Title,
			&i.Text,
			&i.CyclePhase,
			&i.CycleSubphases,
			&i.SymptomTrigger,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCycleHistoriesNewestFirst = `-- name: ListCycleHistoriesNewestFirst :many
SELECT id, user_id, period_start_date, period_end_date, cycle_length, bleeding_length, is_confirmed, is_estimated, source, data_quality_flags, created_at, updated_at FROM ` + "`" + `cycle_histories` + "`" + ` WHERE user_id = ? ORDER BY period_start_date DESC
`

// HealthDataEngine::getCycleHistories: CycleHistory::where('user_id')->orderBy('period_start_date', 'desc').
func (q *Queries) ListCycleHistoriesNewestFirst(ctx context.Context, userID uint64) ([]CycleHistory, error) {
	rows, err := q.db.QueryContext(ctx, listCycleHistoriesNewestFirst, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CycleHistory{}
	for rows.Next() {
		var i CycleHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStartDate,
			&i.PeriodEndDate,
			&i.CycleLength,
			&i.BleedingLength,
			&i.IsConfirmed,
			&i.IsEstimated,
			&i.Source,
			&i.DataQualityFlags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLogsBetween = `-- name: ListDailyLogsBetween :many
SELECT id, user_id, log_date, bleeding_intensity, blood_color, has_clots, clots_amount, spotting, bleeding_smell, headache_intensity, stomach_ache_intensity, pelvic_pain_intensity, breast_pain_intensity, back_pain_intensity, ovarian_pain_intensity, nausea_intensity, bloating_intensity, diarrhea, constipation, appetite_change, food_craving, breast_sensitivity_intensity, vaginal_dryness, vaginal_burning, vaginal_burning_intensity, vaginal_itching, vaginal_itching_intensity, vaginal_smell_change, urination_change, urination_burning_intensity, acne, oily_skin, hair_loss, swelling, fatigue, dizziness, hot_flashes, chills, moods, sleep_duration, sleep_quality, exercise_type, exercise_duration, exercise_intensity, sexual_activities, sexual_desire, intercourse_type, weight, basal_body_temperature, heart_rate, systolic_pressure, diastolic_pressure, blood_sugar, energy_level, discharge_color, discharge_texture, discharge_amount, discharge_smell, discharge_itching, discharge_burning, frequent_urination, medications, notes, created_at, updated_at FROM ` + "`" + `daily_health_logs` + "`" + `
WHERE user_id = ? AND log_date BETWEEN ? AND ?
ORDER BY log_date
`

type ListDailyLogsBetweenParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

// HealthDataEngine::preloadDailyLogs: whereBetween('log_date', [from, to 23:59:59]) on a DATE column.
func (q *Queries) ListDailyLogsBetween(ctx context.Context, arg ListDailyLogsBetweenParams) ([]DailyHealthLog, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLogsBetween, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyHealthLog{}
	for rows.Next() {
		var i DailyHealthLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.BleedingIntensity,
			&i.BloodColor,
			&i.HasClots,
			&i.ClotsAmount,
			&i.Spotting,
			&i.BleedingSmell,
			&i.HeadacheIntensity,
			&i.StomachAcheIntensity,
			&i.PelvicPainIntensity,
			&i.BreastPainIntensity,
			&i.BackPainIntensity,
			&i.OvarianPainIntensity,
			&i.NauseaIntensity,
			&i.BloatingIntensity,
			&i.Diarrhea,
			&i.Constipation,
			&i.AppetiteChange,
			&i.FoodCraving,
			&i.BreastSensitivityIntensity,
			&i.VaginalDryness,
			&i.VaginalBurning,
			&i.VaginalBurningIntensity,
			&i.VaginalItching,
			&i.VaginalItchingIntensity,
			&i.VaginalSmellChange,
			&i.UrinationChange,
			&i.UrinationBurningIntensity,
			&i.Acne,
			&i.OilySkin,
			&i.HairLoss,
			&i.Swelling,
			&i.Fatigue,
			&i.Dizziness,
			&i.HotFlashes,
			&i.Chills,
			&i.Moods,
			&i.SleepDuration,
			&i.SleepQuality,
			&i.ExerciseType,
			&i.ExerciseDuration,
			&i.ExerciseIntensity,
			&i.SexualActivities,
			&i.SexualDesire,
			&i.IntercourseType,
			&i.Weight,
			&i.BasalBodyTemperature,
			&i.HeartRate,
			&i.SystolicPressure,
			&i.DiastolicPressure,
			&i.BloodSugar,
			&i.EnergyLevel,
			&i.DischargeColor,
			&i.DischargeTexture,
			&i.DischargeAmount,
			&i.DischargeSmell,
			&i.DischargeItching,
			&i.DischargeBurning,
			&i.FrequentUrination,
			&i.Medications,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
