// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const approveLearningInstructor = `-- name: ApproveLearningInstructor :exec
UPDATE ` + "`" + `learning_instructors` + "`" + `
SET status = 'approved', approved_at = ?, approved_by = ?, revoked_at = NULL,
    updated_at = ?
WHERE id = ?
`

type ApproveLearningInstructorParams struct {
	Now     sql.NullTime
	AdminID sql.NullInt64
	ID      uint64
}

func (q *Queries) ApproveLearningInstructor(ctx context.Context, arg ApproveLearningInstructorParams) error {
	_, err := q.db.ExecContext(ctx, approveLearningInstructor,
		arg.Now,
		arg.AdminID,
		arg.Now,
		arg.ID,
	)
	return err
}

const countLearningActiveStudents = `-- name: CountLearningActiveStudents :one
SELECT COUNT(DISTINCT user_id) FROM ` + "`" + `learning_progress` + "`" + ` WHERE last_seen_at >= ?
`

// Distinct students who opened a lesson since `since` (activity, not access).
func (q *Queries) CountLearningActiveStudents(ctx context.Context, since sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningActiveStudents, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningCompletedLessons = `-- name: CountLearningCompletedLessons :one
SELECT COUNT(*) FROM ` + "`" + `learning_progress` + "`" + ` WHERE completed_at IS NOT NULL
`

func (q *Queries) CountLearningCompletedLessons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningCompletedLessons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningCourseGrants = `-- name: CountLearningCourseGrants :many
SELECT
  CASE WHEN a.status = 'active' AND a.expires_at IS NOT NULL AND a.expires_at <= ? THEN 'expired'
       ELSE a.status END AS state,
  COUNT(*) AS total
FROM ` + "`" + `learning_grants` + "`" + ` a
WHERE a.course_id = ?
   OR a.group_id IN (SELECT gc.group_id FROM ` + "`" + `learning_group_courses` + "`" + ` gc WHERE gc.course_id = ?)
GROUP BY state
`

type CountLearningCourseGrantsParams struct {
	Now            sql.NullTime
	DirectCourseID sql.NullInt64
	CourseID       uint64
}

type CountLearningCourseGrantsRow struct {
	State interface{}
	Total int64
}

// A course's grants by stored status (direct or through a group that opens it); expired = active past expires_at.
func (q *Queries) CountLearningCourseGrants(ctx context.Context, arg CountLearningCourseGrantsParams) ([]CountLearningCourseGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningCourseGrants, arg.Now, arg.DirectCourseID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningCourseGrantsRow{}
	for rows.Next() {
		var i CountLearningCourseGrantsRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningCourses = `-- name: CountLearningCourses :one

SELECT COUNT(*) FROM ` + "`" + `learning_courses` + "`" + ` c
WHERE c.status LIKE ?
  AND (? = 0 OR c.instructor_id = ?)
  AND (? = '' OR c.title LIKE CAST(? AS CHAR))
`

type CountLearningCoursesParams struct {
	Status       string
	InstructorID uint64
	Q            interface{}
	QLike        interface{}
}

// ───────────── courses ─────────────
func (q *Queries) CountLearningCourses(ctx context.Context, arg CountLearningCoursesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningCourses,
		arg.Status,
		arg.InstructorID,
		arg.InstructorID,
		arg.Q,
		arg.QLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningCoursesByStatus = `-- name: CountLearningCoursesByStatus :many
SELECT ` + "`" + `status` + "`" + `, COUNT(*) AS total FROM ` + "`" + `learning_courses` + "`" + ` GROUP BY ` + "`" + `status` + "`" + `
`

type CountLearningCoursesByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountLearningCoursesByStatus(ctx context.Context) ([]CountLearningCoursesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningCoursesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningCoursesByStatusRow{}
	for rows.Next() {
		var i CountLearningCoursesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningGrantsByState = `-- name: CountLearningGrantsByState :many
SELECT
  CASE WHEN status = 'active' AND expires_at IS NOT NULL AND expires_at <= ? THEN 'expired'
       ELSE status END AS state,
  COUNT(*) AS total
FROM ` + "`" + `learning_grants` + "`" + `
GROUP BY state
`

type CountLearningGrantsByStateRow struct {
	State interface{}
	Total int64
}

func (q *Queries) CountLearningGrantsByState(ctx context.Context, now sql.NullTime) ([]CountLearningGrantsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningGrantsByState, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningGrantsByStateRow{}
	for rows.Next() {
		var i CountLearningGrantsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningGrantsSince = `-- name: CountLearningGrantsSince :one
SELECT COUNT(*) FROM ` + "`" + `learning_grants` + "`" + ` WHERE created_at >= ?
`

func (q *Queries) CountLearningGrantsSince(ctx context.Context, since sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningGrantsSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningInstructors = `-- name: CountLearningInstructors :one


SELECT COUNT(*) FROM ` + "`" + `learning_instructors` + "`" + ` i
JOIN ` + "`" + `users` + "`" + ` u ON u.id = i.user_id
WHERE i.status LIKE ?
  AND (? = '' OR i.display_name LIKE CAST(? AS CHAR) OR IFNULL(u.name, '') LIKE CAST(? AS CHAR)
       OR IFNULL(u.mobile, '') LIKE CAST(? AS CHAR))
`

type CountLearningInstructorsParams struct {
	Status string
	Q      interface{}
	QLike  interface{}
}

// Admin moderation of courses «مدرسین و دوره‌ها» (bloom B-N8-08; internal/admin/learning, admin-api.md §20).
// Read-mostly over the B-N8-01 tables (00046) plus the review state and moderation log of 00054. Filters are LIKE
// patterns ('%' = all) like the other admin lists. No health data: courses are instructor content, progress is only
// aggregated (percent per student × course), phone numbers are never selected here.
// ───────────── instructors ─────────────
func (q *Queries) CountLearningInstructors(ctx context.Context, arg CountLearningInstructorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningInstructors,
		arg.Status,
		arg.Q,
		arg.QLike,
		arg.QLike,
		arg.QLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLearningInstructorsByStatus = `-- name: CountLearningInstructorsByStatus :many
SELECT ` + "`" + `status` + "`" + `, COUNT(*) AS total FROM ` + "`" + `learning_instructors` + "`" + ` GROUP BY ` + "`" + `status` + "`" + `
`

type CountLearningInstructorsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountLearningInstructorsByStatus(ctx context.Context) ([]CountLearningInstructorsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningInstructorsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningInstructorsByStatusRow{}
	for rows.Next() {
		var i CountLearningInstructorsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningLessons = `-- name: CountLearningLessons :one
SELECT COUNT(*) AS total, CAST(IFNULL(SUM(status = 'published'), 0) AS SIGNED) AS published FROM ` + "`" + `learning_lessons` + "`" + `
`

type CountLearningLessonsRow struct {
	Total     int64
	Published int64
}

func (q *Queries) CountLearningLessons(ctx context.Context) (CountLearningLessonsRow, error) {
	row := q.db.QueryRowContext(ctx, countLearningLessons)
	var i CountLearningLessonsRow
	err := row.Scan(&i.Total, &i.Published)
	return i, err
}

const countLearningLessonsByState = `-- name: CountLearningLessonsByState :many
SELECT
  CASE WHEN review_status = 'flagged' THEN 'flagged'
       WHEN review_status = 'pending' THEN 'pending'
       WHEN reviewed_at IS NULL OR updated_at > reviewed_at THEN 'changed'
       ELSE 'approved' END AS state,
  COUNT(*) AS total
FROM ` + "`" + `learning_lessons` + "`" + `
WHERE status = 'published' OR review_status = 'flagged'
GROUP BY state
`

type CountLearningLessonsByStateRow struct {
	State string
	Total int64
}

// Review queue counts over published lessons + flagged ones (an unpublished lesson stays flagged).
func (q *Queries) CountLearningLessonsByState(ctx context.Context) ([]CountLearningLessonsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningLessonsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningLessonsByStateRow{}
	for rows.Next() {
		var i CountLearningLessonsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningPublishedLessons = `-- name: CountLearningPublishedLessons :many
SELECT course_id, COUNT(*) AS total FROM ` + "`" + `learning_lessons` + "`" + ` WHERE status = 'published' GROUP BY course_id
`

type CountLearningPublishedLessonsRow struct {
	CourseID uint64
	Total    int64
}

func (q *Queries) CountLearningPublishedLessons(ctx context.Context) ([]CountLearningPublishedLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, countLearningPublishedLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLearningPublishedLessonsRow{}
	for rows.Next() {
		var i CountLearningPublishedLessonsRow
		if err := rows.Scan(&i.CourseID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLearningReviewQueue = `-- name: CountLearningReviewQueue :one

SELECT COUNT(*) FROM ` + "`" + `learning_lessons` + "`" + ` l
WHERE (l.status = 'published' OR l.review_status = 'flagged')
  AND (
    (? AND l.review_status = 'flagged')
    OR (? AND l.review_status = 'pending')
    OR (? AND l.review_status = 'approved' AND (l.reviewed_at IS NULL OR l.updated_at > l.reviewed_at))
    OR (? AND l.review_status = 'approved' AND l.reviewed_at IS NOT NULL
        AND (l.updated_at IS NULL OR l.updated_at <= l.reviewed_at))
  )
`

type CountLearningReviewQueueParams struct {
	WantFlagged  interface{}
	WantPending  interface{}
	WantChanged  interface{}
	WantApproved interface{}
}

// ───────────── review queue ─────────────
func (q *Queries) CountLearningReviewQueue(ctx context.Context, arg CountLearningReviewQueueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLearningReviewQueue,
		arg.WantFlagged,
		arg.WantPending,
		arg.WantChanged,
		arg.WantApproved,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLearningCourse = `-- name: GetLearningCourse :one
SELECT c.id, c.instructor_id, c.kind, c.title, c.description, c.status, c.published_at, c.created_at, c.updated_at,
  i.display_name AS instructor_name, i.title AS instructor_title, i.status AS instructor_status
FROM ` + "`" + `learning_courses` + "`" + ` c
JOIN ` + "`" + `learning_instructors` + "`" + ` i ON i.id = c.instructor_id
WHERE c.id = ? LIMIT 1
`

type GetLearningCourseRow struct {
	ID               uint64
	InstructorID     uint64
	Kind             string
	Title            string
	Description      sql.NullString
	Status           string
	PublishedAt      sql.NullTime
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	InstructorName   string
	InstructorTitle  sql.NullString
	InstructorStatus string
}

func (q *Queries) GetLearningCourse(ctx context.Context, id uint64) (GetLearningCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningCourse, id)
	var i GetLearningCourseRow
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstructorName,
		&i.InstructorTitle,
		&i.InstructorStatus,
	)
	return i, err
}

const getLearningInstructorAdmin = `-- name: GetLearningInstructorAdmin :one
SELECT i.id, i.user_id, i.display_name, i.title, i.bio, i.status, i.approved_at, i.approved_by, i.revoked_at,
  i.created_at, i.updated_at, u.name AS user_name, u.mobile AS user_mobile, ad.name AS approved_by_name,
  (SELECT COUNT(*) FROM ` + "`" + `learning_courses` + "`" + ` c WHERE c.instructor_id = i.id) AS courses_count,
  (SELECT COUNT(*) FROM ` + "`" + `learning_courses` + "`" + ` c WHERE c.instructor_id = i.id AND c.status = 'published') AS published_courses,
  (SELECT COUNT(DISTINCT a.user_id) FROM ` + "`" + `learning_grants` + "`" + ` a
    WHERE a.instructor_id = i.id AND a.status = 'active' AND a.user_id IS NOT NULL
      AND (a.expires_at IS NULL OR a.expires_at > ?)) AS students_count
FROM ` + "`" + `learning_instructors` + "`" + ` i
JOIN ` + "`" + `users` + "`" + ` u ON u.id = i.user_id
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = i.approved_by
WHERE i.id = ? LIMIT 1
`

type GetLearningInstructorAdminParams struct {
	Now sql.NullTime
	ID  uint64
}

type GetLearningInstructorAdminRow struct {
	ID               uint64
	UserID           uint64
	DisplayName      string
	Title            sql.NullString
	Bio              sql.NullString
	Status           string
	ApprovedAt       sql.NullTime
	ApprovedBy       sql.NullInt64
	RevokedAt        sql.NullTime
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	UserName         sql.NullString
	UserMobile       sql.NullString
	ApprovedByName   sql.NullString
	CoursesCount     int64
	PublishedCourses int64
	StudentsCount    int64
}

func (q *Queries) GetLearningInstructorAdmin(ctx context.Context, arg GetLearningInstructorAdminParams) (GetLearningInstructorAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningInstructorAdmin, arg.Now, arg.ID)
	var i GetLearningInstructorAdminRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Title,
		&i.Bio,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserMobile,
		&i.ApprovedByName,
		&i.CoursesCount,
		&i.PublishedCourses,
		&i.StudentsCount,
	)
	return i, err
}

const getLearningInstructorForUpdate = `-- name: GetLearningInstructorForUpdate :one
SELECT id, status FROM ` + "`" + `learning_instructors` + "`" + ` WHERE id = ? LIMIT 1 FOR UPDATE
`

type GetLearningInstructorForUpdateRow struct {
	ID     uint64
	Status string
}

func (q *Queries) GetLearningInstructorForUpdate(ctx context.Context, id uint64) (GetLearningInstructorForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningInstructorForUpdate, id)
	var i GetLearningInstructorForUpdateRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLearningLessonForUpdate = `-- name: GetLearningLessonForUpdate :one
SELECT l.id, l.course_id, l.status, c.instructor_id FROM ` + "`" + `learning_lessons` + "`" + ` l
JOIN ` + "`" + `learning_courses` + "`" + ` c ON c.id = l.course_id
WHERE l.id = ? LIMIT 1 FOR UPDATE
`

type GetLearningLessonForUpdateRow struct {
	ID           uint64
	CourseID     uint64
	Status       string
	InstructorID uint64
}

func (q *Queries) GetLearningLessonForUpdate(ctx context.Context, id uint64) (GetLearningLessonForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningLessonForUpdate, id)
	var i GetLearningLessonForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Status,
		&i.InstructorID,
	)
	return i, err
}

const getLearningReviewLesson = `-- name: GetLearningReviewLesson :one
SELECT l.id, l.course_id, l.chapter_id, l.kind, l.title, l.description, l.duration_seconds, l.page_count,
  l.size_bytes, l.media_status, l.status, l.published_at, l.review_status, l.reviewed_at, l.reviewed_by,
  l.review_note, l.created_at, l.updated_at,
  c.title AS course_title, c.kind AS course_kind, c.status AS course_status,
  i.id AS instructor_id, i.display_name AS instructor_name, i.status AS instructor_status,
  ad.name AS reviewed_by_name
FROM ` + "`" + `learning_lessons` + "`" + ` l
JOIN ` + "`" + `learning_courses` + "`" + ` c ON c.id = l.course_id
JOIN ` + "`" + `learning_instructors` + "`" + ` i ON i.id = c.instructor_id
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = l.reviewed_by
WHERE l.id = ? LIMIT 1
`

type GetLearningReviewLessonRow struct {
	ID               uint64
	CourseID         uint64
	ChapterID        sql.NullInt64
	Kind             string
	Title            string
	Description      sql.NullString
	DurationSeconds  sql.NullInt32
	PageCount        sql.NullInt16
	SizeBytes        sql.NullInt64
	MediaStatus      string
	Status           string
	PublishedAt      sql.NullTime
	ReviewStatus     string
	ReviewedAt       sql.NullTime
	ReviewedBy       sql.NullInt64
	ReviewNote       sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	CourseTitle      string
	CourseKind       string
	CourseStatus     string
	InstructorID     uint64
	InstructorName   string
	InstructorStatus string
	ReviewedByName   sql.NullString
}

func (q *Queries) GetLearningReviewLesson(ctx context.Context, id uint64) (GetLearningReviewLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getLearningReviewLesson, id)
	var i GetLearningReviewLessonRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ChapterID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.DurationSeconds,
		&i.PageCount,
		&i.SizeBytes,
		&i.MediaStatus,
		&i.Status,
		&i.PublishedAt,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseTitle,
		&i.CourseKind,
		&i.CourseStatus,
		&i.InstructorID,
		&i.InstructorName,
		&i.InstructorStatus,
		&i.ReviewedByName,
	)
	return i, err
}

const insertLearningModeration = `-- name: InsertLearningModeration :exec

INSERT INTO ` + "`" + `learning_moderation_log` + "`" + ` (admin_id, action, target_type, target_id, instructor_id, note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?, ?)
`

type InsertLearningModerationParams struct {
	AdminID      sql.NullInt64
	Action       string
	TargetType   string
	TargetID     uint64
	InstructorID sql.NullInt64
	Note         sql.NullString
	Now          sql.NullTime
}

// ───────────── moderation log ─────────────
func (q *Queries) InsertLearningModeration(ctx context.Context, arg InsertLearningModerationParams) error {
	_, err := q.db.ExecContext(ctx, insertLearningModeration,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.InstructorID,
		arg.Note,
		arg.Now,
		arg.Now,
	)
	return err
}

const listLearningAccessPairs = `-- name: ListLearningAccessPairs :many

SELECT DISTINCT c.id AS course_id, a.user_id
FROM ` + "`" + `learning_grants` + "`" + ` a
JOIN ` + "`" + `learning_courses` + "`" + ` c ON c.instructor_id = a.instructor_id AND (
  c.id = a.course_id
  OR c.id IN (SELECT gc.course_id FROM ` + "`" + `learning_group_courses` + "`" + ` gc WHERE gc.group_id = a.group_id)
)
WHERE a.status = 'active' AND a.user_id IS NOT NULL AND (a.expires_at IS NULL OR a.expires_at > ?)
  AND c.id IN (/*SLICE:course_ids*/?)
`

type ListLearningAccessPairsParams struct {
	Now       sql.NullTime
	CourseIds []uint64
}

type ListLearningAccessPairsRow struct {
	CourseID uint64
	UserID   sql.NullInt64
}

// ───────────── usage aggregates (completion) ─────────────
// (course, student) pairs with a running grant for the given courses: the denominator of «completion».
func (q *Queries) ListLearningAccessPairs(ctx context.Context, arg ListLearningAccessPairsParams) ([]ListLearningAccessPairsRow, error) {
	query := listLearningAccessPairs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Now)
	if len(arg.CourseIds) > 0 {
		for _, v := range arg.CourseIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:course_ids*/?", strings.Repeat(",?", len(arg.CourseIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:course_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningAccessPairsRow{}
	for rows.Next() {
		var i ListLearningAccessPairsRow
		if err := rows.Scan(&i.CourseID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningAllAccessPairs = `-- name: ListLearningAllAccessPairs :many
SELECT DISTINCT c.id AS course_id, a.user_id
FROM ` + "`" + `learning_grants` + "`" + ` a
JOIN ` + "`" + `learning_courses` + "`" + ` c ON c.instructor_id = a.instructor_id AND (
  c.id = a.course_id
  OR c.id IN (SELECT gc.course_id FROM ` + "`" + `learning_group_courses` + "`" + ` gc WHERE gc.group_id = a.group_id)
)
WHERE a.status = 'active' AND a.user_id IS NOT NULL AND (a.expires_at IS NULL OR a.expires_at > ?)
`

type ListLearningAllAccessPairsRow struct {
	CourseID uint64
	UserID   sql.NullInt64
}

func (q *Queries) ListLearningAllAccessPairs(ctx context.Context, now sql.NullTime) ([]ListLearningAllAccessPairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningAllAccessPairs, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningAllAccessPairsRow{}
	for rows.Next() {
		var i ListLearningAllAccessPairsRow
		if err := rows.Scan(&i.CourseID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningCourseChapters = `-- name: ListLearningCourseChapters :many
SELECT id, title, sort_order, unlock_at FROM ` + "`" + `learning_chapters` + "`" + ` WHERE course_id = ?
ORDER BY sort_order, id
`

type ListLearningCourseChaptersRow struct {
	ID        uint64
	Title     string
	SortOrder uint16
	UnlockAt  sql.NullTime
}

func (q *Queries) ListLearningCourseChapters(ctx context.Context, courseID uint64) ([]ListLearningCourseChaptersRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningCourseChapters, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningCourseChaptersRow{}
	for rows.Next() {
		var i ListLearningCourseChaptersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortOrder,
			&i.UnlockAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningCourseLessons = `-- name: ListLearningCourseLessons :many
SELECT l.id, l.chapter_id, l.kind, l.title, l.description, l.duration_seconds, l.page_count, l.size_bytes,
  l.media_status, l.status, l.published_at, l.review_status, l.reviewed_at, l.reviewed_by, l.review_note,
  l.sort_order, l.created_at, l.updated_at, ad.name AS reviewed_by_name
FROM ` + "`" + `learning_lessons` + "`" + ` l
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = l.reviewed_by
WHERE l.course_id = ?
ORDER BY l.sort_order, l.id
`

type ListLearningCourseLessonsRow struct {
	ID              uint64
	ChapterID       sql.NullInt64
	Kind            string
	Title           string
	Description     sql.NullString
	DurationSeconds sql.NullInt32
	PageCount       sql.NullInt16
	SizeBytes       sql.NullInt64
	MediaStatus     string
	Status          string
	PublishedAt     sql.NullTime
	ReviewStatus    string
	ReviewedAt      sql.NullTime
	ReviewedBy      sql.NullInt64
	ReviewNote      sql.NullString
	SortOrder       uint16
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	ReviewedByName  sql.NullString
}

func (q *Queries) ListLearningCourseLessons(ctx context.Context, courseID uint64) ([]ListLearningCourseLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningCourseLessons, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningCourseLessonsRow{}
	for rows.Next() {
		var i ListLearningCourseLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.DurationSeconds,
			&i.PageCount,
			&i.SizeBytes,
			&i.MediaStatus,
			&i.Status,
			&i.PublishedAt,
			&i.ReviewStatus,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningCourses = `-- name: ListLearningCourses :many
SELECT c.id, c.instructor_id, c.kind, c.title, c.status, c.published_at, c.created_at, c.updated_at,
  i.display_name AS instructor_name, i.status AS instructor_status,
  (SELECT COUNT(*) FROM ` + "`" + `learning_chapters` + "`" + ` ch WHERE ch.course_id = c.id) AS chapters_count,
  (SELECT COUNT(*) FROM ` + "`" + `learning_lessons` + "`" + ` l WHERE l.course_id = c.id) AS lessons_count,
  (SELECT COUNT(*) FROM ` + "`" + `learning_lessons` + "`" + ` l WHERE l.course_id = c.id AND l.status = 'published') AS published_lessons,
  (SELECT COUNT(*) FROM ` + "`" + `learning_lessons` + "`" + ` l WHERE l.course_id = c.id AND l.status = 'published'
     AND (l.review_status IN ('pending', 'flagged') OR l.reviewed_at IS NULL OR l.updated_at > l.reviewed_at)) AS review_open,
  (SELECT COUNT(*) FROM ` + "`" + `learning_lessons` + "`" + ` l WHERE l.course_id = c.id AND l.review_status = 'flagged') AS flagged_count
FROM ` + "`" + `learning_courses` + "`" + ` c
JOIN ` + "`" + `learning_instructors` + "`" + ` i ON i.id = c.instructor_id
WHERE c.status LIKE ?
  AND (? = 0 OR c.instructor_id = ?)
  AND (? = '' OR c.title LIKE CAST(? AS CHAR))
ORDER BY c.created_at DESC, c.id DESC
LIMIT ? OFFSET ?
`

type ListLearningCoursesParams struct {
	Status       string
	InstructorID uint64
	Q            interface{}
	QLike        interface{}
	Limit        int32
	Offset       int32
}

type ListLearningCoursesRow struct {
	ID               uint64
	InstructorID     uint64
	Kind             string
	Title            string
	Status           string
	PublishedAt      sql.NullTime
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	InstructorName   string
	InstructorStatus string
	ChaptersCount    int64
	LessonsCount     int64
	PublishedLessons int64
	ReviewOpen       int64
	FlaggedCount     int64
}

func (q *Queries) ListLearningCourses(ctx context.Context, arg ListLearningCoursesParams) ([]ListLearningCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningCourses,
		arg.Status,
		arg.InstructorID,
		arg.InstructorID,
		arg.Q,
		arg.QLike,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningCoursesRow{}
	for rows.Next() {
		var i ListLearningCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Kind,
			&i.Title,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstructorName,
			&i.InstructorStatus,
			&i.ChaptersCount,
			&i.LessonsCount,
			&i.PublishedLessons,
			&i.ReviewOpen,
			&i.FlaggedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningInstructors = `-- name: ListLearningInstructors :many
SELECT i.id, i.user_id, i.display_name, i.title, i.bio, i.status, i.approved_at, i.approved_by, i.revoked_at,
  i.created_at, i.updated_at, u.name AS user_name, u.mobile AS user_mobile, ad.name AS approved_by_name,
  (SELECT COUNT(*) FROM ` + "`" + `learning_courses` + "`" + ` c WHERE c.instructor_id = i.id) AS courses_count,
  (SELECT COUNT(*) FROM ` + "`" + `learning_courses` + "`" + ` c WHERE c.instructor_id = i.id AND c.status = 'published') AS published_courses,
  (SELECT COUNT(DISTINCT a.user_id) FROM ` + "`" + `learning_grants` + "`" + ` a
    WHERE a.instructor_id = i.id AND a.status = 'active' AND a.user_id IS NOT NULL
      AND (a.expires_at IS NULL OR a.expires_at > ?)) AS students_count
FROM ` + "`" + `learning_instructors` + "`" + ` i
JOIN ` + "`" + `users` + "`" + ` u ON u.id = i.user_id
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = i.approved_by
WHERE i.status LIKE ?
  AND (? = '' OR i.display_name LIKE CAST(? AS CHAR) OR IFNULL(u.name, '') LIKE CAST(? AS CHAR)
       OR IFNULL(u.mobile, '') LIKE CAST(? AS CHAR))
ORDER BY (i.status = 'pending') DESC, i.created_at DESC, i.id DESC
LIMIT ? OFFSET ?
`

type ListLearningInstructorsParams struct {
	Now    sql.NullTime
	Status string
	Q      interface{}
	QLike  interface{}
	Limit  int32
	Offset int32
}

type ListLearningInstructorsRow struct {
	ID               uint64
	UserID           uint64
	DisplayName      string
	Title            sql.NullString
	Bio              sql.NullString
	Status           string
	ApprovedAt       sql.NullTime
	ApprovedBy       sql.NullInt64
	RevokedAt        sql.NullTime
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	UserName         sql.NullString
	UserMobile       sql.NullString
	ApprovedByName   sql.NullString
	CoursesCount     int64
	PublishedCourses int64
	StudentsCount    int64
}

// Pending applications first (what needs an answer), then newest.
func (q *Queries) ListLearningInstructors(ctx context.Context, arg ListLearningInstructorsParams) ([]ListLearningInstructorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningInstructors,
		arg.Now,
		arg.Status,
		arg.Q,
		arg.QLike,
		arg.QLike,
		arg.QLike,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningInstructorsRow{}
	for rows.Next() {
		var i ListLearningInstructorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Title,
			&i.Bio,
			&i.Status,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserMobile,
			&i.ApprovedByName,
			&i.CoursesCount,
			&i.PublishedCourses,
			&i.StudentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningModeration = `-- name: ListLearningModeration :many
SELECT m.id, m.admin_id, m.action, m.target_type, m.target_id, m.instructor_id, m.note, m.created_at,
  ad.name AS admin_name
FROM ` + "`" + `learning_moderation_log` + "`" + ` m
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = m.admin_id
WHERE (m.target_type = 'instructor' AND m.target_id = ?) OR m.instructor_id = ?
ORDER BY m.created_at DESC, m.id DESC
LIMIT 20
`

type ListLearningModerationParams struct {
	TargetID     uint64
	InstructorID sql.NullInt64
}

type ListLearningModerationRow struct {
	ID           uint64
	AdminID      sql.NullInt64
	Action       string
	TargetType   string
	TargetID     uint64
	InstructorID sql.NullInt64
	Note         sql.NullString
	CreatedAt    sql.NullTime
	AdminName    sql.NullString
}

func (q *Queries) ListLearningModeration(ctx context.Context, arg ListLearningModerationParams) ([]ListLearningModerationRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningModeration, arg.TargetID, arg.InstructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningModerationRow{}
	for rows.Next() {
		var i ListLearningModerationRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.InstructorID,
			&i.Note,
			&i.CreatedAt,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningReviewQueue = `-- name: ListLearningReviewQueue :many
SELECT l.id, l.course_id, l.chapter_id, l.kind, l.title, l.description, l.duration_seconds, l.page_count,
  l.size_bytes, l.media_status, l.status, l.published_at, l.review_status, l.reviewed_at, l.reviewed_by,
  l.review_note, l.created_at, l.updated_at,
  c.title AS course_title, c.kind AS course_kind, c.status AS course_status,
  i.id AS instructor_id, i.display_name AS instructor_name, i.status AS instructor_status,
  ad.name AS reviewed_by_name
FROM ` + "`" + `learning_lessons` + "`" + ` l
JOIN ` + "`" + `learning_courses` + "`" + ` c ON c.id = l.course_id
JOIN ` + "`" + `learning_instructors` + "`" + ` i ON i.id = c.instructor_id
LEFT JOIN ` + "`" + `admins` + "`" + ` ad ON ad.id = l.reviewed_by
WHERE (l.status = 'published' OR l.review_status = 'flagged')
  AND (
    (? AND l.review_status = 'flagged')
    OR (? AND l.review_status = 'pending')
    OR (? AND l.review_status = 'approved' AND (l.reviewed_at IS NULL OR l.updated_at > l.reviewed_at))
    OR (? AND l.review_status = 'approved' AND l.reviewed_at IS NOT NULL
        AND (l.updated_at IS NULL OR l.updated_at <= l.reviewed_at))
  )
ORDER BY
  CASE WHEN ? THEN l.updated_at END ASC,
  l.updated_at DESC,
  l.id
LIMIT ? OFFSET ?
`

type ListLearningReviewQueueParams struct {
	WantFlagged  interface{}
	WantPending  interface{}
	WantChanged  interface{}
	WantApproved interface{}
	OldestFirst  interface{}
	Limit        int32
	Offset       int32
}

type ListLearningReviewQueueRow struct {
	ID               uint64
	CourseID         uint64
	ChapterID        sql.NullInt64
	Kind             string
	Title            string
	Description      sql.NullString
	DurationSeconds  sql.NullInt32
	PageCount        sql.NullInt16
	SizeBytes        sql.NullInt64
	MediaStatus      string
	Status           string
	PublishedAt      sql.NullTime
	ReviewStatus     string
	ReviewedAt       sql.NullTime
	ReviewedBy       sql.NullInt64
	ReviewNote       sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	CourseTitle      string
	CourseKind       string
	CourseStatus     string
	InstructorID     uint64
	InstructorName   string
	InstructorStatus string
	ReviewedByName   sql.NullString
}

// Published lessons (and flagged ones, also after a takedown) in the given review states. Open states come oldest-change first (a queue), the rest newest first.
func (q *Queries) ListLearningReviewQueue(ctx context.Context, arg ListLearningReviewQueueParams) ([]ListLearningReviewQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, listLearningReviewQueue,
		arg.WantFlagged,
		arg.WantPending,
		arg.WantChanged,
		arg.WantApproved,
		arg.OldestFirst,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLearningReviewQueueRow{}
	for rows.Next() {
		var i ListLearningReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ChapterID,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.DurationSeconds,
			&i.PageCount,
			&i.SizeBytes,
			&i.MediaStatus,
			&i.Status,
			&i.PublishedAt,
			&i.ReviewStatus,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.CourseKind,
			&i.CourseStatus,
			&i.InstructorID,
			&i.InstructorName,
			&i.InstructorStatus,
			&i.ReviewedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewLearningLesson = `-- name: ReviewLearningLesson :exec
UPDATE ` + "`" + `learning_lessons` + "`" + `
SET review_status = ?, reviewed_at = ?, reviewed_by = ?,
    review_note = ?
WHERE id = ?
`

type ReviewLearningLessonParams struct {
	ReviewStatus string
	Now          sql.NullTime
	AdminID      sql.NullInt64
	Note         sql.NullString
	ID           uint64
}

// approve / flag: the review fields only — updated_at stays, so «changed since review» keeps meaning the instructor.
func (q *Queries) ReviewLearningLesson(ctx context.Context, arg ReviewLearningLessonParams) error {
	_, err := q.db.ExecContext(ctx, reviewLearningLesson,
		arg.ReviewStatus,
		arg.Now,
		arg.AdminID,
		arg.Note,
		arg.ID,
	)
	return err
}

const revokeLearningInstructor = `-- name: RevokeLearningInstructor :exec
UPDATE ` + "`" + `learning_instructors` + "`" + ` SET status = 'revoked', revoked_at = ?, updated_at = ?
WHERE id = ?
`

type RevokeLearningInstructorParams struct {
	Now sql.NullTime
	ID  uint64
}

func (q *Queries) RevokeLearningInstructor(ctx context.Context, arg RevokeLearningInstructorParams) error {
	_, err := q.db.ExecContext(ctx, revokeLearningInstructor, arg.Now, arg.Now, arg.ID)
	return err
}

const sumAllLearningProgress = `-- name: SumAllLearningProgress :many
SELECT p.course_id, p.user_id,
  CAST(SUM(CASE WHEN p.completed_at IS NOT NULL THEN 100 ELSE LEAST(p.percent, 100) END) AS SIGNED) AS percent_sum
FROM ` + "`" + `learning_progress` + "`" + ` p
JOIN ` + "`" + `learning_lessons` + "`" + ` l ON l.id = p.lesson_id AND l.status = 'published'
GROUP BY p.course_id, p.user_id
`

type SumAllLearningProgressRow struct {
	CourseID   uint64
	UserID     uint64
	PercentSum int64
}

func (q *Queries) SumAllLearningProgress(ctx context.Context) ([]SumAllLearningProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, sumAllLearningProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumAllLearningProgressRow{}
	for rows.Next() {
		var i SumAllLearningProgressRow
		if err := rows.Scan(&i.CourseID, &i.UserID, &i.PercentSum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLearningProgress = `-- name: SumLearningProgress :many
SELECT p.course_id, p.user_id,
  CAST(SUM(CASE WHEN p.completed_at IS NOT NULL THEN 100 ELSE LEAST(p.percent, 100) END) AS SIGNED) AS percent_sum
FROM ` + "`" + `learning_progress` + "`" + ` p
JOIN ` + "`" + `learning_lessons` + "`" + ` l ON l.id = p.lesson_id AND l.status = 'published'
WHERE p.course_id IN (/*SLICE:course_ids*/?)
GROUP BY p.course_id, p.user_id
`

type SumLearningProgressRow struct {
	CourseID   uint64
	UserID     uint64
	PercentSum int64
}

// Per (course, student): the summed effective percent over published lessons (a completed lesson counts 100).
func (q *Queries) SumLearningProgress(ctx context.Context, courseIds []uint64) ([]SumLearningProgressRow, error) {
	query := sumLearningProgress
	var queryParams []interface{}
	if len(courseIds) > 0 {
		for _, v := range courseIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:course_ids*/?", strings.Repeat(",?", len(courseIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:course_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumLearningProgressRow{}
	for rows.Next() {
		var i SumLearningProgressRow
		if err := rows.Scan(&i.CourseID, &i.UserID, &i.PercentSum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpublishLearningLesson = `-- name: UnpublishLearningLesson :exec
UPDATE ` + "`" + `learning_lessons` + "`" + `
SET status = 'draft', review_status = 'flagged', reviewed_at = ?, reviewed_by = ?,
    review_note = ?, updated_at = ?
WHERE id = ?
`

type UnpublishLearningLessonParams struct {
	Now     sql.NullTime
	AdminID sql.NullInt64
	Note    sql.NullString
	ID      uint64
}

// A takedown: back to draft (students stop seeing it at once) and flagged with the admin's reason.
func (q *Queries) UnpublishLearningLesson(ctx context.Context, arg UnpublishLearningLessonParams) error {
	_, err := q.db.ExecContext(ctx, unpublishLearningLesson,
		arg.Now,
		arg.AdminID,
		arg.Note,
		arg.Now,
		arg.ID,
	)
	return err
}
