// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plus.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/ritme/backend-go/db"
)

const adminCountPlusDiscounts = `-- name: AdminCountPlusDiscounts :one

SELECT COUNT(*) FROM plus_discount_codes d
WHERE d.code LIKE ?
  AND d.is_active >= ? AND d.is_active <= ?
`

type AdminCountPlusDiscountsParams struct {
	Pattern   string
	ActiveMin bool
	ActiveMax bool
}

// ---------------------------------------------------------------------------
// Discount codes
func (q *Queries) AdminCountPlusDiscounts(ctx context.Context, arg AdminCountPlusDiscountsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountPlusDiscounts, arg.Pattern, arg.ActiveMin, arg.ActiveMax)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountPlusInvoices = `-- name: AdminCountPlusInvoices :one

SELECT COUNT(*) FROM plus_invoices i
JOIN users u ON u.id = i.user_id
LEFT JOIN plus_receipts r ON r.invoice_id = i.id
WHERE i.status LIKE ?
  AND IFNULL(i.gateway, '') LIKE ?
  AND i.created_at >= ? AND i.created_at < ?
  AND (IFNULL(i.reference, '') LIKE ? OR IFNULL(r.ref_id, '') LIKE ? OR IFNULL(u.mobile, '') LIKE ?)
`

type AdminCountPlusInvoicesParams struct {
	Status      string
	Gateway     sql.NullString
	CreatedFrom sql.NullTime
	CreatedTo   sql.NullTime
	Q           string
	QRef        string
	QMobile     sql.NullString
}

// ---------------------------------------------------------------------------
// Payment log (invoices + receipts). The receipt's card_pan is never selected.
func (q *Queries) AdminCountPlusInvoices(ctx context.Context, arg AdminCountPlusInvoicesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountPlusInvoices,
		arg.Status,
		arg.Gateway,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Q,
		arg.QRef,
		arg.QMobile,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountPlusSubscriptions = `-- name: AdminCountPlusSubscriptions :one

SELECT COUNT(*) FROM plus_subscriptions s
JOIN users u ON u.id = s.user_id
WHERE (s.status LIKE ? OR s.status LIKE ?)
  AND s.ends_at > ? AND s.ends_at <= ?
  AND IFNULL(s.plan_id, 0) >= ? AND IFNULL(s.plan_id, 0) <= ?
  AND s.starts_at >= ? AND s.starts_at < ?
  AND IFNULL(u.mobile, '') LIKE ?
`

type AdminCountPlusSubscriptionsParams struct {
	StatusA    string
	StatusB    string
	EndsAfter  time.Time
	EndsUntil  time.Time
	PlanMin    sql.NullInt64
	PlanMax    sql.NullInt64
	StartsFrom time.Time
	StartsTo   time.Time
	Mobile     sql.NullString
}

// ---------------------------------------------------------------------------
// Subscriptions
//
// Status filter (resolved in Go): status_a / status_b are the stored statuses to match, ends_after < ends_at <=
// ends_until the window ("active" = stored active and ends_at > now; "expired" = active|canceled with ends_at <= now).
func (q *Queries) AdminCountPlusSubscriptions(ctx context.Context, arg AdminCountPlusSubscriptionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountPlusSubscriptions,
		arg.StatusA,
		arg.StatusB,
		arg.EndsAfter,
		arg.EndsUntil,
		arg.PlanMin,
		arg.PlanMax,
		arg.StartsFrom,
		arg.StartsTo,
		arg.Mobile,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreatePlusDiscount = `-- name: AdminCreatePlusDiscount :execlastid
INSERT INTO plus_discount_codes (code, kind, value, max_redemptions, per_user_limit, plan_ids, starts_at, expires_at,
  is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?)
`

type AdminCreatePlusDiscountParams struct {
	Code           string
	Kind           string
	Value          uint64
	MaxRedemptions sql.NullInt32
	PerUserLimit   sql.NullInt32
	PlanIds        db.NullRawJSON
	StartsAt       sql.NullTime
	ExpiresAt      sql.NullTime
	IsActive       bool
	Now            sql.NullTime
}

func (q *Queries) AdminCreatePlusDiscount(ctx context.Context, arg AdminCreatePlusDiscountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminCreatePlusDiscount,
		arg.Code,
		arg.Kind,
		arg.Value,
		arg.MaxRedemptions,
		arg.PerUserLimit,
		arg.PlanIds,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.IsActive,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminCreatePlusPlan = `-- name: AdminCreatePlusPlan :execlastid
INSERT INTO plus_plans (code, title, badge, duration_months, price_rials, monthly_display_rials, is_highlighted,
  is_active, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?)
`

type AdminCreatePlusPlanParams struct {
	Code                string
	Title               json.RawMessage
	Badge               db.NullRawJSON
	DurationMonths      uint16
	PriceRials          uint64
	MonthlyDisplayRials sql.NullInt64
	IsHighlighted       bool
	IsActive            bool
	SortOrder           uint32
	Now                 sql.NullTime
}

func (q *Queries) AdminCreatePlusPlan(ctx context.Context, arg AdminCreatePlusPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminCreatePlusPlan,
		arg.Code,
		arg.Title,
		arg.Badge,
		arg.DurationMonths,
		arg.PriceRials,
		arg.MonthlyDisplayRials,
		arg.IsHighlighted,
		arg.IsActive,
		arg.SortOrder,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminDeactivatePlusDiscount = `-- name: AdminDeactivatePlusDiscount :exec
UPDATE plus_discount_codes SET is_active = 0, updated_at = ? WHERE id = ?
`

type AdminDeactivatePlusDiscountParams struct {
	Now sql.NullTime
	ID  uint64
}

func (q *Queries) AdminDeactivatePlusDiscount(ctx context.Context, arg AdminDeactivatePlusDiscountParams) error {
	_, err := q.db.ExecContext(ctx, adminDeactivatePlusDiscount, arg.Now, arg.ID)
	return err
}

const adminDeactivatePlusPlan = `-- name: AdminDeactivatePlusPlan :exec
UPDATE plus_plans SET is_active = 0, is_highlighted = 0, updated_at = ? WHERE id = ?
`

type AdminDeactivatePlusPlanParams struct {
	Now sql.NullTime
	ID  uint64
}

func (q *Queries) AdminDeactivatePlusPlan(ctx context.Context, arg AdminDeactivatePlusPlanParams) error {
	_, err := q.db.ExecContext(ctx, adminDeactivatePlusPlan, arg.Now, arg.ID)
	return err
}

const adminDeleteUnusedPlusDiscount = `-- name: AdminDeleteUnusedPlusDiscount :execrows
DELETE FROM plus_discount_codes
WHERE plus_discount_codes.id = ?
  AND NOT EXISTS (SELECT 1 FROM plus_invoices i WHERE i.discount_code_id = plus_discount_codes.id)
`

func (q *Queries) AdminDeleteUnusedPlusDiscount(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminDeleteUnusedPlusDiscount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteUnusedPlusPlan = `-- name: AdminDeleteUnusedPlusPlan :execrows
DELETE FROM plus_plans
WHERE plus_plans.id = ?
  AND NOT EXISTS (SELECT 1 FROM plus_invoices i WHERE i.plan_id = plus_plans.id)
  AND NOT EXISTS (SELECT 1 FROM plus_subscriptions s WHERE s.plan_id = plus_plans.id)
`

// Deletes only while nothing references the plan (invoices / subscriptions keep plan_id for the history).
func (q *Queries) AdminDeleteUnusedPlusPlan(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminDeleteUnusedPlusPlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetPlusDiscount = `-- name: AdminGetPlusDiscount :one
SELECT id, code, kind, value, max_redemptions, per_user_limit, plan_ids, starts_at, expires_at, is_active, created_at, updated_at FROM plus_discount_codes WHERE id = ?
`

func (q *Queries) AdminGetPlusDiscount(ctx context.Context, id uint64) (PlusDiscountCode, error) {
	row := q.db.QueryRowContext(ctx, adminGetPlusDiscount, id)
	var i PlusDiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.MaxRedemptions,
		&i.PerUserLimit,
		&i.PlanIds,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetPlusInvoice = `-- name: AdminGetPlusInvoice :one
SELECT i.id, i.reference, i.user_id, i.plan_id, i.duration_months, i.status, i.currency, i.subtotal_rials,
       i.discount_rials, i.vat_rate_bps, i.vat_rials, i.total_rials, i.discount_code, i.gateway, i.authority,
       i.expires_at, i.paid_at, i.created_at, i.updated_at,
       u.name AS user_name, u.mobile AS user_mobile, p.code AS plan_code, p.title AS plan_title,
       r.ref_id AS receipt_ref_id, r.gateway AS receipt_gateway, r.amount_rials AS receipt_amount_rials,
       r.paid_at AS receipt_paid_at
FROM plus_invoices i
JOIN users u ON u.id = i.user_id
LEFT JOIN plus_plans p ON p.id = i.plan_id
LEFT JOIN plus_receipts r ON r.invoice_id = i.id
WHERE i.id = ?
`

type AdminGetPlusInvoiceRow struct {
	ID                 uint64
	Reference          string
	UserID             uint64
	PlanID             sql.NullInt64
	DurationMonths     uint16
	Status             string
	Currency           string
	SubtotalRials      uint64
	DiscountRials      uint64
	VatRateBps         uint32
	VatRials           uint64
	TotalRials         uint64
	DiscountCode       sql.NullString
	Gateway            sql.NullString
	Authority          sql.NullString
	ExpiresAt          time.Time
	PaidAt             sql.NullTime
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	UserName           sql.NullString
	UserMobile         sql.NullString
	PlanCode           sql.NullString
	PlanTitle          db.NullRawJSON
	ReceiptRefID       sql.NullString
	ReceiptGateway     sql.NullString
	ReceiptAmountRials sql.NullInt64
	ReceiptPaidAt      sql.NullTime
}

func (q *Queries) AdminGetPlusInvoice(ctx context.Context, id uint64) (AdminGetPlusInvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetPlusInvoice, id)
	var i AdminGetPlusInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.PlanID,
		&i.DurationMonths,
		&i.Status,
		&i.Currency,
		&i.SubtotalRials,
		&i.DiscountRials,
		&i.VatRateBps,
		&i.VatRials,
		&i.TotalRials,
		&i.DiscountCode,
		&i.Gateway,
		&i.Authority,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserMobile,
		&i.PlanCode,
		&i.PlanTitle,
		&i.ReceiptRefID,
		&i.ReceiptGateway,
		&i.ReceiptAmountRials,
		&i.ReceiptPaidAt,
	)
	return i, err
}

const adminGetPlusPlan = `-- name: AdminGetPlusPlan :one
SELECT id, code, title, badge, duration_months, price_rials, monthly_display_rials, is_highlighted, is_active, sort_order, created_at, updated_at FROM plus_plans WHERE id = ?
`

func (q *Queries) AdminGetPlusPlan(ctx context.Context, id uint64) (PlusPlan, error) {
	row := q.db.QueryRowContext(ctx, adminGetPlusPlan, id)
	var i PlusPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Badge,
		&i.DurationMonths,
		&i.PriceRials,
		&i.MonthlyDisplayRials,
		&i.IsHighlighted,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListPlusDiscounts = `-- name: AdminListPlusDiscounts :many
SELECT d.id, d.code, d.kind, d.value, d.max_redemptions, d.per_user_limit, d.plan_ids, d.starts_at, d.expires_at, d.is_active, d.created_at, d.updated_at,
       (SELECT COUNT(*) FROM plus_invoices i WHERE i.discount_code_id = d.id AND i.status = 'paid') AS paid_uses,
       (SELECT COUNT(*) FROM plus_invoices ip WHERE ip.discount_code_id = d.id AND ip.status = 'pending'
          AND ip.expires_at > ?) AS pending_uses
FROM plus_discount_codes d
WHERE d.code LIKE ?
  AND d.is_active >= ? AND d.is_active <= ?
ORDER BY d.id DESC
LIMIT ? OFFSET ?
`

type AdminListPlusDiscountsParams struct {
	Now       time.Time
	Pattern   string
	ActiveMin bool
	ActiveMax bool
	Limit     int32
	Offset    int32
}

type AdminListPlusDiscountsRow struct {
	PlusDiscountCode PlusDiscountCode
	PaidUses         int64
	PendingUses      int64
}

func (q *Queries) AdminListPlusDiscounts(ctx context.Context, arg AdminListPlusDiscountsParams) ([]AdminListPlusDiscountsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListPlusDiscounts,
		arg.Now,
		arg.Pattern,
		arg.ActiveMin,
		arg.ActiveMax,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlusDiscountsRow{}
	for rows.Next() {
		var i AdminListPlusDiscountsRow
		if err := rows.Scan(
			&i.PlusDiscountCode.ID,
			&i.PlusDiscountCode.Code,
			&i.PlusDiscountCode.Kind,
			&i.PlusDiscountCode.Value,
			&i.PlusDiscountCode.MaxRedemptions,
			&i.PlusDiscountCode.PerUserLimit,
			&i.PlusDiscountCode.PlanIds,
			&i.PlusDiscountCode.StartsAt,
			&i.PlusDiscountCode.ExpiresAt,
			&i.PlusDiscountCode.IsActive,
			&i.PlusDiscountCode.CreatedAt,
			&i.PlusDiscountCode.UpdatedAt,
			&i.PaidUses,
			&i.PendingUses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPlusInvoices = `-- name: AdminListPlusInvoices :many
SELECT i.id, i.reference, i.user_id, i.plan_id, i.duration_months, i.status, i.subtotal_rials, i.discount_rials,
       i.vat_rate_bps, i.vat_rials, i.total_rials, i.discount_code, i.gateway, i.expires_at, i.paid_at, i.created_at,
       u.name AS user_name, u.mobile AS user_mobile, p.code AS plan_code, p.title AS plan_title,
       r.ref_id AS receipt_ref_id, r.amount_rials AS receipt_amount_rials, r.paid_at AS receipt_paid_at
FROM plus_invoices i
JOIN users u ON u.id = i.user_id
LEFT JOIN plus_plans p ON p.id = i.plan_id
LEFT JOIN plus_receipts r ON r.invoice_id = i.id
WHERE i.status LIKE ?
  AND IFNULL(i.gateway, '') LIKE ?
  AND i.created_at >= ? AND i.created_at < ?
  AND (IFNULL(i.reference, '') LIKE ? OR IFNULL(r.ref_id, '') LIKE ? OR IFNULL(u.mobile, '') LIKE ?)
ORDER BY i.id DESC
LIMIT ? OFFSET ?
`

type AdminListPlusInvoicesParams struct {
	Status      string
	Gateway     sql.NullString
	CreatedFrom sql.NullTime
	CreatedTo   sql.NullTime
	Q           string
	QRef        string
	QMobile     sql.NullString
	Limit       int32
	Offset      int32
}

type AdminListPlusInvoicesRow struct {
	ID                 uint64
	Reference          string
	UserID             uint64
	PlanID             sql.NullInt64
	DurationMonths     uint16
	Status             string
	SubtotalRials      uint64
	DiscountRials      uint64
	VatRateBps         uint32
	VatRials           uint64
	TotalRials         uint64
	DiscountCode       sql.NullString
	Gateway            sql.NullString
	ExpiresAt          time.Time
	PaidAt             sql.NullTime
	CreatedAt          sql.NullTime
	UserName           sql.NullString
	UserMobile         sql.NullString
	PlanCode           sql.NullString
	PlanTitle          db.NullRawJSON
	ReceiptRefID       sql.NullString
	ReceiptAmountRials sql.NullInt64
	ReceiptPaidAt      sql.NullTime
}

func (q *Queries) AdminListPlusInvoices(ctx context.Context, arg AdminListPlusInvoicesParams) ([]AdminListPlusInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListPlusInvoices,
		arg.Status,
		arg.Gateway,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Q,
		arg.QRef,
		arg.QMobile,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlusInvoicesRow{}
	for rows.Next() {
		var i AdminListPlusInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.PlanID,
			&i.DurationMonths,
			&i.Status,
			&i.SubtotalRials,
			&i.DiscountRials,
			&i.VatRateBps,
			&i.VatRials,
			&i.TotalRials,
			&i.DiscountCode,
			&i.Gateway,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UserName,
			&i.UserMobile,
			&i.PlanCode,
			&i.PlanTitle,
			&i.ReceiptRefID,
			&i.ReceiptAmountRials,
			&i.ReceiptPaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPlusPlans = `-- name: AdminListPlusPlans :many


SELECT plus_plans.id, plus_plans.code, plus_plans.title, plus_plans.badge, plus_plans.duration_months, plus_plans.price_rials, plus_plans.monthly_display_rials, plus_plans.is_highlighted, plus_plans.is_active, plus_plans.sort_order, plus_plans.created_at, plus_plans.updated_at,
       (SELECT COUNT(*) FROM plus_invoices i WHERE i.plan_id = plus_plans.id) AS invoices_count,
       (SELECT COUNT(*) FROM plus_subscriptions s WHERE s.plan_id = plus_plans.id) AS subscriptions_count,
       (SELECT COUNT(*) FROM plus_subscriptions sa WHERE sa.plan_id = plus_plans.id
          AND sa.status IN ('active', 'canceled') AND sa.ends_at > ?) AS active_subscriptions
FROM plus_plans
ORDER BY plus_plans.sort_order, plus_plans.id
`

type AdminListPlusPlansRow struct {
	PlusPlan            PlusPlan
	InvoicesCount       int64
	SubscriptionsCount  int64
	ActiveSubscriptions int64
}

// Admin «اشتراک‌ها و پرداخت» module (B-N2-09): plans, discount codes, subscriptions, the payment log, refunds,
// extensions and the plus_admin_actions ledger. Admin-only: these read every user's rows by design (the admin chain
// guards them); nothing here is reachable from /api/v1.
// ---------------------------------------------------------------------------
// Plans
func (q *Queries) AdminListPlusPlans(ctx context.Context, now time.Time) ([]AdminListPlusPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListPlusPlans, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlusPlansRow{}
	for rows.Next() {
		var i AdminListPlusPlansRow
		if err := rows.Scan(
			&i.PlusPlan.ID,
			&i.PlusPlan.Code,
			&i.PlusPlan.Title,
			&i.PlusPlan.Badge,
			&i.PlusPlan.DurationMonths,
			&i.PlusPlan.PriceRials,
			&i.PlusPlan.MonthlyDisplayRials,
			&i.PlusPlan.IsHighlighted,
			&i.PlusPlan.IsActive,
			&i.PlusPlan.SortOrder,
			&i.PlusPlan.CreatedAt,
			&i.PlusPlan.UpdatedAt,
			&i.InvoicesCount,
			&i.SubscriptionsCount,
			&i.ActiveSubscriptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPlusSubscriptions = `-- name: AdminListPlusSubscriptions :many
SELECT s.id, s.user_id, s.plan_id, s.invoice_id, s.status, s.source, s.starts_at, s.ends_at, s.auto_renew,
       s.canceled_at, s.created_at, u.name AS user_name, u.mobile AS user_mobile,
       p.code AS plan_code, p.title AS plan_title, i.reference AS invoice_reference
FROM plus_subscriptions s
JOIN users u ON u.id = s.user_id
LEFT JOIN plus_plans p ON p.id = s.plan_id
LEFT JOIN plus_invoices i ON i.id = s.invoice_id
WHERE (s.status LIKE ? OR s.status LIKE ?)
  AND s.ends_at > ? AND s.ends_at <= ?
  AND IFNULL(s.plan_id, 0) >= ? AND IFNULL(s.plan_id, 0) <= ?
  AND s.starts_at >= ? AND s.starts_at < ?
  AND IFNULL(u.mobile, '') LIKE ?
ORDER BY s.id DESC
LIMIT ? OFFSET ?
`

type AdminListPlusSubscriptionsParams struct {
	StatusA    string
	StatusB    string
	EndsAfter  time.Time
	EndsUntil  time.Time
	PlanMin    sql.NullInt64
	PlanMax    sql.NullInt64
	StartsFrom time.Time
	StartsTo   time.Time
	Mobile     sql.NullString
	Limit      int32
	Offset     int32
}

type AdminListPlusSubscriptionsRow struct {
	ID               uint64
	UserID           uint64
	PlanID           sql.NullInt64
	InvoiceID        sql.NullInt64
	Status           string
	Source           string
	StartsAt         time.Time
	EndsAt           time.Time
	AutoRenew        bool
	CanceledAt       sql.NullTime
	CreatedAt        sql.NullTime
	UserName         sql.NullString
	UserMobile       sql.NullString
	PlanCode         sql.NullString
	PlanTitle        db.NullRawJSON
	InvoiceReference sql.NullString
}

func (q *Queries) AdminListPlusSubscriptions(ctx context.Context, arg AdminListPlusSubscriptionsParams) ([]AdminListPlusSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListPlusSubscriptions,
		arg.StatusA,
		arg.StatusB,
		arg.EndsAfter,
		arg.EndsUntil,
		arg.PlanMin,
		arg.PlanMax,
		arg.StartsFrom,
		arg.StartsTo,
		arg.Mobile,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlusSubscriptionsRow{}
	for rows.Next() {
		var i AdminListPlusSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.InvoiceID,
			&i.Status,
			&i.Source,
			&i.StartsAt,
			&i.EndsAt,
			&i.AutoRenew,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UserName,
			&i.UserMobile,
			&i.PlanCode,
			&i.PlanTitle,
			&i.InvoiceReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLockPlusInvoice = `-- name: AdminLockPlusInvoice :one
SELECT id, reference, user_id, plan_id, duration_months, status, currency, subtotal_rials, discount_rials, vat_rate_bps, vat_rials, total_rials, discount_code_id, discount_code, gateway, authority, expires_at, paid_at, created_at, updated_at FROM plus_invoices WHERE id = ? FOR UPDATE
`

func (q *Queries) AdminLockPlusInvoice(ctx context.Context, id uint64) (PlusInvoice, error) {
	row := q.db.QueryRowContext(ctx, adminLockPlusInvoice, id)
	var i PlusInvoice
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.PlanID,
		&i.DurationMonths,
		&i.Status,
		&i.Currency,
		&i.SubtotalRials,
		&i.DiscountRials,
		&i.VatRateBps,
		&i.VatRials,
		&i.TotalRials,
		&i.DiscountCodeID,
		&i.DiscountCode,
		&i.Gateway,
		&i.Authority,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminLockPlusSubscription = `-- name: AdminLockPlusSubscription :one
SELECT id, user_id, plan_id, invoice_id, status, source, starts_at, ends_at, auto_renew, canceled_at, created_at, updated_at FROM plus_subscriptions WHERE id = ? FOR UPDATE
`

func (q *Queries) AdminLockPlusSubscription(ctx context.Context, id uint64) (PlusSubscription, error) {
	row := q.db.QueryRowContext(ctx, adminLockPlusSubscription, id)
	var i PlusSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.InvoiceID,
		&i.Status,
		&i.Source,
		&i.StartsAt,
		&i.EndsAt,
		&i.AutoRenew,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminMarkPlusInvoiceRefunded = `-- name: AdminMarkPlusInvoiceRefunded :execrows
UPDATE plus_invoices SET status = 'refunded', updated_at = ? WHERE id = ? AND status = 'paid'
`

type AdminMarkPlusInvoiceRefundedParams struct {
	Now sql.NullTime
	ID  uint64
}

func (q *Queries) AdminMarkPlusInvoiceRefunded(ctx context.Context, arg AdminMarkPlusInvoiceRefundedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminMarkPlusInvoiceRefunded, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminNextPlusPlanSortOrder = `-- name: AdminNextPlusPlanSortOrder :one
SELECT CAST(COALESCE(MAX(sort_order), 0) + 1 AS UNSIGNED) AS next_sort FROM plus_plans
`

func (q *Queries) AdminNextPlusPlanSortOrder(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminNextPlusPlanSortOrder)
	var next_sort int64
	err := row.Scan(&next_sort)
	return next_sort, err
}

const adminPlusDiscountCodeTaken = `-- name: AdminPlusDiscountCodeTaken :one
SELECT EXISTS(SELECT 1 FROM plus_discount_codes WHERE code = ? AND id <> ?) AS taken
`

type AdminPlusDiscountCodeTakenParams struct {
	Code     string
	ExceptID uint64
}

func (q *Queries) AdminPlusDiscountCodeTaken(ctx context.Context, arg AdminPlusDiscountCodeTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminPlusDiscountCodeTaken, arg.Code, arg.ExceptID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const adminPlusDiscountUses = `-- name: AdminPlusDiscountUses :one
SELECT (SELECT COUNT(*) FROM plus_invoices i WHERE i.discount_code_id = ? AND i.status = 'paid') AS paid_uses,
       (SELECT COUNT(*) FROM plus_invoices ip WHERE ip.discount_code_id = ? AND ip.status = 'pending'
          AND ip.expires_at > ?) AS pending_uses,
       (SELECT COUNT(*) FROM plus_invoices ia WHERE ia.discount_code_id = ?) AS invoices_count
`

type AdminPlusDiscountUsesParams struct {
	ID  sql.NullInt64
	Now time.Time
}

type AdminPlusDiscountUsesRow struct {
	PaidUses      int64
	PendingUses   int64
	InvoicesCount int64
}

func (q *Queries) AdminPlusDiscountUses(ctx context.Context, arg AdminPlusDiscountUsesParams) (AdminPlusDiscountUsesRow, error) {
	row := q.db.QueryRowContext(ctx, adminPlusDiscountUses,
		arg.ID,
		arg.ID,
		arg.Now,
		arg.ID,
	)
	var i AdminPlusDiscountUsesRow
	err := row.Scan(&i.PaidUses, &i.PendingUses, &i.InvoicesCount)
	return i, err
}

const adminPlusGateways = `-- name: AdminPlusGateways :many
SELECT DISTINCT gateway FROM plus_invoices WHERE gateway IS NOT NULL ORDER BY gateway
`

func (q *Queries) AdminPlusGateways(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, adminPlusGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var gateway sql.NullString
		if err := rows.Scan(&gateway); err != nil {
			return nil, err
		}
		items = append(items, gateway)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlusInvoiceReceipt = `-- name: AdminPlusInvoiceReceipt :one
SELECT id, gateway, ref_id, amount_rials, paid_at FROM plus_receipts WHERE invoice_id = ?
`

type AdminPlusInvoiceReceiptRow struct {
	ID          uint64
	Gateway     string
	RefID       string
	AmountRials uint64
	PaidAt      time.Time
}

func (q *Queries) AdminPlusInvoiceReceipt(ctx context.Context, invoiceID uint64) (AdminPlusInvoiceReceiptRow, error) {
	row := q.db.QueryRowContext(ctx, adminPlusInvoiceReceipt, invoiceID)
	var i AdminPlusInvoiceReceiptRow
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.RefID,
		&i.AmountRials,
		&i.PaidAt,
	)
	return i, err
}

const adminPlusInvoiceSubscriptions = `-- name: AdminPlusInvoiceSubscriptions :many
SELECT id, status, source, starts_at, ends_at FROM plus_subscriptions WHERE invoice_id = ? ORDER BY id
`

type AdminPlusInvoiceSubscriptionsRow struct {
	ID       uint64
	Status   string
	Source   string
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) AdminPlusInvoiceSubscriptions(ctx context.Context, invoiceID sql.NullInt64) ([]AdminPlusInvoiceSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminPlusInvoiceSubscriptions, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPlusInvoiceSubscriptionsRow{}
	for rows.Next() {
		var i AdminPlusInvoiceSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Source,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlusInvoiceSummary = `-- name: AdminPlusInvoiceSummary :one
SELECT CAST(COALESCE(SUM(CASE WHEN i.status = 'paid' THEN i.total_rials ELSE 0 END), 0) AS UNSIGNED) AS paid_rials,
       CAST(COALESCE(SUM(CASE WHEN i.status = 'refunded' THEN i.total_rials ELSE 0 END), 0) AS UNSIGNED) AS refunded_rials,
       CAST(COALESCE(SUM(CASE WHEN i.status = 'paid' THEN 1 ELSE 0 END), 0) AS UNSIGNED) AS paid_count
FROM plus_invoices i
JOIN users u ON u.id = i.user_id
LEFT JOIN plus_receipts r ON r.invoice_id = i.id
WHERE i.status LIKE ?
  AND IFNULL(i.gateway, '') LIKE ?
  AND i.created_at >= ? AND i.created_at < ?
  AND (IFNULL(i.reference, '') LIKE ? OR IFNULL(r.ref_id, '') LIKE ? OR IFNULL(u.mobile, '') LIKE ?)
`

type AdminPlusInvoiceSummaryParams struct {
	Status      string
	Gateway     sql.NullString
	CreatedFrom sql.NullTime
	CreatedTo   sql.NullTime
	Q           string
	QRef        string
	QMobile     sql.NullString
}

type AdminPlusInvoiceSummaryRow struct {
	PaidRials     int64
	RefundedRials int64
	PaidCount     int64
}

func (q *Queries) AdminPlusInvoiceSummary(ctx context.Context, arg AdminPlusInvoiceSummaryParams) (AdminPlusInvoiceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, adminPlusInvoiceSummary,
		arg.Status,
		arg.Gateway,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Q,
		arg.QRef,
		arg.QMobile,
	)
	var i AdminPlusInvoiceSummaryRow
	err := row.Scan(&i.PaidRials, &i.RefundedRials, &i.PaidCount)
	return i, err
}

const adminPlusPlanCodeTaken = `-- name: AdminPlusPlanCodeTaken :one
SELECT EXISTS(SELECT 1 FROM plus_plans WHERE code = ? AND id <> ?) AS taken
`

type AdminPlusPlanCodeTakenParams struct {
	Code     string
	ExceptID uint64
}

func (q *Queries) AdminPlusPlanCodeTaken(ctx context.Context, arg AdminPlusPlanCodeTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminPlusPlanCodeTaken, arg.Code, arg.ExceptID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const adminPlusPlanOptions = `-- name: AdminPlusPlanOptions :many
SELECT id, code, title, duration_months, is_active FROM plus_plans ORDER BY sort_order, id
`

type AdminPlusPlanOptionsRow struct {
	ID             uint64
	Code           string
	Title          json.RawMessage
	DurationMonths uint16
	IsActive       bool
}

func (q *Queries) AdminPlusPlanOptions(ctx context.Context) ([]AdminPlusPlanOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminPlusPlanOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPlusPlanOptionsRow{}
	for rows.Next() {
		var i AdminPlusPlanOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.DurationMonths,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlusPlanRefs = `-- name: AdminPlusPlanRefs :one
SELECT (SELECT COUNT(*) FROM plus_invoices i WHERE i.plan_id = ?) AS invoices_count,
       (SELECT COUNT(*) FROM plus_subscriptions s WHERE s.plan_id = ?) AS subscriptions_count
`

type AdminPlusPlanRefsParams struct {
	PlanID sql.NullInt64
}

type AdminPlusPlanRefsRow struct {
	InvoicesCount      int64
	SubscriptionsCount int64
}

func (q *Queries) AdminPlusPlanRefs(ctx context.Context, arg AdminPlusPlanRefsParams) (AdminPlusPlanRefsRow, error) {
	row := q.db.QueryRowContext(ctx, adminPlusPlanRefs, arg.PlanID, arg.PlanID)
	var i AdminPlusPlanRefsRow
	err := row.Scan(&i.InvoicesCount, &i.SubscriptionsCount)
	return i, err
}

const adminPlusSubscriptionCounts = `-- name: AdminPlusSubscriptionCounts :one
SELECT
  (SELECT COUNT(*) FROM plus_subscriptions a WHERE a.status = 'active' AND a.ends_at > ?) AS active,
  (SELECT COUNT(*) FROM plus_subscriptions c WHERE c.status = 'canceled' AND c.ends_at > ?) AS canceled,
  (SELECT COUNT(*) FROM plus_subscriptions e WHERE e.status IN ('active', 'canceled') AND e.ends_at <= ?) AS expired,
  (SELECT COUNT(*) FROM plus_subscriptions r WHERE r.status = 'refunded') AS refunded
`

type AdminPlusSubscriptionCountsParams struct {
	Now time.Time
}

type AdminPlusSubscriptionCountsRow struct {
	Active   int64
	Canceled int64
	Expired  int64
	Refunded int64
}

func (q *Queries) AdminPlusSubscriptionCounts(ctx context.Context, arg AdminPlusSubscriptionCountsParams) (AdminPlusSubscriptionCountsRow, error) {
	row := q.db.QueryRowContext(ctx, adminPlusSubscriptionCounts, arg.Now, arg.Now, arg.Now)
	var i AdminPlusSubscriptionCountsRow
	err := row.Scan(
		&i.Active,
		&i.Canceled,
		&i.Expired,
		&i.Refunded,
	)
	return i, err
}

const adminRefundPlusSubscriptionsOfInvoice = `-- name: AdminRefundPlusSubscriptionsOfInvoice :execrows
UPDATE plus_subscriptions
SET status = 'refunded', auto_renew = 0, updated_at = ?
WHERE invoice_id = ? AND status IN ('active', 'canceled')
`

type AdminRefundPlusSubscriptionsOfInvoiceParams struct {
	Now       sql.NullTime
	InvoiceID sql.NullInt64
}

func (q *Queries) AdminRefundPlusSubscriptionsOfInvoice(ctx context.Context, arg AdminRefundPlusSubscriptionsOfInvoiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminRefundPlusSubscriptionsOfInvoice, arg.Now, arg.InvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminSetPlusSubscriptionEnd = `-- name: AdminSetPlusSubscriptionEnd :exec
UPDATE plus_subscriptions SET ends_at = ?, updated_at = ? WHERE id = ?
`

type AdminSetPlusSubscriptionEndParams struct {
	EndsAt time.Time
	Now    sql.NullTime
	ID     uint64
}

func (q *Queries) AdminSetPlusSubscriptionEnd(ctx context.Context, arg AdminSetPlusSubscriptionEndParams) error {
	_, err := q.db.ExecContext(ctx, adminSetPlusSubscriptionEnd, arg.EndsAt, arg.Now, arg.ID)
	return err
}

const adminShiftQueuedPlusSubscriptions = `-- name: AdminShiftQueuedPlusSubscriptions :execrows
UPDATE plus_subscriptions
SET starts_at = DATE_ADD(starts_at, INTERVAL ? DAY),
    ends_at = DATE_ADD(ends_at, INTERVAL ? DAY),
    updated_at = ?
WHERE user_id = ?
  AND id <> ?
  AND status IN ('active', 'canceled')
  AND starts_at >= ?
`

type AdminShiftQueuedPlusSubscriptionsParams struct {
	Days   interface{}
	Now    sql.NullTime
	UserID uint64
	ID     uint64
	OldEnd time.Time
}

// An extension pushes the user's queued periods (starting at or after the extended period's old end) back by the
// same number of days, so periods never overlap.
func (q *Queries) AdminShiftQueuedPlusSubscriptions(ctx context.Context, arg AdminShiftQueuedPlusSubscriptionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adminShiftQueuedPlusSubscriptions,
		arg.Days,
		arg.Days,
		arg.Now,
		arg.UserID,
		arg.ID,
		arg.OldEnd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdatePlusDiscount = `-- name: AdminUpdatePlusDiscount :exec
UPDATE plus_discount_codes
SET kind = ?, value = ?, max_redemptions = ?,
    per_user_limit = ?, plan_ids = ?, starts_at = ?,
    expires_at = ?, is_active = ?, updated_at = ?
WHERE id = ?
`

type AdminUpdatePlusDiscountParams struct {
	Kind           string
	Value          uint64
	MaxRedemptions sql.NullInt32
	PerUserLimit   sql.NullInt32
	PlanIds        db.NullRawJSON
	StartsAt       sql.NullTime
	ExpiresAt      sql.NullTime
	IsActive       bool
	Now            sql.NullTime
	ID             uint64
}

func (q *Queries) AdminUpdatePlusDiscount(ctx context.Context, arg AdminUpdatePlusDiscountParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdatePlusDiscount,
		arg.Kind,
		arg.Value,
		arg.MaxRedemptions,
		arg.PerUserLimit,
		arg.PlanIds,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.IsActive,
		arg.Now,
		arg.ID,
	)
	return err
}

const adminUpdatePlusPlan = `-- name: AdminUpdatePlusPlan :exec
UPDATE plus_plans
SET title = ?, badge = ?, duration_months = ?,
    price_rials = ?, monthly_display_rials = ?,
    is_highlighted = ?, is_active = ?, sort_order = ?,
    updated_at = ?
WHERE id = ?
`

type AdminUpdatePlusPlanParams struct {
	Title               json.RawMessage
	Badge               db.NullRawJSON
	DurationMonths      uint16
	PriceRials          uint64
	MonthlyDisplayRials sql.NullInt64
	IsHighlighted       bool
	IsActive            bool
	SortOrder           uint32
	Now                 sql.NullTime
	ID                  uint64
}

func (q *Queries) AdminUpdatePlusPlan(ctx context.Context, arg AdminUpdatePlusPlanParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdatePlusPlan,
		arg.Title,
		arg.Badge,
		arg.DurationMonths,
		arg.PriceRials,
		arg.MonthlyDisplayRials,
		arg.IsHighlighted,
		arg.IsActive,
		arg.SortOrder,
		arg.Now,
		arg.ID,
	)
	return err
}

const insertPlusAdminAction = `-- name: InsertPlusAdminAction :exec

INSERT INTO plus_admin_actions (admin_id, action, target_type, target_id, user_id, amount_rials, days, gateway,
  gateway_ref, note, details, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?,
  ?, ?, ?)
`

type InsertPlusAdminActionParams struct {
	AdminID     sql.NullInt64
	Action      string
	TargetType  string
	TargetID    uint64
	UserID      sql.NullInt64
	AmountRials sql.NullInt64
	Days        sql.NullInt32
	Gateway     sql.NullString
	GatewayRef  sql.NullString
	Note        sql.NullString
	Details     db.NullRawJSON
	Now         sql.NullTime
}

// ---------------------------------------------------------------------------
// Ledger
func (q *Queries) InsertPlusAdminAction(ctx context.Context, arg InsertPlusAdminActionParams) error {
	_, err := q.db.ExecContext(ctx, insertPlusAdminAction,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.UserID,
		arg.AmountRials,
		arg.Days,
		arg.Gateway,
		arg.GatewayRef,
		arg.Note,
		arg.Details,
		arg.Now,
		arg.Now,
	)
	return err
}

const listPlusAdminActionsFor = `-- name: ListPlusAdminActionsFor :many
SELECT a.id, a.admin_id, a.action, a.target_type, a.target_id, a.user_id, a.amount_rials, a.days, a.gateway,
       a.gateway_ref, a.note, a.details, a.created_at, ad.name AS admin_name
FROM plus_admin_actions a
LEFT JOIN admins ad ON ad.id = a.admin_id
WHERE a.target_type = ? AND a.target_id = ?
ORDER BY a.id DESC
LIMIT 50
`

type ListPlusAdminActionsForParams struct {
	TargetType string
	TargetID   uint64
}

type ListPlusAdminActionsForRow struct {
	ID          uint64
	AdminID     sql.NullInt64
	Action      string
	TargetType  string
	TargetID    uint64
	UserID      sql.NullInt64
	AmountRials sql.NullInt64
	Days        sql.NullInt32
	Gateway     sql.NullString
	GatewayRef  sql.NullString
	Note        sql.NullString
	Details     db.NullRawJSON
	CreatedAt   sql.NullTime
	AdminName   sql.NullString
}

func (q *Queries) ListPlusAdminActionsFor(ctx context.Context, arg ListPlusAdminActionsForParams) ([]ListPlusAdminActionsForRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlusAdminActionsFor, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlusAdminActionsForRow{}
	for rows.Next() {
		var i ListPlusAdminActionsForRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.UserID,
			&i.AmountRials,
			&i.Days,
			&i.Gateway,
			&i.GatewayRef,
			&i.Note,
			&i.Details,
			&i.CreatedAt,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
