// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycle_settings.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/db"
)

const getCyclePreferences = `-- name: GetCyclePreferences :one

SELECT id, user_id, lengths_auto, created_at, updated_at FROM ` + "`" + `cycle_preferences` + "`" + ` WHERE user_id = ? LIMIT 1
`

// Cycle settings (B-N1-09, goose 00013): GET/PUT /profile/cycle-settings, Go only. The reminder switches and
// times live on the B-N1-11 `notification_preferences` row (categories + schedule); the «خودکار از داده‌ها»
// flag in `cycle_preferences`. Every statement is scoped by user_id.
func (q *Queries) GetCyclePreferences(ctx context.Context, userID uint64) (CyclePreference, error) {
	row := q.db.QueryRowContext(ctx, getCyclePreferences, userID)
	var i CyclePreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LengthsAuto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCyclePreferences = `-- name: UpsertCyclePreferences :exec
INSERT INTO ` + "`" + `cycle_preferences` + "`" + ` (user_id, lengths_auto, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  lengths_auto = VALUES(lengths_auto),
  updated_at = VALUES(updated_at)
`

type UpsertCyclePreferencesParams struct {
	UserID      uint64
	LengthsAuto bool
	Now         sql.NullTime
}

func (q *Queries) UpsertCyclePreferences(ctx context.Context, arg UpsertCyclePreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertCyclePreferences,
		arg.UserID,
		arg.LengthsAuto,
		arg.Now,
		arg.Now,
	)
	return err
}

const upsertReminderPreferences = `-- name: UpsertReminderPreferences :exec
INSERT INTO ` + "`" + `notification_preferences` + "`" + `
  (user_id, categories, schedule, quiet_hours_enabled, quiet_start, quiet_end, neutral_copy, created_at, updated_at)
VALUES
  (?, ?, ?, ?, ?,
   ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  categories = VALUES(categories),
  schedule = VALUES(schedule),
  updated_at = VALUES(updated_at)
`

type UpsertReminderPreferencesParams struct {
	UserID            uint64
	Categories        db.NullRawJSON
	Schedule          db.NullRawJSON
	QuietHoursEnabled bool
	QuietStart        string
	QuietEnd          string
	NeutralCopy       bool
	Now               sql.NullTime
}

// Writes the category switches and the schedule; on first save the other columns take the loaded values
// (the defaults), and an existing row keeps its quiet hours / neutral copy.
func (q *Queries) UpsertReminderPreferences(ctx context.Context, arg UpsertReminderPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertReminderPreferences,
		arg.UserID,
		arg.Categories,
		arg.Schedule,
		arg.QuietHoursEnabled,
		arg.QuietStart,
		arg.QuietEnd,
		arg.NeutralCopy,
		arg.Now,
		arg.Now,
	)
	return err
}
