// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preferences.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/db"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one

SELECT id, user_id, categories, quiet_hours_enabled, quiet_start, quiet_end, neutral_copy, created_at, updated_at, schedule FROM ` + "`" + `notification_preferences` + "`" + ` WHERE user_id = ? LIMIT 1
`

// Notification settings (B-N1-11, goose 00011): one row per user, Go only. Read by
// GET /profile/notification-settings and by every push sender through internal/notifications.
func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uint64) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Categories,
		&i.QuietHoursEnabled,
		&i.QuietStart,
		&i.QuietEnd,
		&i.NeutralCopy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Schedule,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :exec
INSERT INTO ` + "`" + `notification_preferences` + "`" + `
  (user_id, categories, quiet_hours_enabled, quiet_start, quiet_end, neutral_copy, created_at, updated_at)
VALUES
  (?, ?, ?, ?,
   ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  categories = VALUES(categories),
  quiet_hours_enabled = VALUES(quiet_hours_enabled),
  quiet_start = VALUES(quiet_start),
  quiet_end = VALUES(quiet_end),
  neutral_copy = VALUES(neutral_copy),
  updated_at = VALUES(updated_at)
`

type UpsertNotificationPreferencesParams struct {
	UserID            uint64
	Categories        db.NullRawJSON
	QuietHoursEnabled bool
	QuietStart        string
	QuietEnd          string
	NeutralCopy       bool
	Now               sql.NullTime
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.Categories,
		arg.QuietHoursEnabled,
		arg.QuietStart,
		arg.QuietEnd,
		arg.NeutralCopy,
		arg.Now,
		arg.Now,
	)
	return err
}
