// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Placeholder so the `profile` sqlc package exists and compiles before its domain task lands (T-M2-03).
	// Delete this file when the first real query is added to db/queries/profile/.
	SampleProfileUserProfile(ctx context.Context, id uint64) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
