// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sample.sql

package store

import (
	"context"
)

const sampleProfileUserProfile = `-- name: SampleProfileUserProfile :one

SELECT id, user_id, birthday, weight, height, period_duration, cycle_duration, last_period_start, user_goal, pregnancy_intention, chronic_conditions, subscription_type, calculation_status, calculation_started_at, calculation_completed_at, calculation_version, created_at, updated_at FROM ` + "`" + `user_profiles` + "`" + ` WHERE id = ? LIMIT 1
`

// Placeholder so the `profile` sqlc package exists and compiles before its domain task lands (T-M2-03).
// Delete this file when the first real query is added to db/queries/profile/.
func (q *Queries) SampleProfileUserProfile(ctx context.Context, id uint64) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, sampleProfileUserProfile, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Birthday,
		&i.Weight,
		&i.Height,
		&i.PeriodDuration,
		&i.CycleDuration,
		&i.LastPeriodStart,
		&i.UserGoal,
		&i.PregnancyIntention,
		&i.ChronicConditions,
		&i.SubscriptionType,
		&i.CalculationStatus,
		&i.CalculationStartedAt,
		&i.CalculationCompletedAt,
		&i.CalculationVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
