// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support_reports.sql

package store

import (
	"context"
	"database/sql"
)

const countRecentSupportReports = `-- name: CountRecentSupportReports :one
SELECT COUNT(*) FROM ` + "`" + `support_reports` + "`" + ` WHERE user_id = ? AND created_at >= ?
`

type CountRecentSupportReportsParams struct {
	UserID    uint64
	CreatedAt sql.NullTime
}

// Per-user flood guard: reports created since `since`.
func (q *Queries) CountRecentSupportReports(ctx context.Context, arg CountRecentSupportReportsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentSupportReports, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupportReport = `-- name: CreateSupportReport :execlastid

INSERT INTO ` + "`" + `support_reports` + "`" + ` (user_id, message, screenshot_path, app_version, user_agent, status, created_at, updated_at)
VALUES (?, ?, ?, ?,
        ?, 'open', ?, ?)
`

type CreateSupportReportParams struct {
	UserID         uint64
	Message        string
	ScreenshotPath sql.NullString
	AppVersion     sql.NullString
	UserAgent      sql.NullString
	Now            sql.NullTime
}

// Support reports (B-N1-12, goose 00012): «گزارش مشکل» from the Support screen, Go only.
func (q *Queries) CreateSupportReport(ctx context.Context, arg CreateSupportReportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSupportReport,
		arg.UserID,
		arg.Message,
		arg.ScreenshotPath,
		arg.AppVersion,
		arg.UserAgent,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listUserSupportScreenshots = `-- name: ListUserSupportScreenshots :many
SELECT screenshot_path FROM ` + "`" + `support_reports` + "`" + ` WHERE user_id = ? AND screenshot_path IS NOT NULL
`

// Screenshot files to remove with the account (the rows go by ON DELETE CASCADE).
func (q *Queries) ListUserSupportScreenshots(ctx context.Context, userID uint64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listUserSupportScreenshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var screenshot_path sql.NullString
		if err := rows.Scan(&screenshot_path); err != nil {
			return nil, err
		}
		items = append(items, screenshot_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
