// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	DeletePlanItems(ctx context.Context, userID uint64) error
	DeleteReading(ctx context.Context, arg DeleteReadingParams) (int64, error)
	GetReading(ctx context.Context, arg GetReadingParams) (VitalReading, error)
	InsertPlanItem(ctx context.Context, arg InsertPlanItemParams) error
	// Vitals (bloom B-N6-01; internal/vitals): timed BP / glucose / heart-rate readings, the weekly measurement plan and
	// the urgent-message copy. Every user-data query is scoped by user_id in the query itself (IDOR).
	InsertReading(ctx context.Context, arg InsertReadingParams) (int64, error)
	LatestReading(ctx context.Context, arg LatestReadingParams) (VitalReading, error)
	// The live (active + approved) vitals_alert rows, all locales (urgent modal copy).
	ListLiveAlertCopy(ctx context.Context) ([]ListLiveAlertCopyRow, error)
	// The day-level vitals of the log sheet (taxonomy v2 measurements.*, incl. the legacy daily-log projection) in
	// [date_from, date_to], read merged into the vitals views (internal/vitals/merge.go).
	ListLogMeasurements(ctx context.Context, arg ListLogMeasurementsParams) ([]ListLogMeasurementsRow, error)
	ListPlanItems(ctx context.Context, userID uint64) ([]VitalPlanItem, error)
	// Readings of [from, to) newest first; an empty type = every type.
	ListReadings(ctx context.Context, arg ListReadingsParams) ([]VitalReading, error)
	UpdateReading(ctx context.Context, arg UpdateReadingParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
