// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intakes.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const deleteIntake = `-- name: DeleteIntake :execrows
DELETE FROM ` + "`" + `reminder_intakes` + "`" + `
WHERE reminder_id = ? AND user_id = ? AND intake_date = ? AND slot = ?
`

type DeleteIntakeParams struct {
	ReminderID uint64
	UserID     uint64
	IntakeDate civildate.Date
	Slot       string
}

func (q *Queries) DeleteIntake(ctx context.Context, arg DeleteIntakeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIntake,
		arg.ReminderID,
		arg.UserID,
		arg.IntakeDate,
		arg.Slot,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIntake = `-- name: GetIntake :one
SELECT id, user_id, reminder_id, intake_date, slot, taken_at, created_at, updated_at FROM ` + "`" + `reminder_intakes` + "`" + `
WHERE reminder_id = ? AND user_id = ? AND intake_date = ? AND slot = ?
LIMIT 1
`

type GetIntakeParams struct {
	ReminderID uint64
	UserID     uint64
	IntakeDate civildate.Date
	Slot       string
}

func (q *Queries) GetIntake(ctx context.Context, arg GetIntakeParams) (ReminderIntake, error) {
	row := q.db.QueryRowContext(ctx, getIntake,
		arg.ReminderID,
		arg.UserID,
		arg.IntakeDate,
		arg.Slot,
	)
	var i ReminderIntake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReminderID,
		&i.IntakeDate,
		&i.Slot,
		&i.TakenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIntake = `-- name: InsertIntake :execrows

INSERT IGNORE INTO ` + "`" + `reminder_intakes` + "`" + ` (user_id, reminder_id, intake_date, slot, taken_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIntakeParams struct {
	UserID     uint64
	ReminderID uint64
	IntakeDate civildate.Date
	Slot       string
	TakenAt    time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

// Care reminders: doses taken (reminder_intakes, T-M3-01). One row per (reminder, day, slot).
// Idempotent tick: a second tick of the same dose keeps the first taken_at.
func (q *Queries) InsertIntake(ctx context.Context, arg InsertIntakeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertIntake,
		arg.UserID,
		arg.ReminderID,
		arg.IntakeDate,
		arg.Slot,
		arg.TakenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listIntakesOnDate = `-- name: ListIntakesOnDate :many
SELECT reminder_id, slot FROM ` + "`" + `reminder_intakes` + "`" + `
WHERE user_id = ? AND intake_date = ?
`

type ListIntakesOnDateParams struct {
	UserID     uint64
	IntakeDate civildate.Date
}

type ListIntakesOnDateRow struct {
	ReminderID uint64
	Slot       string
}

// Every dose the user took on one day (GET /care/today); uses INDEX (user_id, intake_date).
func (q *Queries) ListIntakesOnDate(ctx context.Context, arg ListIntakesOnDateParams) ([]ListIntakesOnDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listIntakesOnDate, arg.UserID, arg.IntakeDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntakesOnDateRow{}
	for rows.Next() {
		var i ListIntakesOnDateRow
		if err := rows.Scan(&i.ReminderID, &i.Slot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
