<?php

declare(strict_types=1);

use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

// cPanel layout "public_html" (L10-01, docs/DEPLOY-CPANEL.md): this folder is the document root and holds only the
// public files; the application lives in __APP_DIR__/ next to it, outside the web root. Generated by
// deploy/build-cpanel.sh --layout=public_html — change the path below if you renamed or moved the app folder.
$appRoot = dirname(__DIR__).'/__APP_DIR__';

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = $appRoot.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require $appRoot.'/vendor/autoload.php';

// Bootstrap Laravel and handle the request...
/** @var Application $app */
$app = require_once $appRoot.'/bootstrap/app.php';

// public_path() is this folder (CLI processes read the same from bootstrap/public-path.php).
$app->usePublicPath(__DIR__);

$app->handleRequest(Request::capture());
