// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
	"database/sql"
)

const getAccessToken = `-- name: GetAccessToken :one

SELECT id, user_id, client_id, revoked, expires_at FROM ` + "`" + `oauth_access_tokens` + "`" + ` WHERE id = ? LIMIT 1
`

type GetAccessTokenRow struct {
	ID        string
	UserID    sql.NullInt64
	ClientID  string
	Revoked   bool
	ExpiresAt sql.NullTime
}

// Passport tables (oauth_access_tokens, oauth_clients), shared with Laravel.
func (q *Queries) GetAccessToken(ctx context.Context, id string) (GetAccessTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken, id)
	var i GetAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, provider, revoked FROM ` + "`" + `oauth_clients` + "`" + ` WHERE id = ? LIMIT 1
`

type GetClientRow struct {
	ID       string
	Provider sql.NullString
	Revoked  bool
}

// ClientRepository::find($aud) (findActive checks `revoked`, the guard checks `provider`).
func (q *Queries) GetClient(ctx context.Context, id string) (GetClientRow, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i GetClientRow
	err := row.Scan(&i.ID, &i.Provider, &i.Revoked)
	return i, err
}

const insertAccessToken = `-- name: InsertAccessToken :exec
INSERT INTO ` + "`" + `oauth_access_tokens` + "`" + ` (id, user_id, client_id, name, scopes, revoked, created_at, updated_at, expires_at)
VALUES (?, ?, ?, 'auth_token', '[]', 0, ?, ?, ?)
`

type InsertAccessTokenParams struct {
	ID        string
	UserID    sql.NullInt64
	ClientID  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

// AccessTokenRepository::persistNewAccessToken + PersonalAccessTokenFactory (name, scopes '[]').
func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessToken,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listPersonalAccessClientCandidates = `-- name: ListPersonalAccessClientCandidates :many
SELECT id, grant_types FROM ` + "`" + `oauth_clients` + "`" + `
WHERE revoked = 0 AND (provider IS NULL OR provider = 'users')
ORDER BY created_at DESC
`

type ListPersonalAccessClientCandidatesRow struct {
	ID         string
	GrantTypes string
}

// ClientRepository::personalAccessClient('users'): non-revoked, provider NULL or 'users',
// latest first; the caller picks the first whose grant_types contains "personal_access".
func (q *Queries) ListPersonalAccessClientCandidates(ctx context.Context) ([]ListPersonalAccessClientCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalAccessClientCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalAccessClientCandidatesRow{}
	for rows.Next() {
		var i ListPersonalAccessClientCandidatesRow
		if err := rows.Scan(&i.ID, &i.GrantTypes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE ` + "`" + `oauth_access_tokens` + "`" + ` SET revoked = 1, updated_at = ? WHERE id = ?
`

type RevokeAccessTokenParams struct {
	UpdatedAt sql.NullTime
	ID        string
}

// AccessToken::revoke() (Eloquent update also touches updated_at).
func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAccessToken, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserAccessTokens = `-- name: RevokeUserAccessTokens :execrows
UPDATE ` + "`" + `oauth_access_tokens` + "`" + ` SET revoked = 1, updated_at = ? WHERE user_id = ? AND revoked = 0
`

type RevokeUserAccessTokensParams struct {
	UpdatedAt sql.NullTime
	UserID    sql.NullInt64
}

// $user->tokens()->update(['revoked' => true]) — admin block / account deletion.
func (q *Queries) RevokeUserAccessTokens(ctx context.Context, arg RevokeUserAccessTokensParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserAccessTokens, arg.UpdatedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
