// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ivf.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const closeCycle = `-- name: CloseCycle :exec
UPDATE ` + "`" + `ivf_cycles` + "`" + `
SET active_user_id = NULL, outcome = ?, outcome_on = ?, closed_at = ?,
    updated_at = ?
WHERE id = ? AND user_id = ?
`

type CloseCycleParams struct {
	Outcome   sql.NullString
	OutcomeOn civildate.NullDate
	Now       sql.NullTime
	ID        uint64
	UserID    uint64
}

// Records the result and closes the cycle (frees the one-open-cycle slot).
func (q *Queries) CloseCycle(ctx context.Context, arg CloseCycleParams) error {
	_, err := q.db.ExecContext(ctx, closeCycle,
		arg.Outcome,
		arg.OutcomeOn,
		arg.Now,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const countIntakesSince = `-- name: CountIntakesSince :one
SELECT COUNT(*) FROM ` + "`" + `reminder_intakes` + "`" + `
WHERE user_id = ? AND reminder_id = ? AND taken_at >= ?
`

type CountIntakesSinceParams struct {
	UserID     uint64
	ReminderID uint64
	Since      time.Time
}

// Doses of a medicine ticked (care intakes) since the stock was counted — they used the stock up.
func (q *Queries) CountIntakesSince(ctx context.Context, arg CountIntakesSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIntakesSince, arg.UserID, arg.ReminderID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cycleStats = `-- name: CycleStats :one
SELECT COUNT(*) AS cycles, CAST(COALESCE(MAX(number), 0) AS UNSIGNED) AS max_number
FROM ` + "`" + `ivf_cycles` + "`" + ` WHERE user_id = ?
`

type CycleStatsRow struct {
	Cycles    int64
	MaxNumber int64
}

// How many cycles the user has recorded and the highest number (the next cycle's default number is max + 1).
func (q *Queries) CycleStats(ctx context.Context, userID uint64) (CycleStatsRow, error) {
	row := q.db.QueryRowContext(ctx, cycleStats, userID)
	var i CycleStatsRow
	err := row.Scan(&i.Cycles, &i.MaxNumber)
	return i, err
}

const deleteDoseLog = `-- name: DeleteDoseLog :exec
DELETE FROM ` + "`" + `ivf_dose_logs` + "`" + `
WHERE user_id = ? AND ivf_med_id = ? AND dose_date = ?
  AND slot = ?
`

type DeleteDoseLogParams struct {
	UserID   uint64
	IvfMedID uint64
	DoseDate civildate.Date
	Slot     string
}

func (q *Queries) DeleteDoseLog(ctx context.Context, arg DeleteDoseLogParams) error {
	_, err := q.db.ExecContext(ctx, deleteDoseLog,
		arg.UserID,
		arg.IvfMedID,
		arg.DoseDate,
		arg.Slot,
	)
	return err
}

const deleteScan = `-- name: DeleteScan :execrows
DELETE FROM ` + "`" + `ivf_scans` + "`" + ` WHERE user_id = ? AND cycle_id = ? AND scan_date = ?
`

type DeleteScanParams struct {
	UserID   uint64
	CycleID  uint64
	ScanDate civildate.Date
}

func (q *Queries) DeleteScan(ctx context.Context, arg DeleteScanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScan, arg.UserID, arg.CycleID, arg.ScanDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTWWLog = `-- name: DeleteTWWLog :exec
DELETE FROM ` + "`" + `ivf_tww_logs` + "`" + ` WHERE user_id = ? AND cycle_id = ? AND log_date = ?
`

type DeleteTWWLogParams struct {
	UserID  uint64
	CycleID uint64
	LogDate civildate.Date
}

func (q *Queries) DeleteTWWLog(ctx context.Context, arg DeleteTWWLogParams) error {
	_, err := q.db.ExecContext(ctx, deleteTWWLog, arg.UserID, arg.CycleID, arg.LogDate)
	return err
}

const getActiveCycle = `-- name: GetActiveCycle :one
SELECT id, user_id, active_user_id, number, protocol, stage, started_on, stim_started_on, retrieval_at, transfer_at, beta_on, next_scan_at, notify_companion, outcome, outcome_on, closed_at, created_at, updated_at FROM ` + "`" + `ivf_cycles` + "`" + ` WHERE user_id = ? AND active_user_id IS NOT NULL LIMIT 1
`

func (q *Queries) GetActiveCycle(ctx context.Context, userID uint64) (IvfCycle, error) {
	row := q.db.QueryRowContext(ctx, getActiveCycle, userID)
	var i IvfCycle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveUserID,
		&i.Number,
		&i.Protocol,
		&i.Stage,
		&i.StartedOn,
		&i.StimStartedOn,
		&i.RetrievalAt,
		&i.TransferAt,
		&i.BetaOn,
		&i.NextScanAt,
		&i.NotifyCompanion,
		&i.Outcome,
		&i.OutcomeOn,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIVFSwitch = `-- name: GetIVFSwitch :one

SELECT EXISTS(SELECT 1 FROM ` + "`" + `user_life_profiles` + "`" + ` WHERE user_id = ? AND ivf_iui = 1) AS ivf_iui
`

// IVF treatment (CB-IVF-01, goose 00027). Health data: every statement is scoped by user_id in the statement itself.
// Medicines are care medication reminders and doses taken are care intakes (internal/care store, reused as is);
// the statements here only read/write the ivf_* side tables, the life-profile switch and the few `reminders` /
// `reminder_intakes` reads the IVF screens need.
// bloom's «IVF/IUI» switch (B-N2-03); false without a life-profile row.
func (q *Queries) GetIVFSwitch(ctx context.Context, userID uint64) (bool, error) {
	row := q.db.QueryRowContext(ctx, getIVFSwitch, userID)
	var ivf_iui bool
	err := row.Scan(&ivf_iui)
	return ivf_iui, err
}

const getMed = `-- name: GetMed :one
SELECT m.id, m.user_id, m.cycle_id, m.reminder_id, m.role, m.route, m.trigger_at, m.stock_units, m.stock_unit, m.doses_per_unit, m.stock_counted_at, m.created_at, m.updated_at, r.id, r.user_id, r.type, r.title, r.subtitle, r.notes, r.scheduled_at, r.recurrence, r.recurrence_time, r.starts_on, r.ends_on, r.is_active, r.meta, r.created_at, r.updated_at
FROM ` + "`" + `ivf_meds` + "`" + ` m
JOIN ` + "`" + `reminders` + "`" + ` r ON r.id = m.reminder_id AND r.user_id = m.user_id
WHERE m.id = ? AND m.user_id = ?
LIMIT 1
`

type GetMedParams struct {
	ID     uint64
	UserID uint64
}

type GetMedRow struct {
	IvfMed   IvfMed
	Reminder Reminder
}

func (q *Queries) GetMed(ctx context.Context, arg GetMedParams) (GetMedRow, error) {
	row := q.db.QueryRowContext(ctx, getMed, arg.ID, arg.UserID)
	var i GetMedRow
	err := row.Scan(
		&i.IvfMed.ID,
		&i.IvfMed.UserID,
		&i.IvfMed.CycleID,
		&i.IvfMed.ReminderID,
		&i.IvfMed.Role,
		&i.IvfMed.Route,
		&i.IvfMed.TriggerAt,
		&i.IvfMed.StockUnits,
		&i.IvfMed.StockUnit,
		&i.IvfMed.DosesPerUnit,
		&i.IvfMed.StockCountedAt,
		&i.IvfMed.CreatedAt,
		&i.IvfMed.UpdatedAt,
		&i.Reminder.ID,
		&i.Reminder.UserID,
		&i.Reminder.Type,
		&i.Reminder.Title,
		&i.Reminder.Subtitle,
		&i.Reminder.Notes,
		&i.Reminder.ScheduledAt,
		&i.Reminder.Recurrence,
		&i.Reminder.RecurrenceTime,
		&i.Reminder.StartsOn,
		&i.Reminder.EndsOn,
		&i.Reminder.IsActive,
		&i.Reminder.Meta,
		&i.Reminder.CreatedAt,
		&i.Reminder.UpdatedAt,
	)
	return i, err
}

const insertCycle = `-- name: InsertCycle :execlastid
INSERT INTO ` + "`" + `ivf_cycles` + "`" + `
  (user_id, active_user_id, number, protocol, stage, started_on, stim_started_on, notify_companion, created_at, updated_at)
VALUES
  (?, ?, ?, ?, ?, ?,
   ?, ?, ?, ?)
`

type InsertCycleParams struct {
	UserID          uint64
	ActiveUserID    sql.NullInt64
	Number          uint8
	Protocol        sql.NullString
	Stage           string
	StartedOn       civildate.Date
	StimStartedOn   civildate.NullDate
	NotifyCompanion bool
	Now             sql.NullTime
}

func (q *Queries) InsertCycle(ctx context.Context, arg InsertCycleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCycle,
		arg.UserID,
		arg.ActiveUserID,
		arg.Number,
		arg.Protocol,
		arg.Stage,
		arg.StartedOn,
		arg.StimStartedOn,
		arg.NotifyCompanion,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertMed = `-- name: InsertMed :execlastid
INSERT INTO ` + "`" + `ivf_meds` + "`" + `
  (user_id, cycle_id, reminder_id, role, route, trigger_at, stock_units, stock_unit, doses_per_unit, stock_counted_at,
   created_at, updated_at)
VALUES
  (?, ?, ?, ?, ?, ?,
   ?, ?, ?, ?,
   ?, ?)
`

type InsertMedParams struct {
	UserID         uint64
	CycleID        uint64
	ReminderID     uint64
	Role           string
	Route          string
	TriggerAt      sql.NullTime
	StockUnits     sql.NullInt16
	StockUnit      sql.NullString
	DosesPerUnit   uint16
	StockCountedAt sql.NullTime
	Now            sql.NullTime
}

func (q *Queries) InsertMed(ctx context.Context, arg InsertMedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMed,
		arg.UserID,
		arg.CycleID,
		arg.ReminderID,
		arg.Role,
		arg.Route,
		arg.TriggerAt,
		arg.StockUnits,
		arg.StockUnit,
		arg.DosesPerUnit,
		arg.StockCountedAt,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertReminderLink = `-- name: InsertReminderLink :exec
INSERT INTO ` + "`" + `ivf_reminders` + "`" + ` (user_id, cycle_id, kind, reminder_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  reminder_id = VALUES(reminder_id),
  updated_at = VALUES(updated_at)
`

type InsertReminderLinkParams struct {
	UserID     uint64
	CycleID    uint64
	Kind       string
	ReminderID uint64
	Now        sql.NullTime
}

func (q *Queries) InsertReminderLink(ctx context.Context, arg InsertReminderLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertReminderLink,
		arg.UserID,
		arg.CycleID,
		arg.Kind,
		arg.ReminderID,
		arg.Now,
		arg.Now,
	)
	return err
}

const listCycleMeds = `-- name: ListCycleMeds :many
SELECT m.id, m.user_id, m.cycle_id, m.reminder_id, m.role, m.route, m.trigger_at, m.stock_units, m.stock_unit, m.doses_per_unit, m.stock_counted_at, m.created_at, m.updated_at, r.id, r.user_id, r.type, r.title, r.subtitle, r.notes, r.scheduled_at, r.recurrence, r.recurrence_time, r.starts_on, r.ends_on, r.is_active, r.meta, r.created_at, r.updated_at
FROM ` + "`" + `ivf_meds` + "`" + ` m
JOIN ` + "`" + `reminders` + "`" + ` r ON r.id = m.reminder_id AND r.user_id = m.user_id
WHERE m.user_id = ? AND m.cycle_id = ?
ORDER BY m.id
`

type ListCycleMedsParams struct {
	UserID  uint64
	CycleID uint64
}

type ListCycleMedsRow struct {
	IvfMed   IvfMed
	Reminder Reminder
}

// The cycle's medicines with the care reminder each one is, in the order they were added.
func (q *Queries) ListCycleMeds(ctx context.Context, arg ListCycleMedsParams) ([]ListCycleMedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCycleMeds, arg.UserID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCycleMedsRow{}
	for rows.Next() {
		var i ListCycleMedsRow
		if err := rows.Scan(
			&i.IvfMed.ID,
			&i.IvfMed.UserID,
			&i.IvfMed.CycleID,
			&i.IvfMed.ReminderID,
			&i.IvfMed.Role,
			&i.IvfMed.Route,
			&i.IvfMed.TriggerAt,
			&i.IvfMed.StockUnits,
			&i.IvfMed.StockUnit,
			&i.IvfMed.DosesPerUnit,
			&i.IvfMed.StockCountedAt,
			&i.IvfMed.CreatedAt,
			&i.IvfMed.UpdatedAt,
			&i.Reminder.ID,
			&i.Reminder.UserID,
			&i.Reminder.Type,
			&i.Reminder.Title,
			&i.Reminder.Subtitle,
			&i.Reminder.Notes,
			&i.Reminder.ScheduledAt,
			&i.Reminder.Recurrence,
			&i.Reminder.RecurrenceTime,
			&i.Reminder.StartsOn,
			&i.Reminder.EndsOn,
			&i.Reminder.IsActive,
			&i.Reminder.Meta,
			&i.Reminder.CreatedAt,
			&i.Reminder.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoseLogsBetween = `-- name: ListDoseLogsBetween :many
SELECT ivf_med_id, dose_date, slot, site FROM ` + "`" + `ivf_dose_logs` + "`" + `
WHERE user_id = ? AND dose_date >= ? AND dose_date <= ?
`

type ListDoseLogsBetweenParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

type ListDoseLogsBetweenRow struct {
	IvfMedID uint64
	DoseDate civildate.Date
	Slot     string
	Site     sql.NullString
}

// The injection sites logged from `from_date` to `to_date` (inclusive).
func (q *Queries) ListDoseLogsBetween(ctx context.Context, arg ListDoseLogsBetweenParams) ([]ListDoseLogsBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listDoseLogsBetween, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoseLogsBetweenRow{}
	for rows.Next() {
		var i ListDoseLogsBetweenRow
		if err := rows.Scan(
			&i.IvfMedID,
			&i.DoseDate,
			&i.Slot,
			&i.Site,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntakesBetween = `-- name: ListIntakesBetween :many
SELECT reminder_id, intake_date, slot FROM ` + "`" + `reminder_intakes` + "`" + `
WHERE user_id = ? AND intake_date >= ? AND intake_date <= ?
`

type ListIntakesBetweenParams struct {
	UserID   uint64
	FromDate civildate.Date
	ToDate   civildate.Date
}

type ListIntakesBetweenRow struct {
	ReminderID uint64
	IntakeDate civildate.Date
	Slot       string
}

// Doses ticked (care intakes) from `from_date` to `to_date` (inclusive).
func (q *Queries) ListIntakesBetween(ctx context.Context, arg ListIntakesBetweenParams) ([]ListIntakesBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listIntakesBetween, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntakesBetweenRow{}
	for rows.Next() {
		var i ListIntakesBetweenRow
		if err := rows.Scan(&i.ReminderID, &i.IntakeDate, &i.Slot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderLinks = `-- name: ListReminderLinks :many
SELECT l.kind, r.id, r.user_id, r.type, r.title, r.subtitle, r.notes, r.scheduled_at, r.recurrence, r.recurrence_time, r.starts_on, r.ends_on, r.is_active, r.meta, r.created_at, r.updated_at
FROM ` + "`" + `ivf_reminders` + "`" + ` l
JOIN ` + "`" + `reminders` + "`" + ` r ON r.id = l.reminder_id AND r.user_id = l.user_id
WHERE l.user_id = ? AND l.cycle_id = ?
ORDER BY l.id
`

type ListReminderLinksParams struct {
	UserID  uint64
	CycleID uint64
}

type ListReminderLinksRow struct {
	Kind     string
	Reminder Reminder
}

// The care appointments the cycle dates created, with their current row (a reminder the user deleted has no link).
func (q *Queries) ListReminderLinks(ctx context.Context, arg ListReminderLinksParams) ([]ListReminderLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listReminderLinks, arg.UserID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReminderLinksRow{}
	for rows.Next() {
		var i ListReminderLinksRow
		if err := rows.Scan(
			&i.Kind,
			&i.Reminder.ID,
			&i.Reminder.UserID,
			&i.Reminder.Type,
			&i.Reminder.Title,
			&i.Reminder.Subtitle,
			&i.Reminder.Notes,
			&i.Reminder.ScheduledAt,
			&i.Reminder.Recurrence,
			&i.Reminder.RecurrenceTime,
			&i.Reminder.StartsOn,
			&i.Reminder.EndsOn,
			&i.Reminder.IsActive,
			&i.Reminder.Meta,
			&i.Reminder.CreatedAt,
			&i.Reminder.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScans = `-- name: ListScans :many
SELECT id, user_id, cycle_id, scan_date, right_lt_10, right_10_14, right_15_17, right_18_plus, left_lt_10, left_10_14, left_15_17, left_18_plus, endometrium_mm, e2, e2_unit, notes, created_at, updated_at FROM ` + "`" + `ivf_scans` + "`" + ` WHERE user_id = ? AND cycle_id = ? ORDER BY scan_date
`

type ListScansParams struct {
	UserID  uint64
	CycleID uint64
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]IvfScan, error) {
	rows, err := q.db.QueryContext(ctx, listScans, arg.UserID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IvfScan{}
	for rows.Next() {
		var i IvfScan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CycleID,
			&i.ScanDate,
			&i.RightLt10,
			&i.Right1014,
			&i.Right1517,
			&i.Right18Plus,
			&i.LeftLt10,
			&i.Left1014,
			&i.Left1517,
			&i.Left18Plus,
			&i.EndometriumMm,
			&i.E2,
			&i.E2Unit,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTWWLogs = `-- name: ListTWWLogs :many
SELECT log_date, mood FROM ` + "`" + `ivf_tww_logs` + "`" + ` WHERE user_id = ? AND cycle_id = ? ORDER BY log_date
`

type ListTWWLogsParams struct {
	UserID  uint64
	CycleID uint64
}

type ListTWWLogsRow struct {
	LogDate civildate.Date
	Mood    string
}

func (q *Queries) ListTWWLogs(ctx context.Context, arg ListTWWLogsParams) ([]ListTWWLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTWWLogs, arg.UserID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTWWLogsRow{}
	for rows.Next() {
		var i ListTWWLogsRow
		if err := rows.Scan(&i.LogDate, &i.Mood); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveCycle = `-- name: LockActiveCycle :one
SELECT id, user_id, active_user_id, number, protocol, stage, started_on, stim_started_on, retrieval_at, transfer_at, beta_on, next_scan_at, notify_companion, outcome, outcome_on, closed_at, created_at, updated_at FROM ` + "`" + `ivf_cycles` + "`" + ` WHERE user_id = ? AND active_user_id IS NOT NULL LIMIT 1 FOR UPDATE
`

// The open cycle, row-locked for a write transaction.
func (q *Queries) LockActiveCycle(ctx context.Context, userID uint64) (IvfCycle, error) {
	row := q.db.QueryRowContext(ctx, lockActiveCycle, userID)
	var i IvfCycle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveUserID,
		&i.Number,
		&i.Protocol,
		&i.Stage,
		&i.StartedOn,
		&i.StimStartedOn,
		&i.RetrievalAt,
		&i.TransferAt,
		&i.BetaOn,
		&i.NextScanAt,
		&i.NotifyCompanion,
		&i.Outcome,
		&i.OutcomeOn,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveAppointment = `-- name: MoveAppointment :exec
UPDATE ` + "`" + `reminders` + "`" + ` SET scheduled_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND ` + "`" + `type` + "`" + ` = 'appointment'
`

type MoveAppointmentParams struct {
	ScheduledAt sql.NullTime
	Now         sql.NullTime
	ID          uint64
	UserID      uint64
}

// A changed cycle date moves its appointment; the user's own edits (title, notes, details, switch) stay.
func (q *Queries) MoveAppointment(ctx context.Context, arg MoveAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, moveAppointment,
		arg.ScheduledAt,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const recentSites = `-- name: RecentSites :many
SELECT site, dose_date, slot FROM ` + "`" + `ivf_dose_logs` + "`" + `
WHERE user_id = ? AND site IS NOT NULL
ORDER BY dose_date DESC, slot DESC, id DESC
LIMIT 200
`

type RecentSitesRow struct {
	Site     sql.NullString
	DoseDate civildate.Date
	Slot     string
}

// The most recent injection sites, newest first (the rotation reads the last use of each site).
func (q *Queries) RecentSites(ctx context.Context, userID uint64) ([]RecentSitesRow, error) {
	rows, err := q.db.QueryContext(ctx, recentSites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentSitesRow{}
	for rows.Next() {
		var i RecentSitesRow
		if err := rows.Scan(&i.Site, &i.DoseDate, &i.Slot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIVFSwitch = `-- name: SetIVFSwitch :exec
INSERT INTO ` + "`" + `user_life_profiles` + "`" + ` (user_id, ivf_iui, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  ivf_iui = VALUES(ivf_iui),
  updated_at = VALUES(updated_at)
`

type SetIVFSwitchParams struct {
	UserID uint64
	IvfIui bool
	Now    sql.NullTime
}

// Flips only the switch (a missing row is created with the column defaults, like PUT /profile/life-stage).
func (q *Queries) SetIVFSwitch(ctx context.Context, arg SetIVFSwitchParams) error {
	_, err := q.db.ExecContext(ctx, setIVFSwitch,
		arg.UserID,
		arg.IvfIui,
		arg.Now,
		arg.Now,
	)
	return err
}

const setReminderActive = `-- name: SetReminderActive :exec
UPDATE ` + "`" + `reminders` + "`" + ` SET is_active = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type SetReminderActiveParams struct {
	IsActive bool
	Now      sql.NullTime
	ID       uint64
	UserID   uint64
}

// Switches a cycle's medicine reminder on/off (a negative or cancelled cycle stops its injection reminders).
func (q *Queries) SetReminderActive(ctx context.Context, arg SetReminderActiveParams) error {
	_, err := q.db.ExecContext(ctx, setReminderActive,
		arg.IsActive,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateCycle = `-- name: UpdateCycle :exec
UPDATE ` + "`" + `ivf_cycles` + "`" + `
SET number = ?, protocol = ?, stage = ?, started_on = ?,
    stim_started_on = ?, retrieval_at = ?,
    transfer_at = ?, beta_on = ?, next_scan_at = ?,
    notify_companion = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateCycleParams struct {
	Number          uint8
	Protocol        sql.NullString
	Stage           string
	StartedOn       civildate.Date
	StimStartedOn   civildate.NullDate
	RetrievalAt     sql.NullTime
	TransferAt      sql.NullTime
	BetaOn          civildate.NullDate
	NextScanAt      sql.NullTime
	NotifyCompanion bool
	Now             sql.NullTime
	ID              uint64
	UserID          uint64
}

// Every editable field of an open cycle (the service merges a partial PUT over the stored row).
func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) error {
	_, err := q.db.ExecContext(ctx, updateCycle,
		arg.Number,
		arg.Protocol,
		arg.Stage,
		arg.StartedOn,
		arg.StimStartedOn,
		arg.RetrievalAt,
		arg.TransferAt,
		arg.BetaOn,
		arg.NextScanAt,
		arg.NotifyCompanion,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateMed = `-- name: UpdateMed :exec
UPDATE ` + "`" + `ivf_meds` + "`" + `
SET role = ?, route = ?, trigger_at = ?,
    stock_units = ?, stock_unit = ?, doses_per_unit = ?,
    stock_counted_at = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateMedParams struct {
	Role           string
	Route          string
	TriggerAt      sql.NullTime
	StockUnits     sql.NullInt16
	StockUnit      sql.NullString
	DosesPerUnit   uint16
	StockCountedAt sql.NullTime
	Now            sql.NullTime
	ID             uint64
	UserID         uint64
}

func (q *Queries) UpdateMed(ctx context.Context, arg UpdateMedParams) error {
	_, err := q.db.ExecContext(ctx, updateMed,
		arg.Role,
		arg.Route,
		arg.TriggerAt,
		arg.StockUnits,
		arg.StockUnit,
		arg.DosesPerUnit,
		arg.StockCountedAt,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertDoseLog = `-- name: UpsertDoseLog :exec
INSERT INTO ` + "`" + `ivf_dose_logs` + "`" + ` (user_id, ivf_med_id, dose_date, slot, site, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  site = VALUES(site),
  updated_at = VALUES(updated_at)
`

type UpsertDoseLogParams struct {
	UserID   uint64
	IvfMedID uint64
	DoseDate civildate.Date
	Slot     string
	Site     sql.NullString
	Now      sql.NullTime
}

func (q *Queries) UpsertDoseLog(ctx context.Context, arg UpsertDoseLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertDoseLog,
		arg.UserID,
		arg.IvfMedID,
		arg.DoseDate,
		arg.Slot,
		arg.Site,
		arg.Now,
		arg.Now,
	)
	return err
}

const upsertScan = `-- name: UpsertScan :exec
INSERT INTO ` + "`" + `ivf_scans` + "`" + `
  (user_id, cycle_id, scan_date, right_lt_10, right_10_14, right_15_17, right_18_plus,
   left_lt_10, left_10_14, left_15_17, left_18_plus, endometrium_mm, e2, e2_unit, notes, created_at, updated_at)
VALUES
  (?, ?, ?, ?, ?,
   ?, ?, ?, ?, ?,
   ?, ?, ?, ?, ?,
   ?, ?)
ON DUPLICATE KEY UPDATE
  right_lt_10 = VALUES(right_lt_10), right_10_14 = VALUES(right_10_14), right_15_17 = VALUES(right_15_17),
  right_18_plus = VALUES(right_18_plus), left_lt_10 = VALUES(left_lt_10), left_10_14 = VALUES(left_10_14),
  left_15_17 = VALUES(left_15_17), left_18_plus = VALUES(left_18_plus), endometrium_mm = VALUES(endometrium_mm),
  e2 = VALUES(e2), e2_unit = VALUES(e2_unit), notes = VALUES(notes), updated_at = VALUES(updated_at)
`

type UpsertScanParams struct {
	UserID        uint64
	CycleID       uint64
	ScanDate      civildate.Date
	RightLt10     uint8
	Right1014     uint8
	Right1517     uint8
	Right18Plus   uint8
	LeftLt10      uint8
	Left1014      uint8
	Left1517      uint8
	Left18Plus    uint8
	EndometriumMm sql.NullString
	E2            sql.NullString
	E2Unit        sql.NullString
	Notes         sql.NullString
	Now           sql.NullTime
}

// One scan per cycle day; saving the day again replaces it.
func (q *Queries) UpsertScan(ctx context.Context, arg UpsertScanParams) error {
	_, err := q.db.ExecContext(ctx, upsertScan,
		arg.UserID,
		arg.CycleID,
		arg.ScanDate,
		arg.RightLt10,
		arg.Right1014,
		arg.Right1517,
		arg.Right18Plus,
		arg.LeftLt10,
		arg.Left1014,
		arg.Left1517,
		arg.Left18Plus,
		arg.EndometriumMm,
		arg.E2,
		arg.E2Unit,
		arg.Notes,
		arg.Now,
		arg.Now,
	)
	return err
}

const upsertTWWLog = `-- name: UpsertTWWLog :exec
INSERT INTO ` + "`" + `ivf_tww_logs` + "`" + ` (user_id, cycle_id, log_date, mood, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  mood = VALUES(mood),
  updated_at = VALUES(updated_at)
`

type UpsertTWWLogParams struct {
	UserID  uint64
	CycleID uint64
	LogDate civildate.Date
	Mood    string
	Now     sql.NullTime
}

func (q *Queries) UpsertTWWLog(ctx context.Context, arg UpsertTWWLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertTWWLog,
		arg.UserID,
		arg.CycleID,
		arg.LogDate,
		arg.Mood,
		arg.Now,
		arg.Now,
	)
	return err
}
