// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const countRecordDocuments = `-- name: CountRecordDocuments :one
SELECT COUNT(*) FROM ` + "`" + `record_documents` + "`" + ` WHERE user_id = ?
`

func (q *Queries) CountRecordDocuments(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecordDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordDocumentsByKind = `-- name: CountRecordDocumentsByKind :many
SELECT kind, COUNT(*) AS documents FROM ` + "`" + `record_documents` + "`" + ` WHERE user_id = ? GROUP BY kind
`

type CountRecordDocumentsByKindRow struct {
	Kind      string
	Documents int64
}

func (q *Queries) CountRecordDocumentsByKind(ctx context.Context, userID uint64) ([]CountRecordDocumentsByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, countRecordDocumentsByKind, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRecordDocumentsByKindRow{}
	for rows.Next() {
		var i CountRecordDocumentsByKindRow
		if err := rows.Scan(&i.Kind, &i.Documents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecordDocumentsInReview = `-- name: CountRecordDocumentsInReview :one
SELECT COUNT(*) FROM ` + "`" + `record_documents` + "`" + `
WHERE user_id = ? AND review_state = 'needs_review'
`

func (q *Queries) CountRecordDocumentsInReview(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecordDocumentsInReview, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDetachedRecordFile = `-- name: DeleteDetachedRecordFile :execrows
DELETE FROM ` + "`" + `files` + "`" + `
WHERE ` + "`" + `files` + "`" + `.id = ? AND ` + "`" + `files` + "`" + `.user_id = ? AND ` + "`" + `files` + "`" + `.purpose = 'record_document'
  AND NOT EXISTS (SELECT 1 FROM ` + "`" + `record_document_files` + "`" + ` r WHERE r.file_id = ` + "`" + `files` + "`" + `.id)
`

type DeleteDetachedRecordFileParams struct {
	ID     uint64
	UserID sql.NullInt64
}

// Deletes a record_document file of the user that no document uses any more (inside the transaction that detached
// it; the blob is removed after commit).
func (q *Queries) DeleteDetachedRecordFile(ctx context.Context, arg DeleteDetachedRecordFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDetachedRecordFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecordDocument = `-- name: DeleteRecordDocument :execrows
DELETE FROM ` + "`" + `record_documents` + "`" + ` WHERE id = ? AND user_id = ?
`

type DeleteRecordDocumentParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeleteRecordDocument(ctx context.Context, arg DeleteRecordDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecordDocument, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecordDocumentFiles = `-- name: DeleteRecordDocumentFiles :exec
DELETE FROM ` + "`" + `record_document_files` + "`" + ` WHERE document_id = ? AND user_id = ?
`

type DeleteRecordDocumentFilesParams struct {
	DocumentID uint64
	UserID     uint64
}

func (q *Queries) DeleteRecordDocumentFiles(ctx context.Context, arg DeleteRecordDocumentFilesParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecordDocumentFiles, arg.DocumentID, arg.UserID)
	return err
}

const deleteRecordDocumentLink = `-- name: DeleteRecordDocumentLink :execrows
DELETE FROM ` + "`" + `record_document_links` + "`" + `
WHERE document_id = ? AND user_id = ? AND target_type = ?
  AND target_id = ?
`

type DeleteRecordDocumentLinkParams struct {
	DocumentID uint64
	UserID     uint64
	TargetType string
	TargetID   uint64
}

func (q *Queries) DeleteRecordDocumentLink(ctx context.Context, arg DeleteRecordDocumentLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecordDocumentLink,
		arg.DocumentID,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecordDocument = `-- name: GetRecordDocument :one
SELECT id, user_id, kind, title, document_date, ended_on, centre, doctor, note, extracted, review_state, created_at, updated_at FROM ` + "`" + `record_documents` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetRecordDocumentParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) GetRecordDocument(ctx context.Context, arg GetRecordDocumentParams) (RecordDocument, error) {
	row := q.db.QueryRowContext(ctx, getRecordDocument, arg.ID, arg.UserID)
	var i RecordDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.DocumentDate,
		&i.EndedOn,
		&i.Centre,
		&i.Doctor,
		&i.Note,
		&i.Extracted,
		&i.ReviewState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecordExtras = `-- name: GetRecordExtras :one

SELECT allergies, allergies_on_emergency_card, surgeries, family_history, updated_at FROM ` + "`" + `health_records` + "`" + `
WHERE user_id = ? LIMIT 1
`

type GetRecordExtrasRow struct {
	Allergies                db.NullRawJSON
	AllergiesOnEmergencyCard bool
	Surgeries                db.NullRawJSON
	FamilyHistory            db.NullRawJSON
	UpdatedAt                sql.NullTime
}

// Record documents, extras and timeline (canvas-build CB-REC-01; internal/healthrecord documents*.go, extras.go,
// timeline.go). Every query is scoped by user_id in the query itself (IDOR): a document, its files and its links are
// only ever read or written together with the owner's id.
func (q *Queries) GetRecordExtras(ctx context.Context, userID uint64) (GetRecordExtrasRow, error) {
	row := q.db.QueryRowContext(ctx, getRecordExtras, userID)
	var i GetRecordExtrasRow
	err := row.Scan(
		&i.Allergies,
		&i.AllergiesOnEmergencyCard,
		&i.Surgeries,
		&i.FamilyHistory,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecordFileDocument = `-- name: GetRecordFileDocument :one
SELECT document_id FROM ` + "`" + `record_document_files` + "`" + `
WHERE file_id = ? AND user_id = ? LIMIT 1
`

type GetRecordFileDocumentParams struct {
	FileID uint64
	UserID uint64
}

// The document a file is attached to (a file belongs to at most one document).
func (q *Queries) GetRecordFileDocument(ctx context.Context, arg GetRecordFileDocumentParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getRecordFileDocument, arg.FileID, arg.UserID)
	var document_id uint64
	err := row.Scan(&document_id)
	return document_id, err
}

const getRecordPregnancyProfileID = `-- name: GetRecordPregnancyProfileID :one
SELECT id FROM ` + "`" + `pregnancy_profiles` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetRecordPregnancyProfileIDParams struct {
	ID     uint64
	UserID uint64
}

// A pregnancy link target must be the user's own pregnancy profile.
func (q *Queries) GetRecordPregnancyProfileID(ctx context.Context, arg GetRecordPregnancyProfileIDParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getRecordPregnancyProfileID, arg.ID, arg.UserID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const insertRecordDocument = `-- name: InsertRecordDocument :execlastid
INSERT INTO ` + "`" + `record_documents` + "`" + ` (user_id, kind, title, document_date, ended_on, centre, doctor, note, review_state,
    created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?)
`

type InsertRecordDocumentParams struct {
	UserID       uint64
	Kind         string
	Title        sql.NullString
	DocumentDate civildate.NullDate
	EndedOn      civildate.NullDate
	Centre       sql.NullString
	Doctor       sql.NullString
	Note         sql.NullString
	ReviewState  string
	Now          sql.NullTime
}

func (q *Queries) InsertRecordDocument(ctx context.Context, arg InsertRecordDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertRecordDocument,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.DocumentDate,
		arg.EndedOn,
		arg.Centre,
		arg.Doctor,
		arg.Note,
		arg.ReviewState,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertRecordDocumentFile = `-- name: InsertRecordDocumentFile :exec
INSERT INTO ` + "`" + `record_document_files` + "`" + ` (user_id, document_id, file_id, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRecordDocumentFileParams struct {
	UserID     uint64
	DocumentID uint64
	FileID     uint64
	Position   uint8
	Now        sql.NullTime
}

func (q *Queries) InsertRecordDocumentFile(ctx context.Context, arg InsertRecordDocumentFileParams) error {
	_, err := q.db.ExecContext(ctx, insertRecordDocumentFile,
		arg.UserID,
		arg.DocumentID,
		arg.FileID,
		arg.Position,
		arg.Now,
		arg.Now,
	)
	return err
}

const listRecordDocumentFiles = `-- name: ListRecordDocumentFiles :many
SELECT file_id FROM ` + "`" + `record_document_files` + "`" + `
WHERE document_id = ? AND user_id = ?
ORDER BY position, id
`

type ListRecordDocumentFilesParams struct {
	DocumentID uint64
	UserID     uint64
}

func (q *Queries) ListRecordDocumentFiles(ctx context.Context, arg ListRecordDocumentFilesParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listRecordDocumentFiles, arg.DocumentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var file_id uint64
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordDocumentLinks = `-- name: ListRecordDocumentLinks :many
SELECT id, user_id, document_id, target_type, target_id, state, created_at, updated_at FROM ` + "`" + `record_document_links` + "`" + `
WHERE document_id = ? AND user_id = ?
ORDER BY created_at, id
`

type ListRecordDocumentLinksParams struct {
	DocumentID uint64
	UserID     uint64
}

func (q *Queries) ListRecordDocumentLinks(ctx context.Context, arg ListRecordDocumentLinksParams) ([]RecordDocumentLink, error) {
	rows, err := q.db.QueryContext(ctx, listRecordDocumentLinks, arg.DocumentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordDocumentLink{}
	for rows.Next() {
		var i RecordDocumentLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.TargetType,
			&i.TargetID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordDocuments = `-- name: ListRecordDocuments :many
SELECT d.id, d.user_id, d.kind, d.title, d.document_date, d.ended_on, d.centre, d.doctor, d.note, d.extracted, d.review_state, d.created_at, d.updated_at, CAST(COALESCE(d.document_date, DATE(d.created_at)) AS DATE) AS sort_date,
       (SELECT COUNT(*) FROM ` + "`" + `record_document_files` + "`" + ` f WHERE f.document_id = d.id AND f.user_id = d.user_id) AS file_count
FROM ` + "`" + `record_documents` + "`" + ` d
WHERE d.user_id = ?
ORDER BY sort_date DESC, d.id DESC
`

type ListRecordDocumentsRow struct {
	ID           uint64
	UserID       uint64
	Kind         string
	Title        sql.NullString
	DocumentDate civildate.NullDate
	EndedOn      civildate.NullDate
	Centre       sql.NullString
	Doctor       sql.NullString
	Note         sql.NullString
	Extracted    db.NullRawJSON
	ReviewState  string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	SortDate     civildate.Date
	FileCount    int64
}

// Newest first by the document's date (the upload day when the date is not known yet).
func (q *Queries) ListRecordDocuments(ctx context.Context, userID uint64) ([]ListRecordDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordDocumentsRow{}
	for rows.Next() {
		var i ListRecordDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.DocumentDate,
			&i.EndedOn,
			&i.Centre,
			&i.Doctor,
			&i.Note,
			&i.Extracted,
			&i.ReviewState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortDate,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRecordDocumentLinks = `-- name: ListUserRecordDocumentLinks :many
SELECT document_id, target_type, target_id, state FROM ` + "`" + `record_document_links` + "`" + `
WHERE user_id = ?
ORDER BY created_at, id
`

type ListUserRecordDocumentLinksRow struct {
	DocumentID uint64
	TargetType string
	TargetID   uint64
	State      string
}

// Every link of the user's documents (the timeline's badges).
func (q *Queries) ListUserRecordDocumentLinks(ctx context.Context, userID uint64) ([]ListUserRecordDocumentLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRecordDocumentLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRecordDocumentLinksRow{}
	for rows.Next() {
		var i ListUserRecordDocumentLinksRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.TargetType,
			&i.TargetID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecordDocument = `-- name: LockRecordDocument :one
SELECT id FROM ` + "`" + `record_documents` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1 FOR UPDATE
`

type LockRecordDocumentParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) LockRecordDocument(ctx context.Context, arg LockRecordDocumentParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockRecordDocument, arg.ID, arg.UserID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const lockRecordDocumentFiles = `-- name: LockRecordDocumentFiles :many
SELECT f.id, f.purpose, f.path FROM ` + "`" + `record_document_files` + "`" + ` r
JOIN ` + "`" + `files` + "`" + ` f ON f.id = r.file_id AND f.user_id = r.user_id
WHERE r.document_id = ? AND r.user_id = ?
ORDER BY r.position, r.id
FOR UPDATE
`

type LockRecordDocumentFilesParams struct {
	DocumentID uint64
	UserID     uint64
}

type LockRecordDocumentFilesRow struct {
	ID      uint64
	Purpose string
	Path    string
}

// The document's files with their storage rows, locked, inside the update / delete transaction.
func (q *Queries) LockRecordDocumentFiles(ctx context.Context, arg LockRecordDocumentFilesParams) ([]LockRecordDocumentFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, lockRecordDocumentFiles, arg.DocumentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRecordDocumentFilesRow{}
	for rows.Next() {
		var i LockRecordDocumentFilesRow
		if err := rows.Scan(&i.ID, &i.Purpose, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecordOwner = `-- name: LockRecordOwner :one
SELECT id FROM ` + "`" + `users` + "`" + ` WHERE id = ? FOR UPDATE
`

// First statement of a document create: the user row lock serialises one user's creates, so the MaxDocuments count
// that follows cannot race (same as internal/files LockOwner).
func (q *Queries) LockRecordOwner(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockRecordOwner, id)
	var id_2 uint64
	err := row.Scan(&id_2)
	return id_2, err
}

const updateRecordDocument = `-- name: UpdateRecordDocument :execrows
UPDATE ` + "`" + `record_documents` + "`" + `
SET kind = ?, title = ?, document_date = ?,
    ended_on = ?, centre = ?, doctor = ?, note = ?,
    review_state = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateRecordDocumentParams struct {
	Kind         string
	Title        sql.NullString
	DocumentDate civildate.NullDate
	EndedOn      civildate.NullDate
	Centre       sql.NullString
	Doctor       sql.NullString
	Note         sql.NullString
	ReviewState  string
	Now          sql.NullTime
	ID           uint64
	UserID       uint64
}

func (q *Queries) UpdateRecordDocument(ctx context.Context, arg UpdateRecordDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRecordDocument,
		arg.Kind,
		arg.Title,
		arg.DocumentDate,
		arg.EndedOn,
		arg.Centre,
		arg.Doctor,
		arg.Note,
		arg.ReviewState,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertRecordDocumentLink = `-- name: UpsertRecordDocumentLink :exec
INSERT INTO ` + "`" + `record_document_links` + "`" + ` (user_id, document_id, target_type, target_id, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?)
ON DUPLICATE KEY UPDATE state = VALUES(state), updated_at = VALUES(updated_at)
`

type UpsertRecordDocumentLinkParams struct {
	UserID     uint64
	DocumentID uint64
	TargetType string
	TargetID   uint64
	State      string
	Now        sql.NullTime
}

func (q *Queries) UpsertRecordDocumentLink(ctx context.Context, arg UpsertRecordDocumentLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecordDocumentLink,
		arg.UserID,
		arg.DocumentID,
		arg.TargetType,
		arg.TargetID,
		arg.State,
		arg.Now,
		arg.Now,
	)
	return err
}

const upsertRecordExtras = `-- name: UpsertRecordExtras :exec
INSERT INTO ` + "`" + `health_records` + "`" + ` (user_id, allergies_on_emergency_card, surgeries, family_history, created_at, updated_at)
VALUES (?, ?, ?, ?,
        ?, ?)
ON DUPLICATE KEY UPDATE allergies_on_emergency_card = VALUES(allergies_on_emergency_card),
    surgeries = VALUES(surgeries), family_history = VALUES(family_history), updated_at = VALUES(updated_at)
`

type UpsertRecordExtrasParams struct {
	UserID                   uint64
	AllergiesOnEmergencyCard bool
	Surgeries                db.NullRawJSON
	FamilyHistory            db.NullRawJSON
	Now                      sql.NullTime
}

// Only the CB-REC-01 columns: blood type and allergies stay with UpsertHealthRecord (B-N6-03).
func (q *Queries) UpsertRecordExtras(ctx context.Context, arg UpsertRecordExtrasParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecordExtras,
		arg.UserID,
		arg.AllergiesOnEmergencyCard,
		arg.Surgeries,
		arg.FamilyHistory,
		arg.Now,
		arg.Now,
	)
	return err
}
