// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountManualPregnancies(ctx context.Context, userID uint64) (int64, error)
	// A pregnancy that ended in a loss shows only as «ended»: the count is all the record reads of pregnancy_losses.
	CountRecordLosses(ctx context.Context, userID uint64) (int64, error)
	DeleteManualPregnancy(ctx context.Context, arg DeleteManualPregnancyParams) (int64, error)
	// Health record «پرونده سلامت من» (bloom B-N6-03; internal/healthrecord): the user-owned rows (health_records,
	// health_record_pregnancies) and the read-only views of other domains' tables the record aggregates. Every query is
	// scoped by user_id in the query itself (IDOR). pregnancy_losses is only ever counted: no column of a loss (type,
	// date, mood, the encrypted note) is read here.
	GetHealthRecord(ctx context.Context, userID uint64) (HealthRecord, error)
	GetManualPregnancy(ctx context.Context, arg GetManualPregnancyParams) (HealthRecordPregnancy, error)
	// The birth postpartum mode counts from (one per user).
	GetRecordBirth(ctx context.Context, userID uint64) (GetRecordBirthRow, error)
	GetRecordLifeProfile(ctx context.Context, userID uint64) (GetRecordLifeProfileRow, error)
	// The pregnancy profile (one per user): an active pregnancy is «ongoing»; blood_type + rh_factor are the fallback of
	// health_records.blood_type.
	GetRecordPregnancy(ctx context.Context, userID uint64) (GetRecordPregnancyRow, error)
	// $user->profile (hasOne: the first row in index order), only the columns the record shows.
	GetRecordProfile(ctx context.Context, userID uint64) (GetRecordProfileRow, error)
	GetRecordUser(ctx context.Context, userID uint64) (sql.NullString, error)
	InsertManualPregnancy(ctx context.Context, arg InsertManualPregnancyParams) (int64, error)
	ListManualPregnancies(ctx context.Context, userID uint64) ([]HealthRecordPregnancy, error)
	// The latest done checkups with the checkup's title / key / icon (custom checkups included: they are the user's own).
	ListRecordCheckups(ctx context.Context, arg ListRecordCheckupsParams) ([]ListRecordCheckupsRow, error)
	UpdateManualPregnancy(ctx context.Context, arg UpdateManualPregnancyParams) (int64, error)
	UpsertHealthRecord(ctx context.Context, arg UpsertHealthRecordParams) error
}

var _ Querier = (*Queries)(nil)
