#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Provision the staging access gate. Sourced by deploy.sh and deploy-stage.sh,
# both of which run from the repo root and define ssh_run().
#
# It writes /opt/ritme/stage-gate.conf on the SERVER — a server-only file, like
# stage.htpasswd, that rsync never touches. The proxy mounts it into conf.d as
# aa-stage-gate.conf, where its `map` blocks land at http level and define the
# variables deploy/vhost-stage.inc uses.
#
# Why a cookie and not just Basic auth: see the long comment in vhost-stage.inc.
# In one line — a request has exactly one Authorization header, the app needs it
# for `Bearer <token>`, so the gate has to live somewhere else.
#
# The token is generated once and then left alone: regenerating it on every
# deploy would log everyone out of staging for no reason.
# ─────────────────────────────────────────────────────────────────────────────

ensure_stage_gate() { # ensure_stage_gate <remote dir holding the file>
  local dir="$1" token

  # A pre-existing file is authoritative — never overwrite a live token.
  if ssh_run "grep -qs stage_auth_realm ${dir}/stage-gate.conf"; then
    return 0
  fi

  echo "==> Provisioning the staging access gate (${dir}/stage-gate.conf)..."
  token="$(openssl rand -hex 24)"

  # Generated locally and piped over, rather than built with a remote heredoc:
  # the nginx syntax is dense with $variables and quoting it twice through ssh
  # is how these files acquire silent typos.
  cat <<NGINX | ssh_run "cat > ${dir}/stage-gate.conf"
# Ritme staging access gate — GENERATED by deploy/stage-gate.sh.
# Server-only: never rsynced, never committed. Delete this file to rotate the
# token (everyone is then asked for the password again on their next visit).

# 1 once the visitor holds the gate cookie handed out after a successful
# password prompt.
map \$cookie_ritme_stage \$stage_cookie_ok {
    default 0;
    "${token}" 1;
}

# 1 for container-to-container traffic. The Next.js server calls
# /api/v1/languages and /languages/<code>/messages through this same proxy
# during SSR, with no password and no cookie to offer; without this the app
# silently falls back to its bundled locales on every staging page.
map \$remote_addr \$stage_internal {
    default 0;
    "~^127\\." 1;
    "~^10\\." 1;
    "~^172\\.(1[6-9]|2[0-9]|3[01])\\." 1;
}

# The realm string asks for a password; the literal \`off\` disables auth_basic.
map "\$stage_cookie_ok\$stage_internal" \$stage_auth_realm {
    "00" "Ritme staging";
    default off;
}

# The cookie value vhost-stage.inc hands out on an authenticated response.
map \$host \$stage_gate_token {
    default "${token}";
}
NGINX
}
