// Public API of the `pregnancy` entity. Import only from here (CLAUDE.md §3.3).

// ── Model: pure logic & config ─────────────────────────────────
export {
  clampWeek,
  derivePregnancyProgress,
  trimesterOfWeek,
  type PregnancyProgress,
  type Trimester,
} from './model/progress';
export { pickBilingual, resolveFlags } from './model/localize';
export {
  CONTENT_MODULE_ORDER,
  CRITICAL_SYMPTOMS,
  isCriticalSymptom,
  SYMPTOM_GROUPS,
  SYMPTOM_KEYS,
  TOTAL_WEEKS,
  WEEKLY_MENTAL,
} from './model/config';

// ── Model: types ───────────────────────────────────────────────
export type {
  AgeSource,
  AlertCounts,
  AlertLevel,
  AlertSummary,
  Bilingual,
  ContentModuleKey,
  EstimatedDueDate,
  FetalMovementInput,
  GestationalAge,
  MovementStatus,
  OnboardingInput,
  PregnancyActivation,
  PregnancyAlert,
  PregnancyEnums,
  PregnancyFlags,
  PregnancyProfile,
  PregnancyStatus,
  SymptomEnums,
  SymptomKey,
  SymptomLogInput,
  WeeklyContent,
  WeeklyEnums,
  WeeklyFaqItem,
  WeeklyLogInput,
} from './model/types';

// ── API: keys, hooks, fetchers ─────────────────────────────────
export { pregnancyKeys } from './api/keys';
export {
  // status & profile
  usePregnancyStatus,
  usePregnancyProfile,
  fetchPregnancyStatus,
  fetchPregnancyProfile,
  // enums
  usePregnancyEnums,
  useSymptomEnums,
  useWeeklyEnums,
  // content
  useWeeklyContent,
  fetchWeeklyContent,
  // daily symptoms
  useSymptomLog,
  useSaveSymptomLog,
  // weekly checkup
  useWeeklyLog,
  useSaveWeeklyLog,
  // fetal movement
  useFetalMovement,
  useSaveFetalMovement,
  // alerts
  usePregnancyAlerts,
  useAlertSummary,
  useAlertAction,
  useMarkAllAlertsRead,
  // mode & onboarding
  useActivatePregnancy,
  useDeactivatePregnancy,
  useCompleteOnboarding,
} from './api/queries';

// ── v2 (M7, `/pregnancy/v2/*`) — alongside v1 until the screens switch ──
export {
  ALERT_LEVELS_V2,
  ALERT_SERVER_ACTIONS,
  CARE_ITEM_KINDS,
  CARE_ITEM_STATES,
  CONFIDENCE_LEVELS,
  DATING_SOURCES,
  DAY_SYMPTOMS,
  HIGHLIGHT_ICONS,
  HIGHLIGHT_TONES,
  MOODS,
  MOODS_DISPLAY_ORDER,
  SEVERITIES,
  V2_MAX_WEEK,
  V2_MIN_WEEK,
  V2_TERM_WEEKS,
  VISIT_STAGES,
  WATER_MAX,
  WATER_MIN,
} from './model/v2-types';
export type {
  AlertActionV2,
  AlertContact,
  AlertLegendRow,
  AlertLevelV2,
  AlertServerAction,
  CalendarDayMarker,
  CalendarVisit,
  CareItem,
  CareItemKind,
  CareItemState,
  Confidence,
  ConfidenceLevel,
  DateRange,
  DatingPreview,
  DatingPreviewInput,
  DatingSource,
  DaySymptom,
  DaySymptoms,
  DueCard,
  GestationalAgeV2,
  HighlightIcon,
  HighlightTone,
  LastWeight,
  Mood,
  NextVisit,
  PregnancyAlertsV2,
  PregnancyAlertV2,
  PregnancyCalendar,
  PregnancyDay,
  PregnancyDayInput,
  PregnancyProgressV2,
  PregnancyReport,
  PregnancyToday,
  PregnancyWeek,
  ReportDay,
  ReportRange,
  ReportWeight,
  Severity,
  TrimesterSpan,
  VisitStage,
  WeekDetails,
  WeekHighlight,
  WeekRelation,
  WeekSource,
  WeekState,
  WeekStateInput,
  WeekSummary,
  WeekTask,
  WeekTip,
} from './model/v2-types';
export {
  applyDoneKeys,
  clampV2Week,
  datingPreviewBody,
  isDatingPreviewReady,
  defaultHighlightTone,
  highlightGlyph,
  isV2Week,
  moodGlyph,
  taskProgress,
  toggleDoneKey,
  trimesterFills,
  type TrimesterFill,
  weekRelation,
} from './model/v2';
export {
  datingPreviewSchema,
  pregnancyAlertsV2Schema,
  pregnancyAlertV2Schema,
  pregnancyCalendarSchema,
  pregnancyDaySchema,
  pregnancyReportSchema,
  pregnancyTodaySchema,
  pregnancyWeekSchema,
  weekStateSchema,
} from './api/v2-schema';
export {
  fetchDatingPreview,
  fetchPregnancyAlertsV2,
  fetchPregnancyCalendar,
  fetchPregnancyDay,
  fetchPregnancyReport,
  fetchPregnancyToday,
  fetchPregnancyWeek,
  useDatingPreview,
  usePregnancyAlertsV2,
  usePregnancyCalendar,
  usePregnancyDay,
  usePregnancyReport,
  usePregnancyToday,
  usePregnancyWeek,
} from './api/v2-queries';
