// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// HealthDataEngine::dailyLogFor(): $user->dailyHealthLogs()->whereDate('log_date', $date)->first().
	// Only the columns MessageManager::extractSymptoms can read exist here (see messages/manager).
	GetMessageDailyLog(ctx context.Context, arg GetMessageDailyLogParams) (GetMessageDailyLogRow, error)
	// $user->profile (hasOne: the first row in index order) — the columns the message system and
	// the legacy HealthDataEngine read.
	GetMessageProfile(ctx context.Context, userID uint64) (GetMessageProfileRow, error)
	// Queries of the smart-message system (backend/app/Services/MessageSystem, MessageController).
	// MessageContentRepository::rows(): every live (active + approved) row of one locale.
	ListLiveMessageContents(ctx context.Context, locale string) ([]ListLiveMessageContentsRow, error)
	// HealthDataEngine::getCycleHistories() (the engine sorts itself).
	ListMessageCycleHistories(ctx context.Context, userID uint64) ([]ListMessageCycleHistoriesRow, error)
	// MessageManager::buildContext(): the last 90 days of logs, newest first (PatternLayer input).
	ListMessageRecentLogs(ctx context.Context, arg ListMessageRecentLogsParams) ([]ListMessageRecentLogsRow, error)
}

var _ Querier = (*Queries)(nil)
