// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teen.sql

package store

import (
	"context"
	"database/sql"
)

const checkTeenKitItem = `-- name: CheckTeenKitItem :exec
INSERT IGNORE INTO ` + "`" + `teen_kit_checks` + "`" + ` (user_id, item_code, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type CheckTeenKitItemParams struct {
	UserID   uint64
	ItemCode string
	Now      sql.NullTime
}

func (q *Queries) CheckTeenKitItem(ctx context.Context, arg CheckTeenKitItemParams) error {
	_, err := q.db.ExecContext(ctx, checkTeenKitItem,
		arg.UserID,
		arg.ItemCode,
		arg.Now,
		arg.Now,
	)
	return err
}

const getTeenLifeMode = `-- name: GetTeenLifeMode :one
SELECT life_mode FROM ` + "`" + `user_life_profiles` + "`" + ` WHERE user_id = ? LIMIT 1
`

// The stored life-stage mode (bloom B-N2-01; no row / NULL = not teen).
func (q *Queries) GetTeenLifeMode(ctx context.Context, userID uint64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTeenLifeMode, userID)
	var life_mode sql.NullString
	err := row.Scan(&life_mode)
	return life_mode, err
}

const getTeenProfile = `-- name: GetTeenProfile :one

SELECT id, user_id, age_band, menarche, parent_note, created_at, updated_at FROM ` + "`" + `teen_profiles` + "`" + ` WHERE user_id = ? LIMIT 1
`

// Teen mode (CB-TEEN-01, goose 00029): onboarding answers, the school-kit checklist and the parent note. Minors' health
// data: every statement is scoped by user_id in the statement itself. The life-stage mode is bloom's
// user_life_profiles.life_mode; what a parent may see goes through internal/companion (type parent, teen sections).
func (q *Queries) GetTeenProfile(ctx context.Context, userID uint64) (TeenProfile, error) {
	row := q.db.QueryRowContext(ctx, getTeenProfile, userID)
	var i TeenProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgeBand,
		&i.Menarche,
		&i.ParentNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeenKitChecks = `-- name: ListTeenKitChecks :many
SELECT item_code FROM ` + "`" + `teen_kit_checks` + "`" + ` WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListTeenKitChecks(ctx context.Context, userID uint64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTeenKitChecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item_code string
		if err := rows.Scan(&item_code); err != nil {
			return nil, err
		}
		items = append(items, item_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeenParentNote = `-- name: SetTeenParentNote :execrows
UPDATE ` + "`" + `teen_profiles` + "`" + ` SET parent_note = ?, updated_at = ?
WHERE user_id = ?
`

type SetTeenParentNoteParams struct {
	ParentNote sql.NullString
	Now        sql.NullTime
	UserID     uint64
}

func (q *Queries) SetTeenParentNote(ctx context.Context, arg SetTeenParentNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTeenParentNote, arg.ParentNote, arg.Now, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uncheckTeenKitItem = `-- name: UncheckTeenKitItem :exec
DELETE FROM ` + "`" + `teen_kit_checks` + "`" + ` WHERE user_id = ? AND item_code = ?
`

type UncheckTeenKitItemParams struct {
	UserID   uint64
	ItemCode string
}

func (q *Queries) UncheckTeenKitItem(ctx context.Context, arg UncheckTeenKitItemParams) error {
	_, err := q.db.ExecContext(ctx, uncheckTeenKitItem, arg.UserID, arg.ItemCode)
	return err
}

const upsertTeenProfile = `-- name: UpsertTeenProfile :exec
INSERT INTO ` + "`" + `teen_profiles` + "`" + ` (user_id, age_band, menarche, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  age_band = VALUES(age_band),
  menarche = VALUES(menarche),
  updated_at = VALUES(updated_at)
`

type UpsertTeenProfileParams struct {
	UserID   uint64
	AgeBand  string
	Menarche string
	Now      sql.NullTime
}

// Onboarding answers (Teen_Onb); the parent note is kept.
func (q *Queries) UpsertTeenProfile(ctx context.Context, arg UpsertTeenProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertTeenProfile,
		arg.UserID,
		arg.AgeBand,
		arg.Menarche,
		arg.Now,
		arg.Now,
	)
	return err
}
