// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extract.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const applyExtractReview = `-- name: ApplyExtractReview :execrows
UPDATE ` + "`" + `record_documents` + "`" + `
SET document_date = ?, ended_on = ?, centre = ?,
    doctor = ?, review_state = ?, extracted = ?,
    updated_at = ?
WHERE id = ? AND user_id = ?
`

type ApplyExtractReviewParams struct {
	DocumentDate civildate.NullDate
	EndedOn      civildate.NullDate
	Centre       sql.NullString
	Doctor       sql.NullString
	ReviewState  string
	Extracted    db.NullRawJSON
	Now          sql.NullTime
	ID           uint64
	UserID       uint64
}

func (q *Queries) ApplyExtractReview(ctx context.Context, arg ApplyExtractReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyExtractReview,
		arg.DocumentDate,
		arg.EndedOn,
		arg.Centre,
		arg.Doctor,
		arg.ReviewState,
		arg.Extracted,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDocExtractCallsSince = `-- name: CountDocExtractCallsSince :one
SELECT COUNT(*) FROM ` + "`" + `ai_usage_logs` + "`" + `
WHERE user_id = ? AND feature = 'doc_extract' AND op = 'extract' AND created_at >= ?
`

type CountDocExtractCallsSinceParams struct {
	UserID sql.NullInt64
	Since  sql.NullTime
}

// Extraction calls of the user since a time, from the append-only AI usage log: deleting documents never resets the
// refund allowance of paid-but-useless extractions.
func (q *Queries) CountDocExtractCallsSince(ctx context.Context, arg CountDocExtractCallsSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocExtractCallsSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExtractDocument = `-- name: GetExtractDocument :one

SELECT id, user_id, kind, title, document_date, ended_on, centre, doctor, note, extracted, review_state, created_at, updated_at FROM ` + "`" + `record_documents` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetExtractDocumentParams struct {
	ID     uint64
	UserID uint64
}

// Record document extraction (canvas-build CB-REC-02; internal/healthrecord/extract). No table of its own: the job
// state lives in record_documents.extracted (key "job", never shown to clients) while review_state = 'pending'.
// Every user-facing query is scoped by user_id in the query itself (IDOR); the worker's queries take the id and the
// user id it read from the claimed row.
func (q *Queries) GetExtractDocument(ctx context.Context, arg GetExtractDocumentParams) (RecordDocument, error) {
	row := q.db.QueryRowContext(ctx, getExtractDocument, arg.ID, arg.UserID)
	var i RecordDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.DocumentDate,
		&i.EndedOn,
		&i.Centre,
		&i.Doctor,
		&i.Note,
		&i.Extracted,
		&i.ReviewState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtractUserName = `-- name: GetExtractUserName :one
SELECT name FROM ` + "`" + `users` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetExtractUserName(ctx context.Context, id uint64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getExtractUserName, id)
	var name sql.NullString
	err := row.Scan(&name)
	return name, err
}

const listExtractFileIDs = `-- name: ListExtractFileIDs :many
SELECT file_id FROM ` + "`" + `record_document_files` + "`" + `
WHERE document_id = ? AND user_id = ?
ORDER BY position, id
`

type ListExtractFileIDsParams struct {
	DocumentID uint64
	UserID     uint64
}

func (q *Queries) ListExtractFileIDs(ctx context.Context, arg ListExtractFileIDsParams) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listExtractFileIDs, arg.DocumentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var file_id uint64
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExtractions = `-- name: ListPendingExtractions :many
SELECT id, user_id FROM ` + "`" + `record_documents` + "`" + `
WHERE review_state = 'pending'
ORDER BY updated_at, id
LIMIT 20
FOR UPDATE SKIP LOCKED
`

type ListPendingExtractionsRow struct {
	ID     uint64
	UserID uint64
}

// Candidate documents for a worker (inside the claim transaction). SKIP LOCKED: concurrent workers never wait on,
// or both take, the same row; due / lease / attempts are decided in Go from the job JSON.
func (q *Queries) ListPendingExtractions(ctx context.Context) ([]ListPendingExtractionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingExtractions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingExtractionsRow{}
	for rows.Next() {
		var i ListPendingExtractionsRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExtractDocument = `-- name: LockExtractDocument :one
SELECT id, user_id, kind, title, document_date, ended_on, centre, doctor, note, extracted, review_state, created_at, updated_at FROM ` + "`" + `record_documents` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1 FOR UPDATE
`

type LockExtractDocumentParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) LockExtractDocument(ctx context.Context, arg LockExtractDocumentParams) (RecordDocument, error) {
	row := q.db.QueryRowContext(ctx, lockExtractDocument, arg.ID, arg.UserID)
	var i RecordDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.DocumentDate,
		&i.EndedOn,
		&i.Centre,
		&i.Doctor,
		&i.Note,
		&i.Extracted,
		&i.ReviewState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockExtractPregnancyProfile = `-- name: LockExtractPregnancyProfile :one
SELECT id FROM ` + "`" + `pregnancy_profiles` + "`" + ` WHERE user_id = ? LIMIT 1 FOR UPDATE
`

// The user's pregnancy profile row, locked for the dating update (read through internal/pregnancy afterwards).
func (q *Queries) LockExtractPregnancyProfile(ctx context.Context, userID uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockExtractPregnancyProfile, userID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const setExtractJob = `-- name: SetExtractJob :execrows
UPDATE ` + "`" + `record_documents` + "`" + `
SET extracted = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND review_state = 'pending'
`

type SetExtractJobParams struct {
	Extracted db.NullRawJSON
	Now       sql.NullTime
	ID        uint64
	UserID    uint64
}

// A job bookkeeping write (claim / retry). updated_at moves on, so a claimed or backed-off job goes to the back of
// ListPendingExtractions' order and can never starve the jobs behind it (security audit L7).
func (q *Queries) SetExtractJob(ctx context.Context, arg SetExtractJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setExtractJob,
		arg.Extracted,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setExtractState = `-- name: SetExtractState :execrows
UPDATE ` + "`" + `record_documents` + "`" + `
SET review_state = ?, extracted = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type SetExtractStateParams struct {
	ReviewState string
	Extracted   db.NullRawJSON
	Now         sql.NullTime
	ID          uint64
	UserID      uint64
}

func (q *Queries) SetExtractState(ctx context.Context, arg SetExtractStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setExtractState,
		arg.ReviewState,
		arg.Extracted,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertExtractDocumentLink = `-- name: UpsertExtractDocumentLink :exec
INSERT INTO ` + "`" + `record_document_links` + "`" + ` (user_id, document_id, target_type, target_id, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?)
ON DUPLICATE KEY UPDATE state = VALUES(state), updated_at = VALUES(updated_at)
`

type UpsertExtractDocumentLinkParams struct {
	UserID     uint64
	DocumentID uint64
	TargetType string
	TargetID   uint64
	State      string
	Now        sql.NullTime
}

// The «where used» link of the dating update, inside the same transaction (same statement as healthrecord's
// UpsertRecordDocumentLink).
func (q *Queries) UpsertExtractDocumentLink(ctx context.Context, arg UpsertExtractDocumentLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertExtractDocumentLink,
		arg.UserID,
		arg.DocumentID,
		arg.TargetType,
		arg.TargetID,
		arg.State,
		arg.Now,
		arg.Now,
	)
	return err
}
