/**
 * data-module="pwa" (L8-02) — mounted once per page by the site layout. Does four things:
 *
 *  1. Registers /sw.js (production builds only; the worker is generated by tools/build-sw.mjs).
 *  2. Two-tier update. Channels: the service worker (a new worker reaches "installed" while one controls the page)
 *     and polling /pwa/version.json (no-store) on load, on focus/visible (throttled) and every 15 minutes.
 *     - soft:   a newer build is out → non-blocking toast «نسخه جدید آماده است»; «به‌روزرسانی» activates the waiting
 *               worker (SKIP_WAITING) and reloads once on controllerchange.
 *     - forced: this build is older than min_build_id → full-screen blocking view (inert page, focus trapped, Escape
 *               and Back blocked); its button activates/updates the worker, drops cached pages and reloads. After
 *               the reload the check runs again, so an old build can never be used.
 *  3. Install prompt: Chromium `beforeinstallprompt` banner, iOS Safari «افزودن به صفحه اصلی» hint sheet. Never on
 *     the first page view, never when installed; a dismissal is remembered for 30 days.
 *  4. [data-pwa-retry] buttons (the offline page) reload the page.
 *
 * All UI is built here with Tailwind classes (no inline styles, no inline scripts); copy is Persian.
 */
import { buildStamp, updateTier } from '../sw/version.js';

/* global __BUILD_ID__ */
const BUILD_ID = typeof __BUILD_ID__ === 'string' ? __BUILD_ID__ : 'dev';

const VERSION_URL = '/pwa/version.json';
const SW_URL = '/sw.js';
const POLL_MS = 15 * 60 * 1000;
const FOCUS_THROTTLE_MS = 60 * 1000;
const DISMISS_MS = 30 * 24 * 60 * 60 * 1000;
const KEY_VIEWS = 'ritme:pwa:views';
const KEY_DISMISSED = 'ritme:pwa:install-dismissed';

const TEXT = {
    softTitle: 'نسخه جدید آماده است',
    softBody: 'برای دیدن آخرین تغییرها صفحه را تازه کن.',
    softAction: 'به‌روزرسانی',
    later: 'بعداً',
    forcedTitle: 'این نسخه دیگر پشتیبانی نمی‌شود',
    forcedBody: 'برای ادامه، ریتمی را به‌روزرسانی کن. چند ثانیه بیشتر طول نمی‌کشد.',
    forcedAction: 'به‌روزرسانی',
    updating: 'در حال به‌روزرسانی…',
    installTitle: 'ریتمی را روی صفحه اصلی داشته باش',
    installBody: 'نصب سبک است و بدون فروشگاه برنامه، با یک لمس باز می‌شود.',
    installAction: 'نصب',
    installDismiss: 'نه، ممنون',
    iosTitle: 'افزودن ریتمی به صفحه اصلی',
    iosStep1: 'در نوار Safari دکمه «اشتراک‌گذاری» (مربع با پیکان رو به بالا) را بزن.',
    iosStep2: 'گزینه «افزودن به صفحه اصلی» (Add to Home Screen) را انتخاب کن.',
    iosStep3: 'روی «افزودن» بزن؛ آیکن ریتمی کنار برنامه‌های دیگرت قرار می‌گیرد.',
    iosClose: 'متوجه شدم',
};

const storage = {
    get(key) {
        try {
            return window.localStorage.getItem(key);
        } catch {
            return null;
        }
    },
    set(key, value) {
        try {
            window.localStorage.setItem(key, value);
        } catch {
            // private mode / blocked storage: the banner simply comes back later
        }
    },
};

/** Tiny DOM builder: h('div', {class: '…', role: 'status'}, [children | 'text']). */
function h(tag, attrs = {}, children = []) {
    const element = document.createElement(tag);
    for (const [name, value] of Object.entries(attrs)) {
        if (value === false || value === null || value === undefined) continue;
        if (name.startsWith('on')) element.addEventListener(name.slice(2), value);
        else element.setAttribute(name, value === true ? '' : String(value));
    }
    for (const child of [].concat(children)) {
        if (child !== null && child !== undefined) element.append(child);
    }

    return element;
}

const BUTTON = 'inline-flex min-h-11 cursor-pointer items-center justify-center rounded-full px-5 text-base font-extrabold transition-colors';

const state = {
    registration: null,
    reloading: false,
    soft: null,
    forced: null,
    install: null,
    deferredPrompt: null,
    lastCheck: 0,
};

/* ------------------------------------------------------------------ service worker */

function reloadOnce() {
    if (state.reloading) return;
    state.reloading = true;
    window.location.reload();
}

function activateWaiting() {
    const waiting = state.registration && state.registration.waiting;
    if (!waiting) return false;
    state.reloading = false;
    navigator.serviceWorker.addEventListener('controllerchange', reloadOnce, { once: true });
    waiting.postMessage({ type: 'SKIP_WAITING' });

    return true;
}

function watchWorker(registration) {
    const promptIfWaiting = () => {
        if (registration.waiting && navigator.serviceWorker.controller) showSoft();
    };
    promptIfWaiting();
    registration.addEventListener('updatefound', () => {
        const worker = registration.installing;
        if (!worker) return;
        worker.addEventListener('statechange', () => {
            if (worker.state !== 'installed') return;
            if (state.forced) applyForced();
            else promptIfWaiting();
        });
    });
}

async function registerWorker() {
    if (!import.meta.env.PROD || !('serviceWorker' in navigator)) return;
    try {
        state.registration = await navigator.serviceWorker.register(SW_URL, { scope: '/', updateViaCache: 'none' });
        watchWorker(state.registration);
    } catch (error) {
        console.error('[ritme] service worker registration failed', error);
    }
}

/* ------------------------------------------------------------------ version polling */

async function checkVersion(force = false) {
    if (buildStamp(BUILD_ID) === null) return; // dev server: nothing to compare
    const now = Date.now();
    if (!force && now - state.lastCheck < FOCUS_THROTTLE_MS) return;
    state.lastCheck = now;

    let info;
    try {
        const response = await fetch(VERSION_URL, { cache: 'no-store', credentials: 'omit', headers: { Accept: 'application/json' } });
        if (!response.ok) return;
        info = await response.json();
    } catch {
        return; // offline: try again later
    }

    const tier = updateTier(BUILD_ID, info);
    if (tier === 'forced') {
        showForced(typeof info.message === 'string' ? info.message : '');
    } else if (tier === 'soft') {
        state.registration?.update().catch(() => undefined);
        showSoft(typeof info.message === 'string' ? info.message : '');
    }
}

/* ------------------------------------------------------------------ soft tier */

function showSoft(message = '') {
    if (state.soft || state.forced) return;
    hideInstall();

    const close = () => {
        state.soft?.remove();
        state.soft = null;
    };
    state.soft = h('div', {
        role: 'status',
        'aria-live': 'polite',
        class: 'fixed inset-x-4 bottom-4 z-50 mx-auto flex max-w-120 items-center gap-4 rounded-3xl bg-night p-4 ps-5 text-on-night shadow-float max-sm:flex-col max-sm:items-stretch',
    }, [
        h('div', { class: 'flex flex-1 flex-col gap-1' }, [
            h('strong', { class: 'text-base font-extrabold' }, TEXT.softTitle),
            h('span', { class: 'text-sm leading-relaxed text-on-night-muted' }, message || TEXT.softBody),
        ]),
        h('div', { class: 'flex items-center gap-2' }, [
            h('button', {
                type: 'button',
                class: `${BUTTON} bg-primary text-white hover:bg-primary-hover max-sm:flex-1`,
                onclick: () => {
                    if (!activateWaiting()) reloadOnce();
                },
            }, TEXT.softAction),
            h('button', { type: 'button', class: `${BUTTON} text-on-night-muted hover:text-on-night`, onclick: close }, TEXT.later),
        ]),
    ]);
    document.body.append(state.soft);
}

/* ------------------------------------------------------------------ forced tier */

async function applyForced() {
    const button = state.forced?.querySelector('button');
    if (button) {
        button.disabled = true;
        button.textContent = TEXT.updating;
    }

    if (activateWaiting()) {
        setTimeout(reloadOnce, 4000); // controllerchange normally reloads first
        return;
    }

    try {
        await state.registration?.update();
    } catch {
        // offline or worker unavailable: the reload below still fetches fresh HTML when online
    }
    if (state.registration?.waiting && activateWaiting()) {
        setTimeout(reloadOnce, 4000);
        return;
    }
    if (state.registration?.installing) return; // watchWorker calls applyForced again once installed

    try {
        const keys = await caches.keys();
        await Promise.all(keys.filter((key) => key.startsWith('ritme-pages-')).map((key) => caches.delete(key)));
    } catch {
        // Cache API unavailable
    }
    reloadOnce();
}

function blockEscape(event) {
    if (event.key === 'Escape') {
        event.preventDefault();
        event.stopPropagation();
    }
}

function showForced(message = '') {
    if (state.forced) return;
    state.soft?.remove();
    state.soft = null;
    hideInstall();

    for (const child of document.body.children) {
        child.setAttribute('inert', '');
        child.setAttribute('aria-hidden', 'true');
    }

    const button = h('button', {
        type: 'button',
        class: `${BUTTON} min-h-13 w-full bg-primary px-8 text-lg text-white hover:bg-primary-hover disabled:cursor-wait disabled:opacity-70`,
        onclick: applyForced,
    }, TEXT.forcedAction);

    state.forced = h('div', {
        role: 'alertdialog',
        'aria-modal': 'true',
        'aria-labelledby': 'pwa-forced-title',
        'aria-describedby': 'pwa-forced-body',
        class: 'fixed inset-0 z-100 flex items-center justify-center bg-night bg-hero-glow p-6 text-on-night',
    }, [
        h('div', { class: 'flex w-full max-w-110 flex-col items-center gap-5 text-center' }, [
            h('h2', { id: 'pwa-forced-title', class: 'm-0 font-display text-d-sm leading-display' }, TEXT.forcedTitle),
            h('p', { id: 'pwa-forced-body', class: 'm-0 text-lg leading-loose text-on-night-muted' }, message || TEXT.forcedBody),
            button,
        ]),
    ]);
    document.body.append(state.forced);
    document.documentElement.classList.add('overflow-hidden');

    // Focus stays on the single action; Escape and Back cannot leave the screen.
    button.focus();
    document.addEventListener('focusin', (event) => {
        if (state.forced && !state.forced.contains(event.target)) button.focus();
    });
    document.addEventListener('keydown', blockEscape, true);
    try {
        window.history.pushState({ pwaForced: true }, '');
    } catch {
        // history unavailable (sandboxed): nothing to block
    }
    window.addEventListener('popstate', () => {
        try {
            window.history.pushState({ pwaForced: true }, '');
        } catch {
            // ignore
        }
    });
}

/* ------------------------------------------------------------------ install prompt */

const isStandalone = () => window.matchMedia('(display-mode: standalone)').matches || navigator.standalone === true;

function installAllowed() {
    if (isStandalone() || state.soft || state.forced) return false;
    if (Number(storage.get(KEY_VIEWS) || 0) < 2) return false; // never on the first page view
    const dismissed = Number(storage.get(KEY_DISMISSED) || 0);

    return !(dismissed && Date.now() - dismissed < DISMISS_MS);
}

function hideInstall(remember = false) {
    if (remember) storage.set(KEY_DISMISSED, String(Date.now()));
    state.install?.remove();
    state.install = null;
}

function showInstallBanner() {
    if (state.install || !state.deferredPrompt || !installAllowed()) return;

    state.install = h('div', {
        role: 'region',
        'aria-label': TEXT.installTitle,
        class: 'fixed inset-x-4 bottom-4 z-40 mx-auto flex max-w-120 items-center gap-4 rounded-3xl border border-line bg-surface p-4 ps-5 text-ink shadow-card max-sm:flex-col max-sm:items-stretch',
    }, [
        h('div', { class: 'flex flex-1 flex-col gap-1' }, [
            h('strong', { class: 'text-base font-extrabold' }, TEXT.installTitle),
            h('span', { class: 'text-sm leading-relaxed text-muted' }, TEXT.installBody),
        ]),
        h('div', { class: 'flex items-center gap-2' }, [
            h('button', {
                type: 'button',
                class: `${BUTTON} bg-primary text-white hover:bg-primary-hover max-sm:flex-1`,
                onclick: async () => {
                    const prompt = state.deferredPrompt;
                    state.deferredPrompt = null;
                    hideInstall();
                    if (!prompt) return;
                    prompt.prompt();
                    try {
                        const choice = await prompt.userChoice;
                        if (choice.outcome !== 'accepted') storage.set(KEY_DISMISSED, String(Date.now()));
                    } catch {
                        // ignore
                    }
                },
            }, TEXT.installAction),
            h('button', { type: 'button', class: `${BUTTON} text-muted hover:text-ink`, onclick: () => hideInstall(true) }, TEXT.installDismiss),
        ]),
    ]);
    document.body.append(state.install);
}

function isIosSafari() {
    const ua = navigator.userAgent;
    const ios = /iphone|ipad|ipod/i.test(ua) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

    return ios && /safari/i.test(ua) && !/crios|fxios|edgios|opios/i.test(ua);
}

function showIosHint() {
    if (state.install || !installAllowed()) return;

    const steps = [TEXT.iosStep1, TEXT.iosStep2, TEXT.iosStep3];
    const close = h('button', { type: 'button', class: `${BUTTON} w-full bg-primary text-white hover:bg-primary-hover`, onclick: () => hideInstall(true) }, TEXT.iosClose);
    state.install = h('div', {
        role: 'dialog',
        'aria-modal': 'false',
        'aria-labelledby': 'pwa-ios-title',
        class: 'fixed inset-x-0 bottom-0 z-40 mx-auto flex max-w-140 flex-col gap-4 rounded-t-4xl border border-line bg-surface p-6 pb-8 text-ink shadow-card',
    }, [
        h('h2', { id: 'pwa-ios-title', class: 'm-0 text-xl font-extrabold' }, TEXT.iosTitle),
        h('ol', { class: 'm-0 flex list-none flex-col gap-3 p-0' }, steps.map((step, index) => h('li', { class: 'flex items-start gap-3 text-base leading-relaxed text-muted' }, [
            h('span', { 'aria-hidden': 'true', class: 'inline-flex size-7 shrink-0 items-center justify-center rounded-full bg-canvas text-sm font-extrabold text-primary' }, (index + 1).toLocaleString('fa-IR')),
            h('span', {}, step),
        ]))),
        close,
    ]);
    state.install.addEventListener('keydown', (event) => {
        if (event.key === 'Escape') hideInstall(true);
    });
    document.body.append(state.install);
}

function setupInstall() {
    if (isStandalone()) return;
    storage.set(KEY_VIEWS, String(Number(storage.get(KEY_VIEWS) || 0) + 1));

    window.addEventListener('beforeinstallprompt', (event) => {
        event.preventDefault();
        state.deferredPrompt = event;
        setTimeout(showInstallBanner, 4000);
    });
    window.addEventListener('appinstalled', () => {
        state.deferredPrompt = null;
        hideInstall(true);
    });
    if (isIosSafari()) setTimeout(showIosHint, 6000);
}

/* ------------------------------------------------------------------ boot */

export default () => {
    document.querySelectorAll('[data-pwa-retry]').forEach((button) => {
        button.hidden = false;
        button.addEventListener('click', () => window.location.reload());
    });

    registerWorker().then(() => checkVersion(true));
    setupInstall();

    document.addEventListener('visibilitychange', () => {
        if (document.visibilityState !== 'visible') return;
        state.registration?.update().catch(() => undefined);
        checkVersion();
    });
    window.addEventListener('focus', () => checkVersion());
    setInterval(() => checkVersion(true), POLL_MS);
};
