// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const adminCheckupTypeKeyExists = `-- name: AdminCheckupTypeKeyExists :one
SELECT EXISTS(SELECT 1 FROM ` + "`" + `checkup_types` + "`" + ` WHERE ` + "`" + `key` + "`" + ` = ?) AS found
`

func (q *Queries) AdminCheckupTypeKeyExists(ctx context.Context, key sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminCheckupTypeKeyExists, key)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const checkupOverdueUsersByType = `-- name: CheckupOverdueUsersByType :many
SELECT r.checkup_type_id, COUNT(DISTINCT r.user_id) AS overdue_users
FROM ` + "`" + `checkup_records` + "`" + ` r
JOIN ` + "`" + `checkup_types` + "`" + ` t ON t.id = r.checkup_type_id AND t.user_id IS NULL
WHERE NOT EXISTS (
        SELECT 1 FROM ` + "`" + `checkup_records` + "`" + ` n
        WHERE n.user_id = r.user_id AND n.checkup_type_id = r.checkup_type_id
          AND (n.done_on > r.done_on OR (n.done_on = r.done_on AND n.id > r.id)))
  AND NOT EXISTS (
        SELECT 1 FROM ` + "`" + `user_checkup_settings` + "`" + ` s
        WHERE s.user_id = r.user_id AND s.checkup_type_id = r.checkup_type_id AND s.enabled = 0)
  AND COALESCE(r.next_due_on,
               DATE_ADD(r.done_on, INTERVAL COALESCE(t.interval_months_max, t.interval_months) MONTH))
      < ?
GROUP BY r.checkup_type_id
`

type CheckupOverdueUsersByTypeRow struct {
	CheckupTypeID uint64
	OverdueUsers  int64
}

// Per catalog type: users whose latest record (ties → higher id) is past its due-by date, i.e.
// next_due_on ?? done_on + (interval_months_max ?? interval_months) months (MariaDB clamps to the month
// end like the engine), strictly before `today`. Users who switched the type off are left out. This is
// the calendar approximation of the engine's `overdue` (it ignores cycle windows, age and pregnancy).
func (q *Queries) CheckupOverdueUsersByType(ctx context.Context, today civildate.NullDate) ([]CheckupOverdueUsersByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, checkupOverdueUsersByType, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupOverdueUsersByTypeRow{}
	for rows.Next() {
		var i CheckupOverdueUsersByTypeRow
		if err := rows.Scan(&i.CheckupTypeID, &i.OverdueUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkupRecordStatsByType = `-- name: CheckupRecordStatsByType :many
SELECT r.checkup_type_id,
       COUNT(*) AS records_total,
       COUNT(DISTINCT r.user_id) AS users_with_records,
       CAST(SUM(CASE WHEN r.done_on >= ? THEN 1 ELSE 0 END) AS SIGNED) AS records_recent
FROM ` + "`" + `checkup_records` + "`" + ` r
JOIN ` + "`" + `checkup_types` + "`" + ` t ON t.id = r.checkup_type_id AND t.user_id IS NULL
GROUP BY r.checkup_type_id
`

type CheckupRecordStatsByTypeRow struct {
	CheckupTypeID    uint64
	RecordsTotal     int64
	UsersWithRecords int64
	RecordsRecent    int64
}

// Per catalog type with records: all records, distinct users, and records done on or after `since`.
func (q *Queries) CheckupRecordStatsByType(ctx context.Context, since civildate.Date) ([]CheckupRecordStatsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, checkupRecordStatsByType, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupRecordStatsByTypeRow{}
	for rows.Next() {
		var i CheckupRecordStatsByTypeRow
		if err := rows.Scan(
			&i.CheckupTypeID,
			&i.RecordsTotal,
			&i.UsersWithRecords,
			&i.RecordsRecent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminCheckupTypes = `-- name: CountAdminCheckupTypes :one

SELECT COUNT(*) FROM ` + "`" + `checkup_types` + "`" + `
WHERE user_id IS NULL
  AND (IFNULL(` + "`" + `key` + "`" + `, '') LIKE CAST(? AS CHAR)
       OR title LIKE CAST(? AS CHAR) OR title LIKE CAST(? AS CHAR))
  AND is_active >= ? AND is_active <= ?
`

type CountAdminCheckupTypesParams struct {
	Pattern     interface{}
	JsonPattern interface{}
	ActiveMin   bool
	ActiveMax   bool
}

// Checkups admin catalog (T-M4-03): /api/admin/v1/checkup-types. Every query is limited to the shared
// catalog (`user_id IS NULL`); users' custom checkups are never listed, shown, changed or counted here.
func (q *Queries) CountAdminCheckupTypes(ctx context.Context, arg CountAdminCheckupTypesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminCheckupTypes,
		arg.Pattern,
		arg.Pattern,
		arg.JsonPattern,
		arg.ActiveMin,
		arg.ActiveMax,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckupRecordsOfType = `-- name: CountCheckupRecordsOfType :one
SELECT COUNT(*) FROM ` + "`" + `checkup_records` + "`" + ` WHERE checkup_type_id = ?
`

func (q *Queries) CountCheckupRecordsOfType(ctx context.Context, checkupTypeID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckupRecordsOfType, checkupTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminCheckupType = `-- name: CreateAdminCheckupType :execresult
INSERT INTO ` + "`" + `checkup_types` + "`" + ` (` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone,
                             interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to,
                             remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy,
                             audiences, is_active, sort_order, source_note, created_at, updated_at)
VALUES (?, NULL, ?, ?, ?, ?,
        ?, ?, ?, ?,
        ?, ?, ?, ?,
        ?, ?, ?, ?,
        ?, ?, ?, ?, ?,
        ?, ?, ?)
`

type CreateAdminCheckupTypeParams struct {
	TypeKey           sql.NullString
	Category          string
	Title             json.RawMessage
	Subtitle          db.NullRawJSON
	Why               db.NullRawJSON
	PerformedBy       string
	Icon              sql.NullString
	Tone              string
	IntervalMonths    uint16
	IntervalMonthsMax sql.NullInt16
	AgeMin            sql.NullInt16
	AgeMax            sql.NullInt16
	CycleDayFrom      sql.NullInt16
	CycleDayTo        sql.NullInt16
	RemindLeadDays    uint16
	PrepSteps         db.NullRawJSON
	GuideSteps        db.NullRawJSON
	FindingOptions    db.NullRawJSON
	HideInPregnancy   bool
	Audiences         db.NullRawJSON
	IsActive          bool
	SortOrder         int32
	SourceNote        sql.NullString
	Now               sql.NullTime
}

func (q *Queries) CreateAdminCheckupType(ctx context.Context, arg CreateAdminCheckupTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdminCheckupType,
		arg.TypeKey,
		arg.Category,
		arg.Title,
		arg.Subtitle,
		arg.Why,
		arg.PerformedBy,
		arg.Icon,
		arg.Tone,
		arg.IntervalMonths,
		arg.IntervalMonthsMax,
		arg.AgeMin,
		arg.AgeMax,
		arg.CycleDayFrom,
		arg.CycleDayTo,
		arg.RemindLeadDays,
		arg.PrepSteps,
		arg.GuideSteps,
		arg.FindingOptions,
		arg.HideInPregnancy,
		arg.Audiences,
		arg.IsActive,
		arg.SortOrder,
		arg.SourceNote,
		arg.Now,
		arg.Now,
	)
}

const deleteUnusedAdminCheckupType = `-- name: DeleteUnusedAdminCheckupType :execresult
DELETE FROM ` + "`" + `checkup_types` + "`" + `
WHERE ` + "`" + `checkup_types` + "`" + `.id = ? AND ` + "`" + `checkup_types` + "`" + `.user_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM ` + "`" + `checkup_records` + "`" + ` r WHERE r.checkup_type_id = ?)
`

type DeleteUnusedAdminCheckupTypeParams struct {
	TypeID uint64
}

// Atomic "refuse if records exist": the FK would otherwise cascade-delete users' records.
func (q *Queries) DeleteUnusedAdminCheckupType(ctx context.Context, arg DeleteUnusedAdminCheckupTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUnusedAdminCheckupType, arg.TypeID, arg.TypeID)
}

const getAdminCheckupType = `-- name: GetAdminCheckupType :one
SELECT id, ` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone, interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to, remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy, is_active, sort_order, source_note, created_at, updated_at, audiences FROM ` + "`" + `checkup_types` + "`" + ` WHERE id = ? AND user_id IS NULL LIMIT 1
`

func (q *Queries) GetAdminCheckupType(ctx context.Context, id uint64) (CheckupType, error) {
	row := q.db.QueryRowContext(ctx, getAdminCheckupType, id)
	var i CheckupType
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Subtitle,
		&i.Why,
		&i.PerformedBy,
		&i.Icon,
		&i.Tone,
		&i.IntervalMonths,
		&i.IntervalMonthsMax,
		&i.AgeMin,
		&i.AgeMax,
		&i.CycleDayFrom,
		&i.CycleDayTo,
		&i.RemindLeadDays,
		&i.PrepSteps,
		&i.GuideSteps,
		&i.FindingOptions,
		&i.HideInPregnancy,
		&i.IsActive,
		&i.SortOrder,
		&i.SourceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Audiences,
	)
	return i, err
}

const listAdminCheckupTypeIDs = `-- name: ListAdminCheckupTypeIDs :many
SELECT id FROM ` + "`" + `checkup_types` + "`" + ` WHERE user_id IS NULL ORDER BY sort_order, id
`

// The whole catalog in display order (reorder check, stats).
func (q *Queries) ListAdminCheckupTypeIDs(ctx context.Context) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, listAdminCheckupTypeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminCheckupTypes = `-- name: ListAdminCheckupTypes :many
SELECT id, ` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone, interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to, remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy, is_active, sort_order, source_note, created_at, updated_at, audiences FROM ` + "`" + `checkup_types` + "`" + `
WHERE user_id IS NULL
  AND (IFNULL(` + "`" + `key` + "`" + `, '') LIKE CAST(? AS CHAR)
       OR title LIKE CAST(? AS CHAR) OR title LIKE CAST(? AS CHAR))
  AND is_active >= ? AND is_active <= ?
ORDER BY sort_order, id
LIMIT ? OFFSET ?
`

type ListAdminCheckupTypesParams struct {
	Pattern     interface{}
	JsonPattern interface{}
	ActiveMin   bool
	ActiveMax   bool
	Limit       int32
	Offset      int32
}

func (q *Queries) ListAdminCheckupTypes(ctx context.Context, arg ListAdminCheckupTypesParams) ([]CheckupType, error) {
	rows, err := q.db.QueryContext(ctx, listAdminCheckupTypes,
		arg.Pattern,
		arg.Pattern,
		arg.JsonPattern,
		arg.ActiveMin,
		arg.ActiveMax,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupType{}
	for rows.Next() {
		var i CheckupType
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Subtitle,
			&i.Why,
			&i.PerformedBy,
			&i.Icon,
			&i.Tone,
			&i.IntervalMonths,
			&i.IntervalMonthsMax,
			&i.AgeMin,
			&i.AgeMax,
			&i.CycleDayFrom,
			&i.CycleDayTo,
			&i.RemindLeadDays,
			&i.PrepSteps,
			&i.GuideSteps,
			&i.FindingOptions,
			&i.HideInPregnancy,
			&i.IsActive,
			&i.SortOrder,
			&i.SourceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Audiences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAdminCheckupTypeSortOrder = `-- name: NextAdminCheckupTypeSortOrder :one
SELECT CAST(COALESCE(MAX(sort_order), 0) + 1 AS SIGNED) AS next_sort_order
FROM ` + "`" + `checkup_types` + "`" + ` WHERE user_id IS NULL
`

func (q *Queries) NextAdminCheckupTypeSortOrder(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAdminCheckupTypeSortOrder)
	var next_sort_order int64
	err := row.Scan(&next_sort_order)
	return next_sort_order, err
}

const setAdminCheckupTypeSortOrder = `-- name: SetAdminCheckupTypeSortOrder :exec
UPDATE ` + "`" + `checkup_types` + "`" + ` SET sort_order = ?, updated_at = ?
WHERE id = ? AND user_id IS NULL
`

type SetAdminCheckupTypeSortOrderParams struct {
	SortOrder int32
	Now       sql.NullTime
	ID        uint64
}

func (q *Queries) SetAdminCheckupTypeSortOrder(ctx context.Context, arg SetAdminCheckupTypeSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, setAdminCheckupTypeSortOrder, arg.SortOrder, arg.Now, arg.ID)
	return err
}

const updateAdminCheckupType = `-- name: UpdateAdminCheckupType :exec
UPDATE ` + "`" + `checkup_types` + "`" + `
SET category = ?, title = ?, subtitle = ?, why = ?,
    performed_by = ?, icon = ?, tone = ?,
    interval_months = ?, interval_months_max = ?,
    age_min = ?, age_max = ?,
    cycle_day_from = ?, cycle_day_to = ?,
    remind_lead_days = ?, prep_steps = ?,
    guide_steps = ?, finding_options = ?,
    hide_in_pregnancy = ?, audiences = ?, is_active = ?,
    sort_order = ?, source_note = ?, updated_at = ?
WHERE id = ? AND user_id IS NULL
`

type UpdateAdminCheckupTypeParams struct {
	Category          string
	Title             json.RawMessage
	Subtitle          db.NullRawJSON
	Why               db.NullRawJSON
	PerformedBy       string
	Icon              sql.NullString
	Tone              string
	IntervalMonths    uint16
	IntervalMonthsMax sql.NullInt16
	AgeMin            sql.NullInt16
	AgeMax            sql.NullInt16
	CycleDayFrom      sql.NullInt16
	CycleDayTo        sql.NullInt16
	RemindLeadDays    uint16
	PrepSteps         db.NullRawJSON
	GuideSteps        db.NullRawJSON
	FindingOptions    db.NullRawJSON
	HideInPregnancy   bool
	Audiences         db.NullRawJSON
	IsActive          bool
	SortOrder         int32
	SourceNote        sql.NullString
	Now               sql.NullTime
	ID                uint64
}

func (q *Queries) UpdateAdminCheckupType(ctx context.Context, arg UpdateAdminCheckupTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminCheckupType,
		arg.Category,
		arg.Title,
		arg.Subtitle,
		arg.Why,
		arg.PerformedBy,
		arg.Icon,
		arg.Tone,
		arg.IntervalMonths,
		arg.IntervalMonthsMax,
		arg.AgeMin,
		arg.AgeMax,
		arg.CycleDayFrom,
		arg.CycleDayTo,
		arg.RemindLeadDays,
		arg.PrepSteps,
		arg.GuideSteps,
		arg.FindingOptions,
		arg.HideInPregnancy,
		arg.Audiences,
		arg.IsActive,
		arg.SortOrder,
		arg.SourceNote,
		arg.Now,
		arg.ID,
	)
	return err
}
