// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engine.sql

package store

import (
	"context"
)

const listActiveCheckupTypesForUser = `-- name: ListActiveCheckupTypesForUser :many

SELECT id, ` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone, interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to, remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy, is_active, sort_order, source_note, created_at, updated_at, audiences FROM ` + "`" + `checkup_types` + "`" + `
WHERE is_active = 1 AND (user_id IS NULL OR user_id = CAST(? AS UNSIGNED))
ORDER BY sort_order, id
`

// Checkups (T-M4-01): the inputs of the status engine (internal/checkups/engine) for one user.
// Every query is scoped by user_id; the catalog query returns the shared rows plus the user's own
// custom checkups only.
func (q *Queries) ListActiveCheckupTypesForUser(ctx context.Context, userID int64) ([]CheckupType, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCheckupTypesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupType{}
	for rows.Next() {
		var i CheckupType
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Subtitle,
			&i.Why,
			&i.PerformedBy,
			&i.Icon,
			&i.Tone,
			&i.IntervalMonths,
			&i.IntervalMonthsMax,
			&i.AgeMin,
			&i.AgeMax,
			&i.CycleDayFrom,
			&i.CycleDayTo,
			&i.RemindLeadDays,
			&i.PrepSteps,
			&i.GuideSteps,
			&i.FindingOptions,
			&i.HideInPregnancy,
			&i.IsActive,
			&i.SortOrder,
			&i.SourceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Audiences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckupRecordsForUser = `-- name: ListCheckupRecordsForUser :many
SELECT id, user_id, checkup_type_id, done_on, result, findings, note, has_attachment, next_due_on, created_at, updated_at FROM ` + "`" + `checkup_records` + "`" + `
WHERE user_id = ?
ORDER BY checkup_type_id, done_on DESC, id DESC
`

// Newest first per type (the engine reads the latest done_on and its next_due_on override).
func (q *Queries) ListCheckupRecordsForUser(ctx context.Context, userID uint64) ([]CheckupRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCheckupRecordsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupRecord{}
	for rows.Next() {
		var i CheckupRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckupTypeID,
			&i.DoneOn,
			&i.Result,
			&i.Findings,
			&i.Note,
			&i.HasAttachment,
			&i.NextDueOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckupSettingsForUser = `-- name: ListCheckupSettingsForUser :many
SELECT id, user_id, checkup_type_id, enabled, remind, created_at, updated_at FROM ` + "`" + `user_checkup_settings` + "`" + `
WHERE user_id = ?
ORDER BY checkup_type_id
`

func (q *Queries) ListCheckupSettingsForUser(ctx context.Context, userID uint64) ([]UserCheckupSetting, error) {
	rows, err := q.db.QueryContext(ctx, listCheckupSettingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCheckupSetting{}
	for rows.Next() {
		var i UserCheckupSetting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckupTypeID,
			&i.Enabled,
			&i.Remind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
