// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Checkups (T-M4-01): the inputs of the status engine (internal/checkups/engine) for one user.
	// Every query is scoped by user_id; the catalog query returns the shared rows plus the user's own
	// custom checkups only.
	ListActiveCheckupTypesForUser(ctx context.Context, userID int64) ([]CheckupType, error)
	// Newest first per type (the engine reads the latest done_on and its next_due_on override).
	ListCheckupRecordsForUser(ctx context.Context, userID uint64) ([]CheckupRecord, error)
	ListCheckupSettingsForUser(ctx context.Context, userID uint64) ([]UserCheckupSetting, error)
}

var _ Querier = (*Queries)(nil)
