// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/ritme/backend-go/db"
	"github.com/ritme/backend-go/internal/platform/civildate"
)

const countCheckupRecordHistory = `-- name: CountCheckupRecordHistory :one
SELECT COUNT(*) FROM ` + "`" + `checkup_records` + "`" + ` r
WHERE r.user_id = ?
  AND (? = 0 OR r.checkup_type_id = ?)
  AND r.done_on >= ?
  AND (CAST(? AS SIGNED) = 0 OR r.has_attachment = 1)
`

type CountCheckupRecordHistoryParams struct {
	UserID         uint64
	TypeID         uint64
	FromDate       civildate.Date
	WithAttachment int64
}

func (q *Queries) CountCheckupRecordHistory(ctx context.Context, arg CountCheckupRecordHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckupRecordHistory,
		arg.UserID,
		arg.TypeID,
		arg.TypeID,
		arg.FromDate,
		arg.WithAttachment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCheckupRecord = `-- name: DeleteCheckupRecord :execrows
DELETE FROM ` + "`" + `checkup_records` + "`" + `
WHERE id = ? AND user_id = ?
`

type DeleteCheckupRecordParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeleteCheckupRecord(ctx context.Context, arg DeleteCheckupRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCheckupRecord, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCustomCheckupType = `-- name: DeleteCustomCheckupType :execrows
DELETE FROM ` + "`" + `checkup_types` + "`" + `
WHERE id = ? AND user_id = ? AND category = 'custom'
`

type DeleteCustomCheckupTypeParams struct {
	ID     uint64
	UserID sql.NullInt64
}

func (q *Queries) DeleteCustomCheckupType(ctx context.Context, arg DeleteCustomCheckupTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCustomCheckupType, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCheckupRecord = `-- name: GetCheckupRecord :one
SELECT id, user_id, checkup_type_id, done_on, result, findings, note, has_attachment, next_due_on, created_at, updated_at FROM ` + "`" + `checkup_records` + "`" + `
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetCheckupRecordParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) GetCheckupRecord(ctx context.Context, arg GetCheckupRecordParams) (CheckupRecord, error) {
	row := q.db.QueryRowContext(ctx, getCheckupRecord, arg.ID, arg.UserID)
	var i CheckupRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckupTypeID,
		&i.DoneOn,
		&i.Result,
		&i.Findings,
		&i.Note,
		&i.HasAttachment,
		&i.NextDueOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckupSetting = `-- name: GetCheckupSetting :one
SELECT id, user_id, checkup_type_id, enabled, remind, created_at, updated_at FROM ` + "`" + `user_checkup_settings` + "`" + `
WHERE user_id = ? AND checkup_type_id = ?
LIMIT 1
`

type GetCheckupSettingParams struct {
	UserID        uint64
	CheckupTypeID uint64
}

func (q *Queries) GetCheckupSetting(ctx context.Context, arg GetCheckupSettingParams) (UserCheckupSetting, error) {
	row := q.db.QueryRowContext(ctx, getCheckupSetting, arg.UserID, arg.CheckupTypeID)
	var i UserCheckupSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckupTypeID,
		&i.Enabled,
		&i.Remind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckupTypeForUser = `-- name: GetCheckupTypeForUser :one
SELECT id, ` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone, interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to, remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy, is_active, sort_order, source_note, created_at, updated_at, audiences FROM ` + "`" + `checkup_types` + "`" + `
WHERE id = ? AND is_active = 1 AND (user_id IS NULL OR user_id = CAST(? AS UNSIGNED))
LIMIT 1
`

type GetCheckupTypeForUserParams struct {
	ID     uint64
	UserID int64
}

// An active type the user can see: a shared catalog row or her own custom checkup.
func (q *Queries) GetCheckupTypeForUser(ctx context.Context, arg GetCheckupTypeForUserParams) (CheckupType, error) {
	row := q.db.QueryRowContext(ctx, getCheckupTypeForUser, arg.ID, arg.UserID)
	var i CheckupType
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Subtitle,
		&i.Why,
		&i.PerformedBy,
		&i.Icon,
		&i.Tone,
		&i.IntervalMonths,
		&i.IntervalMonthsMax,
		&i.AgeMin,
		&i.AgeMax,
		&i.CycleDayFrom,
		&i.CycleDayTo,
		&i.RemindLeadDays,
		&i.PrepSteps,
		&i.GuideSteps,
		&i.FindingOptions,
		&i.HideInPregnancy,
		&i.IsActive,
		&i.SortOrder,
		&i.SourceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Audiences,
	)
	return i, err
}

const getCheckupUserContext = `-- name: GetCheckupUserContext :one

SELECT
  p.id AS profile_id,
  p.birthday,
  p.last_period_start,
  p.cycle_duration,
  p.period_duration,
  p.user_goal,
  CAST(EXISTS (
    SELECT 1 FROM ` + "`" + `pregnancy_profiles` + "`" + ` pp WHERE pp.user_id = u.id AND pp.pregnancy_mode = 1
  ) AS SIGNED) AS pregnant
FROM ` + "`" + `users` + "`" + ` u
LEFT JOIN ` + "`" + `user_profiles` + "`" + ` p ON p.user_id = u.id
WHERE u.id = ?
LIMIT 1
`

type GetCheckupUserContextRow struct {
	ProfileID       sql.NullInt64
	Birthday        civildate.NullDate
	LastPeriodStart civildate.NullDate
	CycleDuration   sql.NullInt16
	PeriodDuration  sql.NullInt16
	UserGoal        sql.NullString
	Pregnant        int64
}

// Checkups user API (T-M4-02, /api/v1/checkups/*). Every query is scoped by user_id; a catalog
// read returns the shared rows plus the user's own custom checkups only.
// The profile columns the cycle engine and the age rules read, plus pregnancy mode, in one read.
func (q *Queries) GetCheckupUserContext(ctx context.Context, id uint64) (GetCheckupUserContextRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckupUserContext, id)
	var i GetCheckupUserContextRow
	err := row.Scan(
		&i.ProfileID,
		&i.Birthday,
		&i.LastPeriodStart,
		&i.CycleDuration,
		&i.PeriodDuration,
		&i.UserGoal,
		&i.Pregnant,
	)
	return i, err
}

const getCustomCheckupType = `-- name: GetCustomCheckupType :one
SELECT id, ` + "`" + `key` + "`" + `, user_id, category, title, subtitle, why, performed_by, icon, tone, interval_months, interval_months_max, age_min, age_max, cycle_day_from, cycle_day_to, remind_lead_days, prep_steps, guide_steps, finding_options, hide_in_pregnancy, is_active, sort_order, source_note, created_at, updated_at, audiences FROM ` + "`" + `checkup_types` + "`" + `
WHERE id = ? AND user_id = ? AND category = 'custom'
LIMIT 1
`

type GetCustomCheckupTypeParams struct {
	ID     uint64
	UserID sql.NullInt64
}

func (q *Queries) GetCustomCheckupType(ctx context.Context, arg GetCustomCheckupTypeParams) (CheckupType, error) {
	row := q.db.QueryRowContext(ctx, getCustomCheckupType, arg.ID, arg.UserID)
	var i CheckupType
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Subtitle,
		&i.Why,
		&i.PerformedBy,
		&i.Icon,
		&i.Tone,
		&i.IntervalMonths,
		&i.IntervalMonthsMax,
		&i.AgeMin,
		&i.AgeMax,
		&i.CycleDayFrom,
		&i.CycleDayTo,
		&i.RemindLeadDays,
		&i.PrepSteps,
		&i.GuideSteps,
		&i.FindingOptions,
		&i.HideInPregnancy,
		&i.IsActive,
		&i.SortOrder,
		&i.SourceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Audiences,
	)
	return i, err
}

const insertCheckupRecord = `-- name: InsertCheckupRecord :execlastid
INSERT INTO ` + "`" + `checkup_records` + "`" + ` (
  user_id, checkup_type_id, done_on, result, findings, note, has_attachment, next_due_on, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCheckupRecordParams struct {
	UserID        uint64
	CheckupTypeID uint64
	DoneOn        civildate.Date
	Result        string
	Findings      db.NullRawJSON
	Note          sql.NullString
	HasAttachment bool
	NextDueOn     civildate.NullDate
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) InsertCheckupRecord(ctx context.Context, arg InsertCheckupRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCheckupRecord,
		arg.UserID,
		arg.CheckupTypeID,
		arg.DoneOn,
		arg.Result,
		arg.Findings,
		arg.Note,
		arg.HasAttachment,
		arg.NextDueOn,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertCustomCheckupType = `-- name: InsertCustomCheckupType :execlastid
INSERT INTO ` + "`" + `checkup_types` + "`" + ` (
  user_id, category, title, subtitle, performed_by, icon, tone, interval_months, remind_lead_days,
  is_active, sort_order, created_at, updated_at
) VALUES (?, 'custom', ?, ?, ?, ?, 'neutral', ?, ?, 1, ?, ?, ?)
`

type InsertCustomCheckupTypeParams struct {
	UserID         sql.NullInt64
	Title          json.RawMessage
	Subtitle       db.NullRawJSON
	PerformedBy    string
	Icon           sql.NullString
	IntervalMonths uint16
	RemindLeadDays uint16
	SortOrder      int32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) InsertCustomCheckupType(ctx context.Context, arg InsertCustomCheckupTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCustomCheckupType,
		arg.UserID,
		arg.Title,
		arg.Subtitle,
		arg.PerformedBy,
		arg.Icon,
		arg.IntervalMonths,
		arg.RemindLeadDays,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listCheckupPlanRows = `-- name: ListCheckupPlanRows :many
SELECT
  t.id, t.` + "`" + `key` + "`" + `, t.user_id, t.category, t.title, t.subtitle, t.why, t.performed_by, t.icon, t.tone, t.interval_months, t.interval_months_max, t.age_min, t.age_max, t.cycle_day_from, t.cycle_day_to, t.remind_lead_days, t.prep_steps, t.guide_steps, t.finding_options, t.hide_in_pregnancy, t.is_active, t.sort_order, t.source_note, t.created_at, t.updated_at, t.audiences,
  s.enabled AS setting_enabled,
  s.remind AS setting_remind,
  r.id AS record_id,
  r.done_on AS record_done_on,
  r.next_due_on AS record_next_due_on
FROM ` + "`" + `checkup_types` + "`" + ` t
LEFT JOIN ` + "`" + `user_checkup_settings` + "`" + ` s
  ON s.checkup_type_id = t.id AND s.user_id = CAST(? AS UNSIGNED)
LEFT JOIN ` + "`" + `checkup_records` + "`" + ` r ON r.id = (
  SELECT r2.id FROM ` + "`" + `checkup_records` + "`" + ` r2
  WHERE r2.user_id = CAST(? AS UNSIGNED) AND r2.checkup_type_id = t.id
  ORDER BY r2.done_on DESC, r2.id DESC
  LIMIT 1
)
WHERE t.is_active = 1 AND (t.user_id IS NULL OR t.user_id = CAST(? AS UNSIGNED))
ORDER BY t.sort_order, t.id
`

type ListCheckupPlanRowsParams struct {
	UserID int64
}

type ListCheckupPlanRowsRow struct {
	CheckupType     CheckupType
	SettingEnabled  sql.NullBool
	SettingRemind   sql.NullBool
	RecordID        sql.NullInt64
	RecordDoneOn    civildate.NullDate
	RecordNextDueOn civildate.NullDate
}

// The active catalog with the user's setting and latest record per type, in one read
// (latest = highest done_on, ties → higher id, like the engine).
func (q *Queries) ListCheckupPlanRows(ctx context.Context, arg ListCheckupPlanRowsParams) ([]ListCheckupPlanRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCheckupPlanRows, arg.UserID, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckupPlanRowsRow{}
	for rows.Next() {
		var i ListCheckupPlanRowsRow
		if err := rows.Scan(
			&i.CheckupType.ID,
			&i.CheckupType.Key,
			&i.CheckupType.UserID,
			&i.CheckupType.Category,
			&i.CheckupType.Title,
			&i.CheckupType.Subtitle,
			&i.CheckupType.Why,
			&i.CheckupType.PerformedBy,
			&i.CheckupType.Icon,
			&i.CheckupType.Tone,
			&i.CheckupType.IntervalMonths,
			&i.CheckupType.IntervalMonthsMax,
			&i.CheckupType.AgeMin,
			&i.CheckupType.AgeMax,
			&i.CheckupType.CycleDayFrom,
			&i.CheckupType.CycleDayTo,
			&i.CheckupType.RemindLeadDays,
			&i.CheckupType.PrepSteps,
			&i.CheckupType.GuideSteps,
			&i.CheckupType.FindingOptions,
			&i.CheckupType.HideInPregnancy,
			&i.CheckupType.IsActive,
			&i.CheckupType.SortOrder,
			&i.CheckupType.SourceNote,
			&i.CheckupType.CreatedAt,
			&i.CheckupType.UpdatedAt,
			&i.CheckupType.Audiences,
			&i.SettingEnabled,
			&i.SettingRemind,
			&i.RecordID,
			&i.RecordDoneOn,
			&i.RecordNextDueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckupRecordHistory = `-- name: ListCheckupRecordHistory :many
SELECT
  r.id, r.user_id, r.checkup_type_id, r.done_on, r.result, r.findings, r.note, r.has_attachment, r.next_due_on, r.created_at, r.updated_at,
  t.title AS checkup_title,
  t.` + "`" + `key` + "`" + ` AS checkup_key,
  t.icon AS checkup_icon,
  t.tone AS checkup_tone
FROM ` + "`" + `checkup_records` + "`" + ` r
JOIN ` + "`" + `checkup_types` + "`" + ` t ON t.id = r.checkup_type_id
WHERE r.user_id = ?
  AND (? = 0 OR r.checkup_type_id = ?)
  AND r.done_on >= ?
  AND (CAST(? AS SIGNED) = 0 OR r.has_attachment = 1)
ORDER BY r.done_on DESC, r.id DESC
LIMIT ? OFFSET ?
`

type ListCheckupRecordHistoryParams struct {
	UserID         uint64
	TypeID         uint64
	FromDate       civildate.Date
	WithAttachment int64
	Limit          int32
	Offset         int32
}

type ListCheckupRecordHistoryRow struct {
	CheckupRecord CheckupRecord
	CheckupTitle  json.RawMessage
	CheckupKey    sql.NullString
	CheckupIcon   sql.NullString
	CheckupTone   string
}

// The History timeline, newest first, with the checkup's title/icon/tone.
func (q *Queries) ListCheckupRecordHistory(ctx context.Context, arg ListCheckupRecordHistoryParams) ([]ListCheckupRecordHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listCheckupRecordHistory,
		arg.UserID,
		arg.TypeID,
		arg.TypeID,
		arg.FromDate,
		arg.WithAttachment,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckupRecordHistoryRow{}
	for rows.Next() {
		var i ListCheckupRecordHistoryRow
		if err := rows.Scan(
			&i.CheckupRecord.ID,
			&i.CheckupRecord.UserID,
			&i.CheckupRecord.CheckupTypeID,
			&i.CheckupRecord.DoneOn,
			&i.CheckupRecord.Result,
			&i.CheckupRecord.Findings,
			&i.CheckupRecord.Note,
			&i.CheckupRecord.HasAttachment,
			&i.CheckupRecord.NextDueOn,
			&i.CheckupRecord.CreatedAt,
			&i.CheckupRecord.UpdatedAt,
			&i.CheckupTitle,
			&i.CheckupKey,
			&i.CheckupIcon,
			&i.CheckupTone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckupRecordsOfType = `-- name: ListCheckupRecordsOfType :many
SELECT id, user_id, checkup_type_id, done_on, result, findings, note, has_attachment, next_due_on, created_at, updated_at FROM ` + "`" + `checkup_records` + "`" + `
WHERE user_id = ? AND checkup_type_id = ?
ORDER BY done_on DESC, id DESC
LIMIT ?
`

type ListCheckupRecordsOfTypeParams struct {
	UserID        uint64
	CheckupTypeID uint64
	Limit         int32
}

func (q *Queries) ListCheckupRecordsOfType(ctx context.Context, arg ListCheckupRecordsOfTypeParams) ([]CheckupRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCheckupRecordsOfType, arg.UserID, arg.CheckupTypeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckupRecord{}
	for rows.Next() {
		var i CheckupRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckupTypeID,
			&i.DoneOn,
			&i.Result,
			&i.Findings,
			&i.Note,
			&i.HasAttachment,
			&i.NextDueOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckupRecord = `-- name: UpdateCheckupRecord :exec
UPDATE ` + "`" + `checkup_records` + "`" + `
SET done_on = ?, result = ?, findings = ?, note = ?, has_attachment = ?, next_due_on = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateCheckupRecordParams struct {
	DoneOn        civildate.Date
	Result        string
	Findings      db.NullRawJSON
	Note          sql.NullString
	HasAttachment bool
	NextDueOn     civildate.NullDate
	UpdatedAt     sql.NullTime
	ID            uint64
	UserID        uint64
}

func (q *Queries) UpdateCheckupRecord(ctx context.Context, arg UpdateCheckupRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckupRecord,
		arg.DoneOn,
		arg.Result,
		arg.Findings,
		arg.Note,
		arg.HasAttachment,
		arg.NextDueOn,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateCustomCheckupType = `-- name: UpdateCustomCheckupType :exec
UPDATE ` + "`" + `checkup_types` + "`" + `
SET title = ?, subtitle = ?, performed_by = ?, icon = ?, interval_months = ?, remind_lead_days = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND category = 'custom'
`

type UpdateCustomCheckupTypeParams struct {
	Title          json.RawMessage
	Subtitle       db.NullRawJSON
	PerformedBy    string
	Icon           sql.NullString
	IntervalMonths uint16
	RemindLeadDays uint16
	UpdatedAt      sql.NullTime
	ID             uint64
	UserID         sql.NullInt64
}

func (q *Queries) UpdateCustomCheckupType(ctx context.Context, arg UpdateCustomCheckupTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomCheckupType,
		arg.Title,
		arg.Subtitle,
		arg.PerformedBy,
		arg.Icon,
		arg.IntervalMonths,
		arg.RemindLeadDays,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const upsertCheckupSetting = `-- name: UpsertCheckupSetting :exec
INSERT INTO ` + "`" + `user_checkup_settings` + "`" + ` (user_id, checkup_type_id, enabled, remind, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  enabled = VALUES(enabled),
  remind = VALUES(remind),
  updated_at = VALUES(updated_at)
`

type UpsertCheckupSettingParams struct {
	UserID        uint64
	CheckupTypeID uint64
	Enabled       bool
	Remind        bool
	Now           sql.NullTime
}

// One row per (user_id, checkup_type_id); created_at is kept on update.
func (q *Queries) UpsertCheckupSetting(ctx context.Context, arg UpsertCheckupSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheckupSetting,
		arg.UserID,
		arg.CheckupTypeID,
		arg.Enabled,
		arg.Remind,
		arg.Now,
		arg.Now,
	)
	return err
}
