// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: info_sections.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/ritme/backend-go/db"
)

const listActiveInfoSections = `-- name: ListActiveInfoSections :many

SELECT id, heading, body, link_label, link_url
FROM ` + "`" + `info_sections` + "`" + `
WHERE ` + "`" + `group` + "`" + ` = ? AND is_active = 1
ORDER BY sort_order, id
`

type ListActiveInfoSectionsRow struct {
	ID        uint64
	Heading   json.RawMessage
	Body      json.RawMessage
	LinkLabel db.NullRawJSON
	LinkUrl   sql.NullString
}

// info_sections (App\Models\InfoSection), read side of InfoController.
// InfoSection::inGroup($group)->active()->ordered()->get().
func (q *Queries) ListActiveInfoSections(ctx context.Context, group string) ([]ListActiveInfoSectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveInfoSections, group)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveInfoSectionsRow{}
	for rows.Next() {
		var i ListActiveInfoSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Heading,
			&i.Body,
			&i.LinkLabel,
			&i.LinkUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
