// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phase_contents.sql

package store

import (
	"context"

	"github.com/ritme/backend-go/db"
)

const getPhaseContent = `-- name: GetPhaseContent :one

SELECT id, phase, symptom_prediction, vaginal_discharge, fertility, hormonal_changes,
       sex_tips, nutrition, exercise, skin_care, sleep
FROM ` + "`" + `phase_contents` + "`" + `
WHERE phase = ?
LIMIT 1
`

type GetPhaseContentRow struct {
	ID                uint64
	Phase             string
	SymptomPrediction db.NullRawJSON
	VaginalDischarge  db.NullRawJSON
	Fertility         db.NullRawJSON
	HormonalChanges   db.NullRawJSON
	SexTips           db.NullRawJSON
	Nutrition         db.NullRawJSON
	Exercise          db.NullRawJSON
	SkinCare          db.NullRawJSON
	Sleep             db.NullRawJSON
}

// phase_contents (App\Models\PhaseContent).
// PhaseContent::getByPhase($phase): where('phase', $phase)->first().
func (q *Queries) GetPhaseContent(ctx context.Context, phase string) (GetPhaseContentRow, error) {
	row := q.db.QueryRowContext(ctx, getPhaseContent, phase)
	var i GetPhaseContentRow
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.SymptomPrediction,
		&i.VaginalDischarge,
		&i.Fertility,
		&i.HormonalChanges,
		&i.SexTips,
		&i.Nutrition,
		&i.Exercise,
		&i.SkinCare,
		&i.Sleep,
	)
	return i, err
}
