// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package store

import (
	"context"
)

const getActivePlan = `-- name: GetActivePlan :one
SELECT id, code, title, badge, duration_months, price_rials, monthly_display_rials, is_highlighted, is_active, sort_order, created_at, updated_at FROM plus_plans
WHERE id = ? AND is_active = 1
`

func (q *Queries) GetActivePlan(ctx context.Context, id uint64) (PlusPlan, error) {
	row := q.db.QueryRowContext(ctx, getActivePlan, id)
	var i PlusPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Badge,
		&i.DurationMonths,
		&i.PriceRials,
		&i.MonthlyDisplayRials,
		&i.IsHighlighted,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, code, title, badge, duration_months, price_rials, monthly_display_rials, is_highlighted, is_active, sort_order, created_at, updated_at FROM plus_plans
WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id uint64) (PlusPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i PlusPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Badge,
		&i.DurationMonths,
		&i.PriceRials,
		&i.MonthlyDisplayRials,
		&i.IsHighlighted,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many

SELECT id, code, title, badge, duration_months, price_rials, monthly_display_rials, is_highlighted, is_active, sort_order, created_at, updated_at FROM plus_plans
WHERE is_active = 1
ORDER BY sort_order, id
`

// Ritme Plus plans (admin data; B-N2-09 owns the CRUD).
func (q *Queries) ListActivePlans(ctx context.Context) ([]PlusPlan, error) {
	rows, err := q.db.QueryContext(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlusPlan{}
	for rows.Next() {
		var i PlusPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Badge,
			&i.DurationMonths,
			&i.PriceRials,
			&i.MonthlyDisplayRials,
			&i.IsHighlighted,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
