// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"
	"database/sql"

	"github.com/ritme/backend-go/internal/platform/civildate"
)

const incrementUsage = `-- name: IncrementUsage :exec
INSERT INTO plus_usage_counters (user_id, feature, period_start, used, created_at, updated_at)
VALUES (?, ?, ?, 1, ?, ?)
ON DUPLICATE KEY UPDATE updated_at = VALUES(updated_at), used = used + 1
`

type IncrementUsageParams struct {
	UserID      uint64
	Feature     string
	PeriodStart civildate.Date
	Now         sql.NullTime
}

// Unlimited features: always count.
func (q *Queries) IncrementUsage(ctx context.Context, arg IncrementUsageParams) error {
	_, err := q.db.ExecContext(ctx, incrementUsage,
		arg.UserID,
		arg.Feature,
		arg.PeriodStart,
		arg.Now,
		arg.Now,
	)
	return err
}

const incrementUsageWithin = `-- name: IncrementUsageWithin :execrows
INSERT INTO plus_usage_counters (user_id, feature, period_start, used, created_at, updated_at)
VALUES (?, ?, ?, 1, ?, ?)
ON DUPLICATE KEY UPDATE
  updated_at = IF(used < ?, VALUES(updated_at), updated_at),
  used = IF(used < ?, used + 1, used)
`

type IncrementUsageWithinParams struct {
	UserID      uint64
	Feature     string
	PeriodStart civildate.Date
	Now         sql.NullTime
	Quota       uint32
}

// Quota features: count only while used < limit, atomically (1 = inserted, 2 = incremented, 0 = quota reached).
// updated_at is assigned first because MariaDB evaluates the SET list left to right with the new values.
func (q *Queries) IncrementUsageWithin(ctx context.Context, arg IncrementUsageWithinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementUsageWithin,
		arg.UserID,
		arg.Feature,
		arg.PeriodStart,
		arg.Now,
		arg.Now,
		arg.Quota,
		arg.Quota,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listUsage = `-- name: ListUsage :many

SELECT feature, used FROM plus_usage_counters
WHERE user_id = ? AND period_start = ?
`

type ListUsageParams struct {
	UserID      uint64
	PeriodStart civildate.Date
}

type ListUsageRow struct {
	Feature string
	Used    uint32
}

// Monthly feature usage counters (quotas + the trial sheet's usage lines).
func (q *Queries) ListUsage(ctx context.Context, arg ListUsageParams) ([]ListUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsage, arg.UserID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageRow{}
	for rows.Next() {
		var i ListUsageRow
		if err := rows.Scan(&i.Feature, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageSince = `-- name: SumUsageSince :many
SELECT feature, CAST(SUM(used) AS UNSIGNED) AS used FROM plus_usage_counters
WHERE user_id = ? AND period_start >= ?
GROUP BY feature
`

type SumUsageSinceParams struct {
	UserID uint64
	Since  civildate.Date
}

type SumUsageSinceRow struct {
	Feature string
	Used    int64
}

// The trial sheet's «این روزها از پلاس استفاده کردی» lines: uses per feature over every quota month from `since`
// (the first day of the trial's start month) on — a 7-day trial can straddle two months.
func (q *Queries) SumUsageSince(ctx context.Context, arg SumUsageSinceParams) ([]SumUsageSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUsageSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageSinceRow{}
	for rows.Next() {
		var i SumUsageSinceRow
		if err := rows.Scan(&i.Feature, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
