// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package store

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :execlastid

INSERT INTO ` + "`" + `files` + "`" + ` (user_id, purpose, visibility, mime, size_bytes, sha256, path, created_at, updated_at)
VALUES (?, ?, ?, ?, ?,
        ?, ?, ?, ?)
`

type CreateFileParams struct {
	UserID     sql.NullInt64
	Purpose    string
	Visibility string
	Mime       string
	SizeBytes  uint32
	Sha256     string
	Path       string
	Now        sql.NullTime
}

// Generic encrypted file storage (CB-CORE-05; internal/files). Owner-facing queries are scoped by user_id in the query
// itself (IDOR). GetFile reads by id only: it serves the signed-URL and public downloads, which prove their right to
// the row with an HMAC over the row's owner and path, or with the public purpose + the random file name.
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFile,
		arg.UserID,
		arg.Purpose,
		arg.Visibility,
		arg.Mime,
		arg.SizeBytes,
		arg.Sha256,
		arg.Path,
		arg.Now,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteOwnedFile = `-- name: DeleteOwnedFile :execrows
DELETE FROM ` + "`" + `files` + "`" + ` WHERE id = ? AND user_id = ?
`

type DeleteOwnedFileParams struct {
	ID     uint64
	UserID sql.NullInt64
}

func (q *Queries) DeleteOwnedFile(ctx context.Context, arg DeleteOwnedFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOwnedFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePlatformFile = `-- name: DeletePlatformFile :execrows
DELETE FROM ` + "`" + `files` + "`" + ` WHERE id = ? AND user_id IS NULL
`

func (q *Queries) DeletePlatformFile(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlatformFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFile = `-- name: GetFile :one
SELECT id, user_id, purpose, visibility, mime, size_bytes, sha256, path, created_at, updated_at FROM ` + "`" + `files` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id uint64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Visibility,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedFile = `-- name: GetOwnedFile :one
SELECT id, user_id, purpose, visibility, mime, size_bytes, sha256, path, created_at, updated_at FROM ` + "`" + `files` + "`" + ` WHERE id = ? AND user_id = ? LIMIT 1
`

type GetOwnedFileParams struct {
	ID     uint64
	UserID sql.NullInt64
}

func (q *Queries) GetOwnedFile(ctx context.Context, arg GetOwnedFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getOwnedFile, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Visibility,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformFile = `-- name: GetPlatformFile :one
SELECT id, user_id, purpose, visibility, mime, size_bytes, sha256, path, created_at, updated_at FROM ` + "`" + `files` + "`" + ` WHERE id = ? AND user_id IS NULL LIMIT 1
`

func (q *Queries) GetPlatformFile(ctx context.Context, id uint64) (File, error) {
	row := q.db.QueryRowContext(ctx, getPlatformFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Visibility,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnerPaths = `-- name: ListOwnerPaths :many
SELECT path FROM ` + "`" + `files` + "`" + ` WHERE user_id = ? AND purpose = ?
`

type ListOwnerPathsParams struct {
	UserID  sql.NullInt64
	Purpose string
}

// The orphan sweep: the stored paths of one owner and purpose (blobs on disk without one are removed).
func (q *Queries) ListOwnerPaths(ctx context.Context, arg ListOwnerPathsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerPaths, arg.UserID, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformPaths = `-- name: ListPlatformPaths :many
SELECT path FROM ` + "`" + `files` + "`" + ` WHERE user_id IS NULL AND purpose = ?
`

func (q *Queries) ListPlatformPaths(ctx context.Context, purpose string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformPaths, purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwner = `-- name: LockOwner :one
SELECT id FROM ` + "`" + `users` + "`" + ` WHERE id = ? FOR UPDATE
`

// First statement of a user's upload transaction: the user row lock serialises that user's uploads, so the usage
// reads below never race (two gap locks on an empty range would otherwise deadlock on insert).
func (q *Queries) LockOwner(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockOwner, id)
	var id_2 uint64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockOwnerUsage = `-- name: LockOwnerUsage :one
SELECT COUNT(*) AS files, CAST(COALESCE(SUM(size_bytes), 0) AS UNSIGNED) AS bytes
FROM ` + "`" + `files` + "`" + ` WHERE user_id = ? AND purpose = ? FOR UPDATE
`

type LockOwnerUsageParams struct {
	UserID  sql.NullInt64
	Purpose string
}

type LockOwnerUsageRow struct {
	Files int64
	Bytes int64
}

// Inside the upload transaction: the owner's files of one purpose, locked (next-key locks on the (user_id, purpose)
// range) so two concurrent uploads cannot both pass the quota.
func (q *Queries) LockOwnerUsage(ctx context.Context, arg LockOwnerUsageParams) (LockOwnerUsageRow, error) {
	row := q.db.QueryRowContext(ctx, lockOwnerUsage, arg.UserID, arg.Purpose)
	var i LockOwnerUsageRow
	err := row.Scan(&i.Files, &i.Bytes)
	return i, err
}

const lockPlatformUsage = `-- name: LockPlatformUsage :one
SELECT COUNT(*) AS files, CAST(COALESCE(SUM(size_bytes), 0) AS UNSIGNED) AS bytes
FROM ` + "`" + `files` + "`" + ` WHERE user_id IS NULL AND purpose = ? FOR UPDATE
`

type LockPlatformUsageRow struct {
	Files int64
	Bytes int64
}

func (q *Queries) LockPlatformUsage(ctx context.Context, purpose string) (LockPlatformUsageRow, error) {
	row := q.db.QueryRowContext(ctx, lockPlatformUsage, purpose)
	var i LockPlatformUsageRow
	err := row.Scan(&i.Files, &i.Bytes)
	return i, err
}
