// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Generic encrypted file storage (CB-CORE-05; internal/files). Owner-facing queries are scoped by user_id in the query
	// itself (IDOR). GetFile reads by id only: it serves the signed-URL and public downloads, which prove their right to
	// the row with an HMAC over the row's owner and path, or with the public purpose + the random file name.
	CreateFile(ctx context.Context, arg CreateFileParams) (int64, error)
	DeleteOwnedFile(ctx context.Context, arg DeleteOwnedFileParams) (int64, error)
	DeletePlatformFile(ctx context.Context, id uint64) (int64, error)
	GetFile(ctx context.Context, id uint64) (File, error)
	GetOwnedFile(ctx context.Context, arg GetOwnedFileParams) (File, error)
	GetPlatformFile(ctx context.Context, id uint64) (File, error)
	// The orphan sweep: the stored paths of one owner and purpose (blobs on disk without one are removed).
	ListOwnerPaths(ctx context.Context, arg ListOwnerPathsParams) ([]string, error)
	ListPlatformPaths(ctx context.Context, purpose string) ([]string, error)
	// First statement of a user's upload transaction: the user row lock serialises that user's uploads, so the usage
	// reads below never race (two gap locks on an empty range would otherwise deadlock on insert).
	LockOwner(ctx context.Context, id uint64) (uint64, error)
	// Inside the upload transaction: the owner's files of one purpose, locked (next-key locks on the (user_id, purpose)
	// range) so two concurrent uploads cannot both pass the quota.
	LockOwnerUsage(ctx context.Context, arg LockOwnerUsageParams) (LockOwnerUsageRow, error)
	LockPlatformUsage(ctx context.Context, purpose string) (LockPlatformUsageRow, error)
}

var _ Querier = (*Queries)(nil)
